### ISSUE TITLE
is the .rotation of items the same as .rotation of a group?  (one seems to want degrees, the other radians) 

### ISSUE THREAD

**Issue by ofZach** [paperjs/paper.js#1004]
I have found .rotation to be slightly inconsistent -- one issue is that items seem to want radians while groups want degrees.  is (xxx.rotation =) not right for user facing setting angle?  I see in the docs you use .rotate(...) but I find it easier when sketching to do fixed rotation rather than relative. 

for example I see this: 

http://sketch.paperjs.org/#S/jVJNT4QwEP0rEy4LSghqYiKbPcgmetHE6BH2UGCAZrtTUgpGN/vfbSmaNXqgTdPMx5v3ZtqjR+yAXuK97VGXrRd6paysnZPbI1OgsNT3sAHCd3hhuo1ejYNRI9DPCcw6uquTnHQC2U0ch+bsQlNA9/wTje/K+G5nV82F2EohVQKrRuHHysFPOQXnlOlyyklhVMiBqj7SsnvCWsMlZNeGdZmOQgz4j45GyaH77v3RGv7EFazP4umfeGrjOTl01PFRapPzS2WJpFGtf5JYVW1bLirflXQF6oFKzSWBpAdlHsrH0cCCufkZqaRmU9IG7mK4gGc7r56TS440P6CtZhFOwULAyfyGQiHbT0PuvSTbnb4A

but this is the expected result: 

http://sketch.paperjs.org/#S/jVJRa4MwEP4rhy/VTZzrYDBLH2ZhY7BB2R61D1FPDbUXidGxFf/7orHDsQ2aEMLdfd/dd5ccLWIHtALrbY8qLS3XSkU22DGZ3TEJElN1D2sgfIctU6X3qh2MigrtmECvo7lqwUkFEN34vqvPztUJVMM/Ufuute92cuW8qjaiEjKARSHxY2HofUzOvGR4fslRoZeIlrLGU6J+xlzBJURLXfU8HUnV4h86Cina+tT742DYYy1nNYuHv+LhEI/JsL2ad0JpzA+VKZJCufoGsSzblLzKbJPSJMhbShUXBIIepH4oGztNc6bmJ6YUio2gNdz5cAEvw7waTgbsKX7AIdvAMApmBHsEb5+uls7/zF5/i0Qi24/Tbqwg2vVf

**Comment by ofZach** [comment]
this also seems inconsistent: 

http://sketch.paperjs.org/#S/pVNLa4NAEP4rg5doKpKkUKghh67QXloo7THmsNGJLjGzsq4pbch/7+qah6SFlCoqO99jPnd05xDfoBM672vUSe74TiLTZh2TPbdcgcJEP8AMCD/gles8eDMFTlmBbkxgjp19lFKQDmF+Oxr55lr4xkBX4gtNbWxqd11pJYoikoVUIQwyhZ8DK9/H5J23ZNe3bBMGS1lTWgVals+40nAD84npel2OZVHjLzmiv+Vg/8pRClr/kCNTsi4PM3hqFm77zt70DGcXOOvh0QUeNXhM1j0oxVZqw+ntZoKkUU07EuuR2AXp6MXTNMpFkbpW5p0M+kiXYFVTooUkkPSozBfp4tZYet3u2nvnrKTmLXUG9yMYwkszlkqQlQRabLDxPCrYNYrhOJgcVDHtzX+wVMjX7VgrJ5wv9t8=

this is more of the expected behavior: 

http://sketch.paperjs.org/#S/pVPfa4MwEP5XDl+qXXFtB4NZ+rAIG4MNyvZY+5DqtQ21F4mxYyv93xeNdko36Jiikvt+3GdODw7xHTqB87ZFHW+cgRPLpFxHZM89V6Aw1vcwBcJ3mHG98V9NgdM6RTciMMfBPjIpSAcwvxkOB+ZaDIyBzsUnmtrI1G7r0kqkaShTqQLorRV+9Kz8GJHXbskub1kl9JeyoCT3tcyecaXhCuZj0/WyHMu0wF9yhH/Lwf6VIxO0/SHHWskia2bwWC7c6p29SQtnZzjr4OEZHpZ4RNbdz8ReasPp7GaMpFFNahLrkNgZ6eTFkyTciDRxrcz7NugidYJVQbEWkkDSgzJfpIt7Y+nVu2vvtbOSmlfUKdwNoQ8v5VhyQVbia7HD0vOkYG2FW7FnT9djr5HGMm9J+yN/3MgjOpofYqmQb6v55k4wXxy/AA==

**Comment by lehni** [comment]
@ofZach I have finally found time to look into this. The problem is not one of radians vs degrees, but one of caching.

Some explanations:

* By default, all scene graph items in paper.js bake the transformations applied to the them directly into their content, instead of just storing them in their `matrix` property. This explains why `path.matrix` is still the identity matrix, even after just rotating an item. The behavior applies to all items that store geometries in their content, so `Path` & `CompoundPath` as well as `Group` & `Layer` (those can just pass on the transformation to whatever they're containing). You can change this behavior for new items by globally changing `settings.applyMatrix` to false, or by controlling it on an item level through `item.applyMatrix`. Note that setting it to true on `Shape`, `Raster` & `SymbolItem` items will not have any effect (it will remain false).

* For items that have `item.applyMatrix`set to false, transformations are stored in `item.matrix`. For these item, we offer short cuts to the most common transformations through `item.rotation` and `item.scaling`. These are not actual internally stored values, they are deducted from decomposing the transformation stored in `item.matrix`.

Now on top of this, I wanted to make `item.rotation` and `item.scaling` work on items that do have `item.applyMatrix` set to true, by caching the values of these properties, and changing the cache when they change.

Your example illustrates why this is a bad idea: You mix groups and paths that both apply their transformations. So when you change `group.rotation`, this gets both cached on group as well as passed down as a transformation to the actually contained item. The item receives it as a matrix and bakes it right into its content, does not cache the rotation value, and has no way of decomposing the matrix later on, since it's baked in.

So the bottom line I believe is: We should not cache these values and always use decomposition, and we should not support `item.rotation` and `item.scaling` on items that have `item.applyMatrix` set to true. They should alway return 0 there, since their `item.matrix` will always be the identity matrix. Setting them can b supported, in a way that `item.rotation = 10` will do the same as `item.rotate(10)`.

Do you see what I mean?

**Comment by lehni** [comment]
The downside of my proposal is that it will almost certainly break existing code....

**Comment by lehni** [comment]
Due to #1177 I had to make yet another change to how this is handled and bringing caching back again, but only on items that have #applyMatrix set to false. On all other items, #rotation and #scaling will not do anything now, which I think is the better way to handle this. The documentation will reflect this.

[Updated Sketch](http://sketch.paperjs.org/#S/jVJRS8MwEP4rR1/WailVQbBjD3agLw5EH9c9ZO21C8suJblO59h/N23mmOjDAiHcl/u+++6SfUBig0EWvK+Ry1UQB6Wu+tgis6TGJqJt1W4m2MhPmEAtlMVxQQVthQGDJT86lPADXgWvkjcHCGoUhgWBW3t/tFoSZzC/S9PY7UXsBNjKL3TYjcPuj1AtlZpqpU0Go8bgbuTph4Ki85L55SUHh8lSd1TZhHX7gjXDNcxvXdXLfCxVh//4aIzu2p/en/sgHGpF47P7/M99Hg3D8+yklVvNLueXyxKJ0YxPSaKqpiupqtBLeoG6o5KlJtD0ZNwLhrh1tOjY/JFpNIshaQIPKVzBrJ+XleSTE5Yb7NV6hndwIeHgvsnSoFgPQ7ZBNl8cvgE=)
