### ISSUE TITLE
Graphical error on stroked paths

### ISSUE THREAD

**Issue by samuelpmish** [paperjs/paper.js#1010]
Hi, I'm new to Github and paper.js, but I was writing a little interactive tool and noticed a strange problem with stroked curves for certain placements of handles and segments.

An example of the problem can be seen in [this video](https://www.youtube.com/watch?v=Y2kAN5h2Sv8), which was created with [this example sketch](http://sketch.paperjs.org/#S/nVRBz9MwDP0rVi9roasGiEurneDCAYEYEgc+9Clt3TUsS6ok3b4x7b+TNmubdJuQOFRq7Odn+8XxOeBkj0EabHaoizqIg0KU3RngQCTkuXjJnuQT7z5rqql+Fo2mgitYwxkUbvfItUpByxZjqAkvGY5HhQwLjeVw1oKhJLzAFN68h0tmiSf6PZFbyg3z21U2WZUmUhsjxyN8FZTr8B28umJjmP4jJwZ56UUcKB4TRf9gcqSlrmEJLsfkrZFua+25o5kGuSRFPZATXYdD3t6RKC3FDj8IJqQBLXJGit3CQ5CyDPueohuzKdtNZx0VlUpvrNKJVfhLOxNktYph5fMxMo/6xL2gpRv1MOFwhya0u8SHKe7hXGzBhOq9FWEK70j2o7+YtZmMe3qSplNTipaXi9mF2MxmJjNvUL+hapl2sFXLexgI/lm0Cj+KIw/xYIqPzhMKJr5OrZaxbHCMpMbRSPHboBJj+45KW56k6YSN3WfiqgtAKwhHlmiw+ilHf3J9XQ7DxX0xN/1Isr3XD63Ckd96bFKvmESfGoS10fiadeGU5xRoW4TXa7Adl8g0yf5JagdwSfkj2nFC/5NZtA8rnp7MA+7LTOAbeU1OsxzCCDxdu/3YbcEp6wtLh53iGGVqF0zeDa8aF9AN8KTvRJ9yP3pcUBY5tuCNmWDlxhRsihs3mztEZtHnEsmuv0oVpD9/Xf4C)

Is there a workaround, or am I just using paper.js in a funny way?

**Comment by iconexperience** [comment]
Welcome to paper.js. The problem that you are seeing is probably a bug in Chrome. We worked a lot with curves a while ago and I noticed that Chrome sometimes renders curves not correctly. At the beginning I thought those were paper.js problems, too, but then I realized that they were cause by the browser.

<a href="http://sketch.paperjs.org/#S/XVHLagMxDPyVZU8tbI31sGQl9B8KOSY5pInblGwebDYtJeTfq91AKQVjrEEzGmuu9WG1L/Wknu1Kv97WTb0+bob6c9VVp1W/heq5OpSv6sXfD9dzed+XQ3+ezBfd4jBnzEGSZREjQEw5NRUgBWQvDYQkImFTxd+zbO5EzsGUkBIRQzTnocWARCMFNNug9QQBvQ1INYOZCTvmbSw+EY2zN6qyjmiUbCLsGqoWAeWORlbgLIqRYxa//1sgYyVR/WsBSNyA3T37PEBNgNFHRkEZfhQiCBuLJXZvigKybKpRmTQFYtcgt+T2YNhKikGTlzGTkA3T/ixloDl73R7PZTPpu0u5PU4HcEwgvF3a9ntW2rLuy8bzGBqmHtVrV1a70/HDA6kn8+XtBw==">Here is a rather extreme example of a path with four points that is rendered wrongly</a>

On the other hand, I cannot rule out that the glitch is not caused by paper.js, so maybe you can try reproducing the issue on Firefox, which seems to be better with this.

**Comment by iconexperience** [comment]
The issue looks very much like this problem:

https://bugs.chromium.org/p/chromium/issues/detail?id=514246

But that should have been fixed since Chrome 46. Can you let us know which is the latest version of Chrome (if you are using Chrome at all) that you can reproduce this bug on?

**Comment by lehni** [comment]
Yes, @iconexperience is right. This is a bug in the underlying canvas implementation and unfortunately not something we can fix in paper.js. We have to wait for the browser vendors to improve their implementations.

**Comment by samuelpmish** [comment]
Just as a followup, I was experiencing the error with Chrome 48, but after upgrading to 49, I can't seem to reproduce it! Thanks for the help.

**Comment by lehni** [comment]
I'm glad to hear they fixed it so quickly!

**Comment by iconexperience** [comment]
@samuelpmish That's actually great news, thanks.
