### ISSUE TITLE
insertChild() wrong index when re-inserting item into parent with higher index

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1015]
When using `Item#insertChild()` on an item and specifying its current parent but at an index `n` where `n > Item#index` the resulting index is `n - 1`:

[Example of issue](http://sketch.paperjs.org/#S/jZDNCoMwEIRfJeSkEIIGvFR66hvUo3pIdavBdCMx/YHSd2+i/fPWPe3sxwzD3inKE9ANLQZwTU8ZbUwb9EVaYqFxKdkShCspejkC3/uLxE5DFG5fVSaMJDUjZeaXLKnjmFVI/IQI8V+EyBgR2SokX0IqnJvwUNVnVXSWFc0XINZAfEDKj0rrndHGvmj7Y1qzgz7DDN/WUVpAxxVOYN2uV7qNUra8JPRqDE5GA9emixaDwhZuce5feLAgh9EodBPdlPXjCQ==)

This is not the case for `addLayer()` which makes me think the index correcting code post removal of the item in `Item#insertChildren()` is to blame as `Project#addLayer()` just removes and splices and ends up with the correct result:

[Project#addLayer() test](http://sketch.paperjs.org/#S/pZCxCsIwEIZfJWRphRBoukV8AzdH6xDjobXxEpKgSOm7mzQuuhTxtv/4vh/uRorqBlTS3QBRXyij2p5yvitPjHqCb8iGIDyIUw483+ZVPWZJkqoA1bRiHZI0cxZLgvgS2iWhTcK6CB1qi8Ea4Mae62I4b6+gI5/ZkMnPfY8BfCy9DXtflbH/qsRvVem1Rw9qcLbHGKjcH6YX)

**Comment by lehni** [comment]
Since the item is already in the list, this case is not so clear: In order to be inserted into children list at a different index, it has to be removed from it first. When you remove, the indices of all items above it shift down by one. And if the insertion index is above its current index, you'd assume it is in relation to these items that now shift, so one can argue that it makes sense to then also adjust the insertion index. Doy ou see what I mean?

**Comment by georeith** [comment]
I do see what you mean. Although its strange that Projects children and other Items children behave differently in this regard.

It makes more sense to me to guarantee the index provided. It is expected that when you splice into array that other keys change and thats fine, but I would always expect my spliced item to be at the index specified.

**Comment by georeith** [comment]
Actually thinking about this more and how `Array#splice()` operates I think you are right in the current implementation... I think its `Project#addLayer()` that gets it wrong.

I imagine the most common use case is I want this item to be above or below something else... in which case for above you would give the target items index + 1, to be below the target items index, just like array splice.

**Comment by lehni** [comment]
The reason why it's behaving differently right now is this line of code: 
https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L2346
And the calculation of `shift` here:
https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L2343

I can't decide which approach is better... Both argumentations are valid, but I think I agree with you that the shift is more elegant, so I shall port this to `insertLayer()`. 

You should then be able to use `insertAbove()` / `insertBelow()` for layers correctly also. This is currently probably not the case, due to the lack of this code in `insertLayer()`.

**Comment by lehni** [comment]
[Here an example with layers](http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUchIrU4sMFWwV8lLLFXxAHI1qBZB6KwX1/LxUdYVaTeuYPLhKI+wqS8rz0VUa41CZUZQKMzU5P684PydVLyc/XaOgKD8rNblED6y3GCQLcZlebn5ZqmMSkNCAOICwRqAHk4pSE7ML8jPzSoqVrKJjawE=) that currently fails.

**Comment by georeith** [comment]
@lehni 

Hmmm so thinking about this some more. I'm not so sure. The issue I see is that the inverse of `insertChildren` isn't the items old index.

As in if I have 4 items.

The 4th has an index of 3:
- I tell the 4th to insert at index 1.
- I tell the 4th to insert at index 3 (effectively the inverse).
- The 4th index is 2.

That does seem strange and hard to reason about. There is also the case that I tell it to move to one above its current index and it always stays in place:

I have 4 items:
- The 2nd has an index of 1.
- I tell the 2nd to insert at index 2.
- The 2nd index is 1.

Perhaps `insertLayer()` had it right and it should behave like that, `insertAbove()` and `insertBelow()` are what you should use if you care about putting a layer above or below another but not the actual index.

**Comment by lehni** [comment]
Yes I agree, I think you're right about this... I was just looking into how jQuery and the DOM handles this case, but the functionality is not even provided, so I think we can make up our own rules here.
