### ISSUE TITLE
PaperScript throws error when using [object]==null

### ISSUE THREAD

**Issue by ktsuttlemyre** [paperjs/paper.js#1043]
I am using this library for large integers https://github.com/peterolson/BigInteger.js
PaperScript will throw an error when I write

```javascript
var n=bigInt('1000')
if(n==null){ //this line throws an error
   alert('this alert will never show')
}
```

However if I switch the condition to say
```javascript 
var n=bigInt('1000')
if(null==n){ //this line does not error
   alert('this alert will never show')
}
```

The error
BigInteger.js:688 Uncaught TypeError: Cannot read property 'value' of nullSmallInteger.compare 
BigInteger.js:688BigInteger.equals
BigInteger.js:700t 
paper-full.min.js:38setCanonicalPath
VM1729:306update
VM1729:251(anonymous function) 
truncated for convince .......

It seems, PaperScript assumes an object in the first position with an equals function will be able to handle any input given to the equals function.
Ex `if(__$__(n, "==" , null)) {`
This may be a huge assumption on the PaperScript interpreter as JavaScript can handle this expression correctly.

**Comment by lehni** [comment]
[Here the sketch](http://sketch.paperjs.org/#S/VY+xDoMwEEN/5ZQFkKqGrlQs3Tp3LB0CXElKuKDLAQPi30vZutnPliWvisyAqlCPHqWx6qSa0P68o8ZPLaaJFRljoTWbpXNybsKgRxTk4GMgfXPdnQQ75PMn6sHEPfmHSXataDYMVNYHT5NLnucHdm9ICcoSaPI+gxW0FusieEcIYjksEQwBMgeuCACMR94HjtKhYXHeA+GMDNGGJckq2iraf9SMph+DI4mqeL62Lw==) for this issue.

**Comment by lehni** [comment]
The problem is that the `bigInt` class defines an `equals()` method that is unable to handle `null`, and PaperScript currently translates `==` to such `left.equals(right)` calls.

We've already moved to special signatures for all math calls (`__add()`& co.), so we just have to do the same for equals, to mark these special equals methods that are able to behave like `==` does.
