### ISSUE TITLE
No room for floating point error in Path.closePath (when merging last point).

### ISSUE THREAD

**Issue by willstott101** [paperjs/paper.js#1045]
I have an SVG path from Inkscape which creates a closed loop (at least it does in inkscape). When loading this path the last points don't get merged together (I end up with 1 too many points). This is a no-go for me because I'm implementing blend-shape style animation, so the paths must have an equal number of points.

**Here is a JS fiddle which demonstrates my problem and monkey-patch fix using** `paper.Numerical.GEOMETRIC_EPSILON`: https://jsfiddle.net/willstott101/fouvx8y4/3/

A more sensible fix would use `GEOMETRIC_EPSILON` and `Point.isClose()` instead of `Point.equals()` all throughout `Path.join()`.

While this is arguably an Inkscape problem with precision. It seems to me this is exactly what `paper.Numerical.GEOMETRIC_EPSILON` and `isClose` should be used for.

**Comment by iconexperience** [comment]
I had the same experience before. This problem is a combination of lack of precision in the SVG file and the IMHO weird decision to use relative coordinates for path descriptions in SVG (they probably wanted to reduce the file size by getting smaller corrdinate values).

Another approach could be to make Inkscape use higher precision for SVG export, but I am not sure if there is a setting for this.

Anyway, I think you are correct that `GEOMETRIC_EPSILON` should be used for closing the path. But with the relative coordinates used by SVG I am not sure if the problem could happen again if lower precision is used in the path data.

**Comment by iconexperience** [comment]
I just noticed that you can even use absolute coordinates for path data, which may solve your problem. Alternatively you can try a higher precision:

![image](https://cloud.githubusercontent.com/assets/2122773/15673309/27d01328-2736-11e6-85e6-d3ac37c68185.png)

**Comment by willstott101** [comment]
Yes, I've actually lowered my precision in Inkscape previously to 4 or something (was debugging the path and all those decimals were driving me mad). I hadn't noticed the absolute setting though. I'll give that a  go. It's unfortunate that my workflow might be tied into Inkscape configuration, but nevermind I suppose.

I shall play with Inkscape's settings next time I'm working on this project.

Yes I suppose it's fundamentally a downfall of the syntax. Or the format as a whole for not having object-based nodes. Reductions in precision will always cause issues.

In my case it probably is low-quality path data.
```
168.579+ 0 + -22.907 + -40.58 + -17.673 + -40.2009 + -40.2012 + -3e-4 + 22.5292 + 40.2022 + 17.674 + 40.58 + 40.579
168.58100000000002
128.004 + 17.673  +39.897 + 39.897  +0  +-22.226 +-39.899 +-17.673 +-40.5689 +-40.569 +-1e-4 +22.897 +40.571
128.00299999999996
```

So perhaps a patch isn't neccessary. Will experiment more soon.

- Thanks

**Comment by iconexperience** [comment]
I just checked if Paper.js supports absolute coordinates at all. For import absolute coordinates should work, but export is always with relative coordinates.

**Comment by lehni** [comment]
Here the example [as a sketch](http://sketch.paperjs.org/#S/nVTbbtpAEP2VqR8io5qNMVcH8VAhU2jDRcBDqxAh1wzgYq8de0lLI/69s2tza1EadV/snTlzO3PsF427IWp32mSDwltrhuZFC3l/dhOYdp356MO0Cy2YaSGUag1WrdtGyWow06yAB6ZRqrNavQxFy2K2WTfKNmvYdShWTFZtHG8ZyDCV3TJN25B4y6rlhpJlFBXWhmIZixUjjwBCVS2bvDJfrWGDglsHgw0KJ/EUBVlRipFF5YV6VY8S/JppzRmf8ZEr1ixOIhGJXYzMC6IUP0U+pwmXW+4JP+KgF+BlxoGO5GDpJ6kgt1j7KVuh6Mj7BFchcqEXjAwoT+Be4O7dM1jzBMvebm+hv4OIBztI0A0gdol8aP3zyJVAp/flmMVfgp61+I68qoebm6xpNo9pMsHwaesGqS59ualwMSHGqR9EkoLYjTFhg22Iie+5AfvoDPvOdNxrz53RpHc/HORzvKGon7Ylt+dVjUOlU3kawOELCHfgrV2+wvQNFFyeLM+J3qyJFEXX5YsAezzvYJ1fz1ehPAmG0TNerEitkFKoCRa6SLZ4cO+zR4Jim3AFJMdeSUtSGROJHH+AlJl++HpkbEz5AvQELqREKGFuU/pIH8zHK/4ZJ3pGzrgzHPehPxx8dr4C5Wt3s1pKu7IQRVyTtbQ1rys+jzooXv9O6znu5JXp5d4V9sQVtagCpJlIBF+ygpmo5Z+EXUDbassLWEYJhBHf4K6olO/zFcTbJKaKqfoq2B/bOH6oalF/E54p9wrtlNKXM7Kf8L4F9Of672W8QuQ53/QH/UbTb5TkU+3u4XH/Gw==)

**Comment by lehni** [comment]
You see that the logged distance is `2.842170943040401e-14`, so much smaller than `GEOMETRIC_EPSILON` which is `2e-7`. I'm thinking that we should maybe `EPSILON` here instead, which is `1e-12`, because `GEOMETRIC_EPSILON` is used in areas where we're geometrically processing paths, e.g. boolean operations, and dealing with accumulated imprecisions of rather complex math equations. Here we just want to address some imprecision in incoming data.
