### ISSUE TITLE
Possible PathItem.unite() bug!

### ISSUE THREAD

**Issue by zrispo** [paperjs/paper.js#1100]
Take a look at the following page: <a href="http://zrispo.co/booleantests.html">booleantests.html</a>

It gives this error when after trying to `unite()` the two SVGs:
`paper-full.js:9309 Uncaught TypeError: Cannot read property '_intersection' of null`

The two SVGs are proper SVGs - you can see them being rendered correctly at the bottom of the page. After being imported into paper.js, they become a `Path` and a `CompoundPath` that render correctly as well. But when I call `path1.unite(path2);` I get the weird error.

Is this something I'm doing wrong? I'm not too familiar with SVGs.

Thanks for the help!!

**Comment by zrispo** [comment]
Nevermind, found out the issue. My paths weren't closed!

According to lehni in [this issue](https://github.com/paperjs/paper.js/issues/427) `unite()` is for closed paths only. Should that be in the docs somewhere? Or maybe `unite()` could warn you if the paths aren't closed?

**Comment by lehni** [comment]
You're using `v0.9.25`. Try again with `v0.10.2` please.

**Comment by zrispo** [comment]
No worries - figured out the issue, see my comment above

**Comment by lehni** [comment]
[Here the sketch](http://sketch.paperjs.org/#S/bZdLb1xHDoX/SkEbO8BNoVjvijErrwZwgABZjrKQ5U5iuNNtSEqyGMx/z3d4bw/szAA2JN56kYeHh9S/7y4Pv53uvrv78dPp5fHXu+3u8fpB9h8PT+GzhX+EHx5efv3ny+m3+Ph0eng5vX71vZUee57BYp4lvA1WShzYJdZUNisWU1khp2h1YaaYLIWaY0tJu/Piwwq9xlTzZnnE1kcYJabeMbkljzB1WfftKWYOLou1z82sxzFzWFWnMHklzbBarLNpe7LYKx9wkdfZNlr33bNvk5d194o2Bpt5pHGYH4un8WAm/JrRbG6dtYzb43C7cWG3oFBb3cqIq8wworWylRyHNcIfJbOT+GpPoNNT2nKOtVhI3AIWI/Yp3MpaHlpcy0IGxrStWHC7c2HdWiy9B6vH04m3cgCYscqWHFyenCXJsCGPlY634VvsZGERX8mb8M8yVtGVVSCy02p4h+MTIDBTamHGbBY6fjSlc4JVCqRldts4ANq5u4+APUdTZkepCqDGDJDEAQUUXSY6MN7jttZ2Q5hUwsu3tR5X4/VYyT/vAD7Gmgd4C1IZHOL12uNsSaC3OrYmSFeodktJweMWKl60tLWmjIc64xptI10rr9Dy4UBTkCmwKeWm5HZihIKr563jFuQZENJ9gA89OTptDpHGoKulrJSDAe+w2+0h1MXBUcb+ZSWnqB12y4Y9jhPGDTunYRwUIDetsSHPHYMcS6MElFx4MYDCHGbqLZUW8HNVFRix9aKEzc5zzsUuWA5alal9wXB8cjsLqS1SLuyt8rTl3fIUjlhHua0CGwWpjBZd3YnMYCJ7kofaeyzAiP8N4ExFS7YK7JJjY+2lvm6lPvFJWWj77bMRGI4LQbYLWRjHJbn6dgCoVsLk1QUOqmERCthU+SJvq07aLhRRBdiszNRovW45cVGqng+IiA3pFsFApj6an6Cah/FFFda2DIENMGRPAsg5OSx8i9P8BKkZ5AKNiZnqy6p/4MI1dAVzeaqpwHbwHMKtLN6p6jJQjOb1k1CjDIMVqkzzEEThPvkJl6iFtiNHgufgNDRVoUBpftV2GGALIpiLWx4JeJPwLEUmBKY+AD038SYPrq2ud91UaSR5VNHMgD+zb0JLSJhdPfKkHIjNwHHoesmleETsFSLllbymLBFUdXTQ1YxqCWGlSPZyfEEBRSgmMV++Pvj+jkre24C+eKQ3O+0IfrGDOvMd5KgAoexDS5bqc3rea95f1e2y5yLOSUGsKtGvKx2BJUp1HnHM7PXI1zIFG0+TYqg9pzlsqB0ot6G6IQvDO1Lx2DwpkgmIodCVlLTLOP4JZZQmofgZ6gtlKqol10zzZqmUV3FuwAy0UBJHTUg8jdtr4+dS7aJpB6EWsoaeQhkIhxdIPJSYDQKX7ELSkwu5+IqzzaWkCgqe7Z2SgPhjARWJyZ5CXjUPlmROhxs/89hklzQc7l55ge+1ZxH+YDgqhkxInWqlKgGzQHgoW1Sk4iCckbujHopBldBUBuHR3Li9hvRfLZrJdsu1iP6S7baKrjWQoXWOsX01c7z65s39xQeU/H8HFKL3Xg1G9WjzgECaaSnyO6nfNChORajrgtkSGGOnK9spRtK+kssmSqGkVVNY3SUZGUgcofUwdpA1CsIkc8NwFTVcPtD0piIXMlUqViCfS1vwFrHGJgHLHnc6On0d5AIKFWUXGrJKefugxOICALFz7zv7GGPQ2ro30ppJNdVRCq1T4wgvreESRwfEV00VajqLyQht6M1FdCEeYoiXnYaHYcfgNdc6biAsmMr/oIynuedySV5RoTn3XBfXI7UN+a/cqwKtSacQfI1WYK8JUMKsE0hTLy4puQzfMZiduIje4hd05JEaOhiingcmBJcabKN5LQ1US9BswrFKKjQb2q0TZq4no02jaHO+abiwumlsbSZerGPSxF0NriQK570XdJFRPdzLwolr7kgSLZdT1TYwG1lb6VHbV+T73tAB6jyoJ+1Z49XMSRhQEs8IGyqxaGbYG7DKr6VbCxWWTE78MEhpSL+gABiP6DCpzrTffnxg9lIv5D4NZSIRFO3Np2103ZM4julFvZ7pBIJCYo+0zurNOJMD1HE025d9eGkq6H0/jmkoK1kmPKJnaRirnPbeLtr5cIxDkwBnFUtzE2nJcJa8kAKJoRrwDizs3f2dtW7U59ijMUiqsij7OOTg4KmmE3Vz01wU+5o7Fkk3V0a8eRsW1chpWl29rW8wQdoChRNlqNERPvKHy6Sg3qmdL01Bw+fLIWmuwf/wkMYyxZTqNoFvxLWqXERQ+7b2uUq1OvxPI80kS+OVZ5ddjaNsYjj4mhquafeXx+vl+Xo+xfP1l9efLT6er8+nD1r6aiF/sXB/Yd/zy9P10+nt9Xx9QhFfPZ0+vHrzxcKPjw/nj5dfWPr54fx80lL+25n7u/fn30/3d1+u/e+xXXafTs98Y9vvl48I7meTH3yMP388n28XXk5/Bv/9tW2Bf2mTlH/zhj8x3yPUnz5fP15enu+++9dP//kL) for `v0.10.2`

 It works. But there is still a problem: If I reverse the sequence of the operands, then it fails:

[Sketch with reversed operands](http://sketch.paperjs.org/#S/bZdLb1xHDoX/SkEbO8BNoVjvijErrwZwgABZjrKQ5U5iuNNtSEqyGMx/z3d4bw/szAA2JN56kYeHh9S/7y4Pv53uvrv78dPp5fHXu+3u8fpB9h8PT+GzhX+EHx5efv3ny+m3+Ph0eng5vX71vZUee57BYp4lvA1WShzYJdZUNisWU1khp2h1YaaYLIWaY0tJu/Piwwq9xlTzZnnE1kcYJabeMbkljzB1WfftKWYOLou1z82sxzFzWFWnMHklzbBarLNpe7LYKx9wkdfZNlr33bNvk5d194o2Bpt5pHGYH4un8WAm/JrRbG6dtYzb43C7cWG3oFBb3cqIq8wworWylRyHNcIfJbOT+GpPoNNT2nKOtVhI3AIWI/Yp3MpaHlpcy0IGxrStWHC7c2HdWiy9B6vH04m3cgCYscqWHFyenCXJsCGPlY634VvsZGERX8mb8M8yVtGVVSCy02p4h+MTIDBTamHGbBY6fjSlc4JVCqRldts4ANq5u4+APUdTZkepCqDGDJDEAQUUXSY6MN7jttZ2Q5hUwsu3tR5X4/VYyT/vAD7Gmgd4C1IZHOL12uNsSaC3OrYmSFeodktJweMWKl60tLWmjIc64xptI10rr9Dy4UBTkCmwKeWm5HZihIKr563jFuQZENJ9gA89OTptDpHGoKulrJSDAe+w2+0h1MXBUcb+ZSWnqB12y4Y9jhPGDTunYRwUIDetsSHPHYMcS6MElFx4MYDCHGbqLZUW8HNVFRix9aKEzc5zzsUuWA5alal9wXB8cjsLqS1SLuyt8rTl3fIUjlhHua0CGwWpjBZd3YnMYCJ7kofaeyzAiP8N4ExFS7YK7JJjY+2lvm6lPvFJWWj77bMRGI4LQbYLWRjHJbn6dgCoVsLk1QUOqmERCthU+SJvq07aLhRRBdiszNRovW45cVGqng+IiA3pFsFApj6an6Cah/FFFda2DIENMGRPAsg5OSx8i9P8BKkZ5AKNiZnqy6p/4MI1dAVzeaqpwHbwHMKtLN6p6jJQjOb1k1CjDIMVqkzzEEThPvkJl6iFtiNHgufgNDRVoUBpftV2GGALIpiLWx4JeJPwLEUmBKY+AD038SYPrq2ud91UaSR5VNHMgD+zb0JLSJhdPfKkHIjNwHHoesmleETsFSLllbymLBFUdXTQ1YxqCWGlSPZyfEEBRSgmMV++Pvj+jkre24C+eKQ3O+0IfrGDOvMd5KgAoexDS5bqc3rea95f1e2y5yLOSUGsKtGvKx2BJUp1HnHM7PXI1zIFG0+TYqg9pzlsqB0ot6G6IQvDO1Lx2DwpkgmIodCVlLTLOP4JZZQmofgZ6gtlKqol10zzZqmUV3FuwAy0UBJHTUg8jdtr4+dS7aJpB6EWsoaeQhkIhxdIPJSYDQKX7ELSkwu5+IqzzaWkCgqe7Z2SgPhjARWJyZ5CXjUPlmROhxs/89hklzQc7l55ge+1ZxH+YDgqhkxInWqlKgGzQHgoW1Sk4iCckbujHopBldBUBuHR3Li9hvRfLZrJdsu1iP6S7baKrjWQoXWOsX01c7z65s39xQeU/H8HFKL3Xg1G9WjzgECaaSnyO6nfNChORajrgtkSGGOnK9spRtK+kssmSqGkVVNY3SUZGUgcofUwdpA1CsIkc8NwFTVcPtD0piIXMlUqViCfS1vwFrHGJgHLHnc6On0d5AIKFWUXGrJKefugxOICALFz7zv7GGPQ2ro30ppJNdVRCq1T4wgvreESRwfEV00VajqLyQht6M1FdCEeYoiXnYaHYcfgNdc6biAsmMr/oIynuedySV5RoTn3XBfXI7UN+a/cqwKtSacQfI1WYK8JUMKsE0hTLy4puQzfMZiduIje4hd05JEaOhiingcmBJcabKN5LQ1US9BswrFKKjQb2q0TZq4no02jaHO+abiwumlsbSZerGPSxF0NriQK570XdJFRPdzLwolr7kgSLZdT1TYwG1lb6VHbV+T73tAB6jyoJ+1Z49XMSRhQEs8IGyqxaGbYG7DKr6VbCxWWTE78MEhpSL+gABiP6DCpzrTffnxg9lIv5D4NZSIRFO3Np2103ZM4julFvZ7pBIJCYo+0zurNOJMD1HE025d9eGkq6H0/jmkoK1kmPKJnaRirnPbeLtr5cIxDkwBnFUtzE2nJcJa8kAKJoRrwDizs3f2dtW7U59ijMUiqsij7OOTg4KmmE3Vz01wU+5o7Fkk3V0a8eRsW1chpWl29rW8wQdoChRNlqNERPvKHy6Sg3qmdL01Bw+fLIWmuwf/wkMYyxZTqNoFvxLWqXERQ+7b2uUq1OvxPI80kS+OVZ5ddjaNsYjj4mhquafeXx+vl+Xo+xfP1l9efLT6er8+nD1r6aiF/sXB/Yd/zy9P10+nt9Xx9QhFfPZ0+vHrzxcKPjw/nj5dfWPr54fx80lL+25n7u/fn30/3d1+u/e+xXXafTs984/bfLx8R3M9ZfvAx/vzxfL5deDn9Gfz317YF/qVNUv7NG/7EfI9Qf/p8/Xh5eb777l8//ecv)

The reasons is indeed because they are not closed.

**Comment by zrispo** [comment]
Thanks for the help!!

**Comment by lehni** [comment]
So this is essential the same bug as #1089

I'd really recommend upgrading to the latest version though, a lot has changed for boolean operations.
