### ISSUE TITLE
Replacing an item with itself removes the item

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1118]
When calling `item.replaceWith(item)`, the item gets removed from the tree structure. I would expect this to just do nothing at all.

Example code:
```
var p = new Path.Circle({center: [100, 100], radius: 50, strokeColor: "blue"});

p.replaceWith(p);

console.log(p.getParent()); // null
```

<a href="http://sketch.paperjs.org/#S/JU7LCoMwEPyVZU8KEtpDLyk9+QNCDz0YDzEuGkyzIYntQfz3psjAwDxgZkev34QSnytls2CDhqe//ugIAR7g6QudzotobTSOqt2QzxQl9NfLpYFCQwNRT3ZLEm7FSTnySi07LiWFo9tI4VHflVc+iEjBaUMvm5cqnKZhn9iRcDxXQcyUOx3LRlWf8YlybIyk18DW54SyH44f">The Sketch</a>

Maybe `replaceWith()` should be implemented like this:

```
    replaceWith: function(item) {
		var ok = item && item != this && item.insertBelow(this);
		if (ok)
			this.remove();
		return ok;
	},
```

**Comment by lehni** [comment]
Interesting. We may want to fix this further down the chain, will look into it right now.

**Comment by lehni** [comment]
`insertBelow()` / `insertAbove()` is expected to only return the item if it was able to insert it. Now the question is, what should it return in case of `item.insertBelow(item)`. Currently it returns `item` although nothing changed... If we decide that it should return `null` in this special case, then `replaceWith()` doesn't need changing, otherwise it does. What do you think?

**Comment by iconexperience** [comment]
I was thinking the same, but then saw that `insertBelow()` and `insertAbove()` call `_insertAt()` and then I gave up :)  i think `insertBelow()` and `insertAbove()` should return null, because the item will not be inserted below/above itself in this case.

**Comment by lehni** [comment]
Yeah I agree :)
