### ISSUE TITLE
Decide if boolean operations should create clones or modify / replace the left operand path.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1120]
Since people often chain these and are confused by the resulting left-overs, and since most other path function are destructive (`smooth(), reverse(), flatten(), simplify(), transform(), scale(), ...`), wouldn't it make more sense that the boolean operations are also destructive, and return the modified `this` if possible, otherwise the new item that replaces `this`?

**Comment by lehni** [comment]
@iconexperience, I'm curious to hear your opinion on this.

**Comment by iconexperience** [comment]
It may be confusing to have a destructive function, because with boolean operations usually two items are involved. Why should one be destroyed and the other one not? Or do you intend to remove the second item, too? My guts tell me that the current way is correct.

I have done some experiments previously to skip the cloning in `preparePath()` to improve performance. What I did was to flag the items (adding a `_disposable` property). If the flag was set, the item was not cloned. But as mentioned above, my goal was to improve performance, not to achieve a better or cleaner implementation for the boolean operations.

**Comment by lehni** [comment]
@iconexperience I agree. But should the clone by default not be inserted into the scene graph perhaps?

**Comment by doom-fr** [comment]
As reply here : https://groups.google.com/forum/#!topic/paperjs/n-Bb2njEGGo
It's a bit disconcerting to return a new path all the more if we do looped unite.
(you have to remove the unintended paths).

If someone wan't to have a new item just clone it before
`newItem=item.clone().unite(path2);`

or create this kind of notation
`newItem=Path.unite(path1,path2);`

So for me it has to not create a new item by default.

Doom

**Comment by lehni** [comment]
It's been out in the current form for too long to change it now. Let's just close this.

**Comment by doom-fr** [comment]
Maybe you can just add an option `createNew` set to `true` by default
so it won't change actual use but will allow the other solution.

Personally, I would have set this option by default to true as `path1.unite(path2)` is an operation on `path1`, and so expected behavior is not to have a new item (`Path.unite(path1,path2)` or something like that is the notation to expect a new item).
