### ISSUE TITLE
Uniting empty path with simple path results in null

### ISSUE THREAD

**Issue by MartinBolot** [paperjs/paper.js#1121]
Hi, I'm Martin, an intern working on Prototypo.

I've noticed that doing `emptyPath.unite(simplePath)` returned null, while doing `simplePath.unite(emptyPath)` returned a new path containing the segments of `simplePath` (`emptyPath` being simply created using `new paper.Path()`).

I was expecting both operations to have the same result.

**Comment by iconexperience** [comment]
I think this has been fixed, too. Maybe you can try again with the latest build from https://github.com/paperjs/paper.js/tree/prebuilt/module/dist

**Comment by lehni** [comment]
If the first paths has 0 segments (`path.isEmpty() == true`) and isn't closed (`path.closed == false`), then the boolean operations currently perform operations on an open path, as defined here https://github.com/paperjs/paper.js/issues/757#issuecomment-150849565. `unite()` is not defined for open paths and currently returns `null`. If both paths are closed, this already works:

[Sketch](http://sketch.paperjs.org/#S/XZDBisMgEIZfZfBilg0hEXpx6WlfYGmPSQ42GVpJOgY1LWzpu69mE7D1IPrP/N/8zIORuiKT7Dig7y4sZ53p4/+mLEzKXyrYA+EdfsI7ezQE4XSjcdhL8HbGhp4fXw01tBlEYigO2HlF5xE362Q0eQl1VZY5hKvN/3WnfzHIIsoikb01A36b0VgJ3GLPX+ZZdDHfkrOYSXvMlgixI9aKxB/6+NkiEt+Kk3Haa0PwuYc6zt2VbYoWK1ok6GpFi3f0aZyRb7UXcsCu7LDdk0U1LEtwTNbt8w8=)

Maybe we should hide these open-path boolean operations behind an `options` switch and always assume closed paths by default even if they're not actually closed, as they seems to cause a lot of confusion otherwise... And you may want to be able to perform the "stroke based" boolean operations on closed paths too... What do you think @iconexperience?

**Comment by iconexperience** [comment]
IMHO this is a very good idea. I have seen unintentionally open paths (<a href="https://design.google.com/icons/#ic_directions_walk">"directions walk" of the official Google Material Icons</a> is such a case) where the current behavior would cause a lot of confusion. So yes, let's keep the open path handling as an option.

**Comment by lehni** [comment]
Great. Should we call it "boolean operations on open paths", or "on stroke" vs "on fill"? I think the latter is clearer...

**Comment by iconexperience** [comment]
If we use the first term this will limit the functionality to open paths. So yes, the second one is better, I think.
