### ISSUE TITLE
Clip masks no longer support compound paths

### ISSUE THREAD

**Issue by park9140** [paperjs/paper.js#1125]
This sketch shows a clip mask working in v0.10.2.  However, in the latest develop branch this no longer works.

http://sketch.paperjs.org/#S/fVLBboMwDP0Vi0vphgLVLhXVTpW2yyZN3bHlkAUDaUMSJaHtVPXf5wA7bkKK4vg9+/mZW6J5j0mZfJ4wiC7JEmHqGJ+5g8EpeIZFF4It85x7j8Ezyy26o2fGtbnseYs+77mT6luzo20Xm4OOVMd9QEdsjRfYjUFK5ZZzuuf+NCe3prdm0PUHD116O2gA0UlVO9Ql7GMIIyym2Q5F4LpVmO5XRQarospgv6bbuqiW2d9gQozQVTGyfsEVnfcoKcphjVRqa5SJqhcO68VvwhovgzSaXSlzlnhhAjUNxK6EyHPYOuQBgUPrzGDBNBA6hHAxIAP2HriuQShpKSyn8SfgNP9rvKexUTa7FhWNCBZZFmtCBjcgPcePOr7RIqgs2U99YzMhnVBI1ZtBi6gVjH5xtNkUz6R1CbfJnNjcNA0tkmq+R5e81BOGCdpCgByeiiU80LmZKJOmf0yAx7kkEe70A32RHSdrpA4+KffV/Qc=

Getting closer to being able to use the latest develop version for my app.  There are so many safari/firefox bug fixes in v0.10.0 I'd love to be able to pull it in sooner than later, so I don't have to keep writing work arounds.

**Comment by lehni** [comment]
This happens due to #590, commit a0417040f8d2b8518a3c44915ca1aa1c99c8d784 and is now the intended behavior. (the next release will therefore be `v1.0.0`):

Both sub-paths have the same orientation, and compound-paths don't magically reorient the sub-paths anymore, because that caused more troubles than it solved issues.

You have two of options to fix this:

1. Set `subPath.clockwise = false` on the second sub-path:

  ```js
  var mask = new CompoundPath({
    children: [
      new Path.Rectangle({
        point: [10, 10],
        size: [80, 80]
      }),
      new Path.Rectangle({
        point: [0, 0],
        size: [100, 100],
        clockwise: false
      }),
    ],
  });
  ```

2. Call `mask.reorient()` which will handle the sub-path reorientation correctly, emulating the 'evenodd' fill-rule, as long as the paths don't intersect:

  ```js
  var mask = new CompoundPath({
    children: [
      new Path.Rectangle([10, 10], [80, 80]),
      new Path.Rectangle([0, 0], [100, 100]),
    ],
  }).reorient();
  ```

When not using clipping, you could also set `mask.fillRule = 'evenodd'` and have the rendering engine handle this for you. For some reason, the fill-rule is ignored when clipping. I'm not sure if this is a canvas bug in all the browsers I tested.
