### ISSUE TITLE
Non-linear scaling animation

### ISSUE THREAD

**Issue by danielmeng07** [paperjs/paper.js#1137]
I have rectangle I'd like to perform `rect.scale(7)`, but animated. The documentation uses the onFrame function to do this, but it's non-linear. By the time I get to scale 7, it's already larger by several hundreds (perhaps thousands) orders of magnitude. 

```
function onFrame(event) {
  if (si > 7) return
  si = (si * 1.01)
  bob.scale(si, 1, o)
}
```

**Comment by iconexperience** [comment]
The problem is that you are scaling an already scaled item.

So in the first iteration you are scaling the item by 1.01, in the second you are scaling the previously scaled item by 1.01 * 1.01, so the result will be scaled by 1.01 * 1.01 * 1.01 and so on.

So instead of scaling by `si`, scaling by `1.01` each time should do the job.

```
function onFrame(event) {
  if (si > 7) return
  si = (si * 1.01)
  bob.scale(1.01, 1, o)
}
```

P.S.: Please post support questions to the mailing list: http://groups.google.com/group/paperjs
This is a bug database, thus, please help to keep free from support questions. Thanks!

**Comment by lehni** [comment]
Another option is to set `item.applyMatrix = false`. See the mailing list or issues database for explanations, e.g. https://groups.google.com/forum/#!searchin/paperjs/applymatrix%7Csort:relevance/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ
