### ISSUE TITLE
error on Boolean subtract operation

### ISSUE THREAD

**Issue by reubenr** [paperjs/paper.js#1149]
I receive an error when I run the following code:
```
var circ = new Path.Circle({
        center: [0, 0],
        radius: 7500,
        strokeColor: 'black'
    });
		
    var rect = new Path.Rectangle({
        point: [-500, -12500],// minus one to avoid intersection
        size: [1000, 12500],
        strokeColor: 'black'
    });
    
    var myPath = rect.subtract(circ);
```

The stack trace:
```
Uncaught TypeError: Cannot read property 'y' of null
propagateWinding @ paper-full-0.10.2.js:9793
computeBoolean @ paper-full-0.10.2.js:9548
subtract @ paper-full-0.10.2.js:9943drawLens 
```

**Comment by iconexperience** [comment]
Here is some more information that should be helpful for further investigation:

- `Curve.evaluate()` gets called with an out-of-range `t` parameter with value `1.0000000000000002`, therefore it returns `null`
- The out-of-range value for `t` is calculated in `Curve.getTimeAt()` with the parameters `v=[-7500, 0, -7500, 4142.135623730952, -4142.135623730952, 7500, 0, 7500]`, `offset=11782.625235553916`, and `start=0`.

**Comment by iconexperience** [comment]
<a href="https://github.com/paperjs/paper.js/blob/aee9a3190dc17f96c1f7130062a7a28605732448/src/path/Curve.js#L1363">`Curve.getLengthIntegrand()`</a> returns this anonymous function:

```javascript
return function(t) {
    var dx = (ax * t + bx) * t + cx,
          dy = (ay * t + by) * t + cy;
    return Math.sqrt(dx * dx + dy * dy);
};
```

If we replace the calculation of `dx` and `dy` as below, the problem does not occur anymore:
```javascript
return function(t) {
    var dx = ax * t * t + bx * t + cx,
          dy = ay * t * t + by * t + cy;
    return Math.sqrt(dx * dx + dy * dy);
};
```

I am not sure if this change really improves precision, or if the issue is solved by coincidince.

Maybe @sapics can halp help here. Do you think the change generally yields in better precision, or is there a negative effects in other cases?

**Comment by sapics** [comment]
Hello, @iconexperience!
In my 2 cents, I guess that both of calculation has almost same precision order.
But, I need expert help :)

If `ax*t ~= -b`, there exists large loss of precision in `(ax * t + bx)`.
In this case, `ax*t*t + b*t` is also large loss of precision, becase of `ax*t*t ~= -b*t`.

For example, the case [`9.0e-17` is expected],
```javascript
((0.8+1e-15) * 0.3 - 0.24) * 0.3      -> 9.159339953157541e-17
 (0.8+1e-15) * 0.3 * 0.3 - 0.24 * 0.3 -> 9.71445146547012e-17
```
both of calculation causes large loss of precision, and in this case, upper calculation is smaller difference from the expected result.

**Comment by iconexperience** [comment]
@sapics Thanks for looking into this.

In this case the values are
```
ax = -7720.779386421433
bx = 20147.18625761429
cx = 0
ay = -7720.779386421433
by = -4705.627484771423
cy = 12426.406871192856
```

Looking at these values I get the feeling that it is just a coincidence that my modification solved the issue. There are probably a lot of other edge cases that will fail with the new code.

Therefore the best way to solve this issue is probably to limit the return value of `getTimeAt()` to the range between `0`and `1`, just like this:

```
    return Math.max(0, Math.min(1, 
        Numerical.findRoot(f, ds, start + guess, a, b, 32, 1e-12)));
```
