### ISSUE TITLE
Modular/plugin usage?

### ISSUE THREAD

**Issue by lyssdod** [paperjs/paper.js#1153]
Hi all,

Paper.js is truly awesome library, but it weights > 200KBs even in minified flavor...Is there a change to build a only needed subset of it or include it as a plugin? For example, I need only path simplification (actually whole `src/path` folder), is it possible to use only this code without bundling the whole library?

Thanks

**Comment by sapics** [comment]
Hi, @lyssdod!
I know how you feel :)

It might be small minification, building with changing 
```diff
- core: { paperScript: false }
+ core: { paperScript: false, svg: false, booleanOperations: false }
```
in `gulp/tasks/build.js` makes minifier.

If you would like to minify more, you can remove each file by deleting `include(...)` in `src/paper.js`, but it sometimes causes error.
It depends on your situation, thus, it is necessary to do by trial and error.

It's impossible to loading only `src/path` folder without some modifications.
For example, [PathItem.js](https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.js) is defined as
`var PathItem = Item.extend(...)`, it would cause error as `Item is undefined`, because `Item` is defined in `src/item/Item.js`.

**Comment by lyssdod** [comment]
Hi @sapics,

Thanks for your suggestion! Will try to use custom minified build.
