### ISSUE TITLE
Possibility to install paper without jsdom

### ISSUE THREAD

**Issue by janslifka** [paperjs/paper.js#1171]
We use paper.js in browser environment (electron app) so we don't need jsdom, but we install our dependencies using npm. Would it be possible to have `jsdom` in optional dependencies (same as `canvas`) so you don't have to install it for browser usage?

**Comment by lehni** [comment]
Yes, I guess we could / should? With bower on its way out, using NPM in such hybrid ways is clearly the way forward...

**Comment by lehni** [comment]
I can see some issues with this route though: There are scenarios where people will want to use Paper in Node.js, e.g. for SVG generation, but don't need the node-canvas module. This would cause them to either install all optional dependencies because they need JSDOM, or none of them...

As far as I know, there is no way for more fine grained control of this. It would be nice if NPM knew something like a target setting, which allow the definition of different types of dependencies based on the target...

**Comment by lehni** [comment]
Here is an idea for how to manage the different dependency requirements based on different environments:

https://github.com/paperjs/paper.js/issues/1252#issuecomment-278321003

**Comment by lehni** [comment]
I have done this now. This solution will soon be superseded by a better one, as described in #1252

**Comment by lehni** [comment]
More about the improved plan here: https://github.com/paperjs/paper.js/issues/1252#issuecomment-287737419
