### ISSUE TITLE
Support ES 2015 in Paperscript

### ISSUE THREAD

**Issue by zekenie** [paperjs/paper.js#1183]
Paper.js currently uses Acorn 0.5.0, which only parses ES5. ES 2015 support would be awesome! I'm sending a pull request to update.

**Comment by zekenie** [comment]
Update! Made a fork and updated Acorn. It largely worked but we ran into some unexpected issues that I _think_ might be from acorn. Made an [issue](https://github.com/ternjs/acorn/issues/479) with them.

**Comment by lehni** [comment]
Interesting. I am weary of including a newer Acorn at the moment as it has increased in size a lot... But I guess there's no avoiding that in the longer term? Another option could also be to prioritize an already loaded version of Acorn over the one that's internally bundled?

**Comment by zekenie** [comment]
That's an interesting idea. If you could pass a parser into paper that might solve the problem. Is Esprima smaller than acorn? I imagine both grew because of ES2015.

**Comment by lehni** [comment]
We started with Esprima, but Acorn.js used to be much smaller than Esprima. Not sure where they stand now. Will investigate! This passing in of a newer Acorn should be fairly simple to achieve... I will look into it.

**Comment by lehni** [comment]
Linking to PR #1185 that I didn't see until now.

**Comment by lehni** [comment]
So I am working on this now, and it is fairly easy to implement. The only issue I am seeing is that for versions of Acorn.js v0.10.0 and above, we need to pass the preserveParens option to it in order to have the same results as with v0.5.0 (see #1275).

That's a non-standard option, and Esprima doesn't offer it, so I think we're now locked to Acorn.js, which is fine with me.

**Comment by lehni** [comment]
So since 5dafc67278db68e4154a7895bf4c26c944a1ed7b, you can now work with external versions of Acorn.js. In NodeJS, it needs to simply be present in node_modules and will be used. In browsers, you can either have it present in the global scope as `acorn` object, or load it through any mechanism that works with calls to `require('acorn')`, just like on NodeJS. This should suffice?

**Comment by zekenie** [comment]
This seems massively useful! What would it take to get the sketch editor to use a different parser?

Thanks,
-Zeke

**Comment by lehni** [comment]
At the moment, that's not possible. But with a very simple change, all it would take is to request the file at the beginning of your script:

```js
include('https://cdnjs.cloudflare.com/ajax/libs/acorn/4.0.11/acorn.js');
```

I will think about this.

**Comment by lehni** [comment]
As of 0ec06e7353f6119401aed87d9a3678756ce8dea0, this now works:

<img width="639" alt="screen shot 2017-03-11 at 20 55 28" src="https://cloud.githubusercontent.com/assets/213275/23826484/1aec4b12-069d-11e7-8232-9c9dd5a0be5c.png">

**Comment by zekenie** [comment]
That's very helpful, thank you!

**Comment by lehni** [comment]
`v0.11.0` has just been released, and [sketch.paperjs.org](http://sketch.paperjs.org) update accordingly. 

[This now just works](http://sketch.paperjs.org/#S/VY67DsIwDEV/JWRpKqF8QFcWFqYODIQhBCut6tqoDkJV1X+nD4rUu/hx5eM7aPIt6EKXDaRQ6aMO/JzngF5EXfrTUgdHalKEpFoQ8RFMvi1ndZDeHans7BFZXQHTIVvd0dHaiO9LbiFVNcX9cWASRrDI0Uy22N+L/E9YIASfLY/J7R7naEr+6MA3L64piS5u9/EL)

**Comment by zekenie** [comment]
Amazing!!!!

Zeke
