### ISSUE TITLE
Hit-testing SymbolItem should not return SymbolDefinition items as hit-results.

### ISSUE THREAD

**Issue by teeg82** [paperjs/paper.js#1199]
Retrieving an object using `project#hitTestAll` that happens to be a symbol item seems to lose certain meta information. Specifically, I set the `name` and `data` properties; I can verify that the properties are indeed set when the object is created. But when retrieving the object via a hit test, those properties are null. In fact, the object resembles the original definition from which the item was created, as the position value is the default I set originally (0,0). It seems like the hit test is giving me the original definition rather than the symbol item instance.

Code to reproduce the problem (also available in a [jsFiddle here](https://jsfiddle.net/teeg82/9wpexruw/1/)).
```
var canvas = paper.createCanvas(100, 100);
document.getElementById("canvasDiv").appendChild(canvas);
paper.setup(canvas);

var circle = paper.Path.Circle([0,0], 10);
circle.fillColor = 'red';

var definition = new paper.SymbolDefinition(circle);

var tool = new paper.Tool();
tool.onMouseUp = function(event){
  var hitResult = paper.project.hitTestAll(event.point);
  if(hitResult.length > 0){
    var result = hitResult[0];
    var item = result.item;
    console.log("Item name should be 'Bob', but is actually " + item.name);
  }
};

var actualCircle = new paper.SymbolItem(definition);
actualCircle.position = [20,30];
actualCircle.name = 'Bob';
console.log("Symbol Item was created with the name " + actualCircle.name);
```

In the dev console, you can indeed see that the name is 'Bob' upon creation, and 'null' upon retrieval.

I posted this on [StackOverflow](http://stackoverflow.com/q/40559302/877472) as well, but no luck so far.

Is this is an actual bug, or something I'm doing wrong on my end?

**Comment by lehni** [comment]
Here a version as a [Sketch](http://sketch.paperjs.org/#S/VVE9T8MwEP0rVpYkUmQF2BqBhMrCgIQoTEmH4F4aU/eust0iVPW/c7abFsZ378Pnd8cM+y1ks2yxAa/GrMoUrQI+9FYobZUBcS9eez/KeURFW1f1shI3ddl0mBRy0MbMyZBlbW5hlV+pEB+mCQaiw5C9gkGj9pqQWYRvsfjZfpJ5uoyL5CijwxMZSfhCewcfO3YMe1RRBQdAXx47FCLEjtq/gdsbz5qdpS9QXvLsHZx/NCap5Y40e5rg0UNxsUgDuPajeBB1CkyRdsq7CNt62Vx57WHLbJLJgM6kInTEFRhaFzmb8ypq08OnDk9TFy5+/V8Pzywsrh0FT1Lx8m6qrb2tq7u4y5mbyk4wXuHvDspC7/k61fnFsuF7f/JwExtx2axdnn4B)

As you can see, instead of the `SymbolItem`, the actual `Path` that's contained in the `SymbolDefinition` is returned. This is a bug for sure.

**Comment by lehni** [comment]
If you use `hitTest()` instead of `hitTestAll()`, it returns the expected result. Strange!

**Comment by teeg82** [comment]
Wonderful, thanks for handling this!
