### ISSUE TITLE
set bounds in events not working

### ISSUE THREAD

**Issue by lichenhao** [paperjs/paper.js#1212]
When set bounds directly, it works well, but when I put it in the events, it doesn't work well.
What's the problem? 
```
var path = new Path.Rectangle({
    rectangle: {
        topLeft: [20, 20],
        bottomRight: [80, 80]
    },
    strokeColor: 'black'
});
var bounds = new Rectangle({
	topLeft: [0,0],
	bottomRight:[100, 100]
})
path.setBounds(bounds)
var site
view.on({
	mousedown: function (e) {
		site = [e.point.x, e.point.y]
		
		path = new Path.Rectangle({
			rectangle: {
				topLeft: site,
				bottomRight: site,
			},
			strokeColor: 'red'
		})
		path.parent.activate()
		console.log(e, path)
	},
	mousedrag: function (e) {
		if (!site || !path) {return}
		var bounds = new Rectangle({
			topLeft: site,
			bottomRight: [e.point.x, e.point.y]
		})
		path.setBounds(bounds)
		console.log(e, path, bounds)
	},
	mouseup: function () {
		site = null
	}
})
```

**Comment by lehni** [comment]
The problem is that when you create a path item with no dimensions, there is no way that changing bounds afterwards can expand those dimensions for you: 

	path = new Path.Rectangle({
		rectangle: {
			topLeft: site,
			bottomRight: site,
		});

This creates a path item with 4 segments all in the same place, at `site`. When you then change the bounds after, this is just a path with 4 segments, without any information that they need to be aligned as a rectangle.

The solution could be to use a Shape item instead of a Path, and the modify its dimensions through `shape.size` instead of `shape.bounds`:

var rect = new Shape.Rectangle({
        point: [100, 100],
        size: [0, 0],
        strokeColor: 'red'
    });
    
    console.log(rect.bounds);
    rect.size = [100, 100];
    console.log(rect.bounds);

Changing the bounds translates into a transformation matrix that's applied to the content of the item. If the item has bounds with no dimensions before the change, no meaningful matrix can be computed for the transformation.
