### ISSUE TITLE
hitTest over the shape filled with a transparent color doesn't return this object

### ISSUE THREAD

**Issue by orangecoloured** [paperjs/paper.js#1218]
I have a number of draggable objects, some of them have transparent strokes, others have transparent fills. In the version 0.9.25 the hitTest returns the proper object, in versions 0.10.* it won't return an object that has 0 alpha. If I make the alpha equal to 0.0001 for example, then it works properly.

```javascript
var myCircle = new Path.Circle(new Point(100, 70), 50);
myCircle.fillColor = 'black';
myCircle.fillColor.alpha = 0;

function getHitObject(event) {
    var hitResult = paper.project.hitTest(event.point);
    console.log(hitResult);
}

function onMouseDown(event) {
    getHitObject(event);
};
```

**Comment by prichey** [comment]
Running into this issue as well, and it seems to be due to the fact that items with transparent fills are considered not to have a fill at all. For reference: https://github.com/paperjs/paper.js/blob/develop/src/style/Style.js#L312. (This decision also carries over to stroke and shadow.)

I've achieved a workaround for my own use case by modifying `Style.hasFill()` to simply return `!!color` rather than `!!color && color.alpha > 0`. 

I'm hesitant to submit a PR before opening up a quick discussion about this. Should an item with a transparent fill be considered to be filled? At least one other (https://github.com/paperjs/paper.js/issues/1157) seems to have been confused by this decision so it might be worth revisiting.

**Comment by lehni** [comment]
Let's move the discussion to #1157 and close this issue. No PR required, we just need to decide what to do.
