### ISSUE TITLE
Boolean subtract with closed: false doesn't work as expected

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1221]
[Sketch 1](http://sketch.paperjs.org/#S/bZDBagJBDIZfJcxFS5fF2tuIJ19A7HHXw+xsWocdM5LJtuDiu5vRFiyYQyAfhC/5J0PuiMaajwHFH0xlfOrL/O0YGL3AGgh/YOvkUO90dvQVcT61BFqnFEgsNG+LRQXa9tWd53BGxcuClw9YOA24STGxhRljP2vp8rJqqaWi84F9xEfh5kb+bB5JkJ/o2PVhzLagp6YujvhfxZjVU/6r89gJOy/zu76CCXxMGXsLny5mhN81XalPKQcJieB1DY3e8K43rDSzjtENtzCysc3+cgU=)

Result:

<img width="228" alt="screen shot 2016-12-17 at 10 53 45" src="https://cloud.githubusercontent.com/assets/213275/21288058/1a64cf0e-c447-11e6-856e-af0f7178cf87.png">

Expected:

<img width="247" alt="screen shot 2016-12-17 at 10 53 11" src="https://cloud.githubusercontent.com/assets/213275/21288056/0dbb4184-c447-11e6-9d7e-3ed260da7ec7.png">

**Comment by lehni** [comment]
Here another [Sketch](http://sketch.paperjs.org/#S/XVGxbsMgEP0VxJJExYgD2+BEmTJ1qFS1Y/DgEJRYSSDCtJUa5d97dtqlLNy9d+/xdNxo6C6eLun7yWd3pIy6uB/7zy6Ra5ePQNbkFe/n7C/cJd9lP7f0pVIlk1ptQAPXDABYLXiFhebAlGBQGVeUI1SVXDEFWEkQXE6zUkqH84Y1zJgCLRoUNEVdOwO8ZvXINFgAGBSDRloapxTiJfobxaFoxncrUTTC0oUNf3kl5g3+a8rM37zLXTic/fxmA8FzjX3IS7JFISOmatkDHvpvj6g0mhGodWvDfbGywYZpA3zIKZ78Jp5jQvdZ8vvZ6sHJ/9wheR9mk3ZMlPyA6K/Lxy6nzuX5JHz4I8+vcehzHwN5WpMtxlJCtCv8iB0u+zQFHuhy295/AA==) for discussion.

**Comment by mokafolio** [comment]
I think there should be options to control how the boolean subtract operation affects the resulting path (This might also be relevant for operations other than subtract, not sure right now). For subtracting I can think of two possible results that make sense, lets name them _trace_ and _split_.
In my opinion, these options should be separate from the existing closed option as they are not the same, here is an illustration:

<img width="816" alt="boolean ops" src="https://cloud.githubusercontent.com/assets/10217168/21606970/5e909cde-d1b3-11e6-8f46-1536ea362274.png">

The api could be something like: `path1.subtract(path2, {mode: "trace/split"});`

The naming is just my initial idea and could possibly be better!
Does that make sense at all?

**Comment by mokafolio** [comment]
To give a real world example of why I think this is very useful: If you want to remove overlapping/occluded paths (i.e. for pen plotting), the _split_ version makes a lot of sense to prevent drawing any outline more than once, while the _trace_ version is I guess the expected result in the traditional sense!

**Comment by mokafolio** [comment]
the closed flag does not appear to work in develop branch. i rolled all my current boolean ops stuff back to the bower/stable version as that seems to work alright.

**Comment by lehni** [comment]
For the record, here the other issues that related to the treatment of open paths: #757, #1036, #1089

**Comment by lehni** [comment]
@mokafolio I am still waiting from some test-cases from you here.

**Comment by mokafolio** [comment]
@lehni sorry zoned out on that. I put together a quick thing here to compare the bower paper version vs the current develop:

http://stuff.mokafolio.de/DevelopVsBowerBoolean/BowerSubtract.html
http://stuff.mokafolio.de/DevelopVsBowerBoolean/DevelopSubtract.html

made a repo here too: https://github.com/mokafolio/PaperJSDevelopVSBowerSubtract

The examples take 200 circles and subtract them from back to front. Both appear to perform very similarily:

`Bower for 200 circles:
6598.660000000001ms
6135.215ms
6436.640000000001ms
6612.035000000001ms
6517.075000000001


Develop for 200 circles:
6261.555ms
6305.515ms
6505.865000000001ms
6608.64ms
6590.790000000001ms
`
 so I think the difference in speed that I was seeing in my actual app was due to the open flag that is available in the current bower branch but not working in current develop. My guess is that that flag made it faster, we should re-evaluate it as soon as it works in develop again. That said, I could not get my actual app to work with the develp branch at all (I would love to try again as soon as we have a way to support open paths. I recommend providing an API similar to what I described in the comment with the illustration above).

Hope that makes sense!

**Comment by lehni** [comment]
In the same way, `divide()` should work with a line and a path:

[Sketch 2](http://sketch.paperjs.org/#S/hZFBa8MgGIb/inhpCkHSdeyQ0tOuO5T2GHOw+jWRmO8LKh209L9XN8LWwagH8X15+B7UK0c1Aq/5YYCoe15yTSbns/JsUrFnW4bwyXbpKPago8LOQXGVyNKayGKsWfNSVSVLW1t+98FeINWvf+voaYB3cuRrtvBgFhJvy41EiVnnLMJv3UfKs+nkaZwnrn8mRprLt/80R6f08Cgy9myDJUyy7BQ5GyjydTOkCQM5EI66YkaF7q0zHvAp0FStCNCNgDE8h1ePsMT0A0cPavh62sDrpr3dAQ==)

**Comment by lehni** [comment]
@mokafolio I finally found some time to look into this, and it turns out silly me got `options.closed` confused. It's called `options.stroke` since quite a while! And there was a tiny error that prevented options from being passed on to `computeBoolean()` in `PathItem#subtract(path)`, which I fixed in dd56f866792fc71c50e7b9a93ced0c9ea8b1f005

With that in place, everything already works as it should:

- `options.stroke = false` is the same as `'trace'` in your example
- `options.stroke = true` is the same as `'split'` in your example

I don't like the naming of the current option all that much though. I also don't think `mode` is good, but what about `options.split` instead of `options.stroke`?

Another question that we still have to decide:

Should the results of this split-mode be collected in a `Group` item as right now, or should they end up in a `CompoundPath`?

**Comment by lehni** [comment]
Another possibility is to call the option `options.trace` as a boolean, that defaults to `true` and has to explicitly set to `false` in order to use the split mode. This may be better and more explicit?

Thoughts?

**Comment by lehni** [comment]
I have implemented all my suggestions now in 3c9d2eea1d7de509974e7b995a9a578a646ca6d7, along with unit tests for them.

Let's keep the discussion going regarding terminology and `CompoundPath` VS `Group`.

**Comment by mokafolio** [comment]
@lehni Great! I like both, `options.split` or `options.trace`. I'll give the develop branch another shot for my overlay removal application and see how it goes soon.

Regarding `CompoundPath` and `Group`, I think there is a couple of decent approaches:

1. Either only return a `CompoundPath` when absolutely needed (i.e. due to holes etc.) and use `Group` for everything else. This would give you some indirect information about what the boolean operation did to your input path.

2. Always return `CompoundPath`. This has the advantage that you don't have to do any extra logic for handling `Groups` at all (which makes writing recursive functions which my overlay removal app heavily relies on a lot easier).

Overall I think approach 2 is the better way to go.

**Comment by lehni** [comment]
I like approach 2 better too. I wonder what we should do about `divide()`... at the moment, it returns a Group of both bits, so you know what was divided. If your original path is already a compound-path, and you're flattening the result into a new compound path, then you would loose that information? hmmm...

**Comment by lehni** [comment]
@mokafolio what are your thoughts on `options.stroke`? can't decide what's better / clearer...

**Comment by mokafolio** [comment]
@lehni I think I like `options.trace` better because stroke is somewhat ambiguous with all the other uses of stroke in the realm of vector graphics.

For the `divide` question, I just don't see a whole lot of reasons where that extra information would be relevant? That said, I think maybe by default always return a `CompoundPath` and if you are about that extra information and want a group of the resulting items allow to pass in another option for that.

**Comment by lehni** [comment]
Actually, since `divide()` is defined in this way, you might as well call them separately if you need that information:
```js
       return new Group([
          path1.subtract(path2),
          path1.intersect(path2)
       ]);
```

**Comment by mokafolio** [comment]
Good call.

About backwards compatibility, didn't we already break it multiple times? Boolean operations in the master/bower branch return other things than the current develop branch, so I don't think that should stop us at this point.

**Comment by lehni** [comment]
Good call. It hasn't stopped us before, so why now : )

**Comment by lehni** [comment]
@mokafolio I've implemented this now, and there was a nice simplification in a43db8427a52470f32f626d42bdb596f052f3a73

I think we're done : )

**Comment by lehni** [comment]
@niravdhanorkar with the latest [prebuilt version](http://paperjs.org/download/#development-builds), you can now pass `{ trace; false }` to the `subtract()`, `intersect()` and `divide()` boolean operations to get the desired behavior, e.g.:

```js
var path1 = PathItem.create("M534,273C171.7,111,60.5,117.1,30,158c-40.5,54.3,31.5,210.2,111,222c60.8,9,88-71.9,159-66c81.6,6.8,99.6,118.3,179,128c33.8,4.1,83.1-9.7,150-90")
var path2 = new Path.Rectangle({
    point: [150, 85],
    size: [287, 167]
});

path1.strokeColor = 'red';
path2.strokeColor = 'green';

var res = path1.subtract(path2, { trace: false });

res.position += [0, 300];
```

**Comment by niravdhanorkar** [comment]
@lehni 
item.divide(path,{stroke:true}); works for me. usgin latest prebuilt version.

Thanks

**Comment by lehni** [comment]
@niravdhanorkar please use trace instead of stroke, as stroke is deprecated now.

**Comment by niravdhanorkar** [comment]
Hi @lehni ,
I had used it 
item.divide(path,{stroke:true});
now for some kit (SVG on canvas). it doesn't give right division (compound path).
Please help as early as possible.

e.g.
 var division = item.divide(path,{stroke:true});
console.log(division.children.length);

Sometimes I get 4 children, and sometimes 3 children.
4 is correct but when 3 comes it breaks my output.
