### ISSUE TITLE
integrate paperjs with isomer

### ISSUE THREAD

**Issue by akashjarad** [paperjs/paper.js#1283]
i want to integrate paperjs with isomerjs (https://github.com/jdan/isomer) .
![screenshot from 2017-03-18 12-03-19](https://cloud.githubusercontent.com/assets/5300334/24069656/f81967ba-0bd2-11e7-96c7-a5f5f7d03834.png)

i need to move prism using paperjs ,
how should i proceed with it ?

**Comment by lehni** [comment]
That's not how things work with canvas based libraries. Since everything dran to a canvas just ends up being placed pixels, and there is no underlying "native" DOM, you cannot mix and match as you may be used to from other web technologies. You'd have to find a way to get Isomer draw its items by creating Paper.js items for them, but I don't think that will be an easy undertaking...
