### ISSUE TITLE
canvas cannot be rendered automatically with socket data

### ISSUE THREAD

**Issue by ferhtaydn** [paperjs/paper.js#1318]
Hi,

With `v0.22` I can update the other browser tab content with `view.draw();` while demoing some socket.io communication between separate browsers. (simply, drawing a path with one and see on the other side). 

However, it is not working on `v0.11.2` (latest). I also used mentioned here https://github.com/paperjs/paper.js/issues/675 but not worked. (I tried all browsers)

If I create new path, pointtext etc. they are rendered on the screen when got socket event but data coming from other socket is not rendered.

The example I am working on can be found at here: https://github.com/byrichardpowell/drawing 

Thanks

**Comment by pinstripe-potatohead** [comment]
I have been facing this exact same problem.(Incidentally with the same example https://github.com/byrichardpowell/drawing too). 

The view doesn't refresh with view.draw(); or view.update(); - Path/Point items sent from the server to clients via socket.io are not rendered in the client with latest version (I'm using paper-jsdom-canvas v0.11.3), but the same works with v0.9.22.

**Comment by sasensi** [comment]
The problem your are encountering is not related to `view.draw()` or `view.update()`, it is related to a change to how `Paper.js` objects are serialized when calling `JSON.stringify()` on them.
In version `0.2.2`, calling `JSON.stringify(new Point(5,5))` resulted in the string `{"x":5,"y":5}`. Once deserialized, this object is compatible with `new Point()` constructor.
In more recent versions of `Paper.js`, calling `JSON.stringify(new Point(5,5))` result in the string `["Point",5,5]`. Once deserialized, this object is not compatible with `new Point()` constructor, leading to a point with the string `"Point"` as `x` coordinate.
This is why you don't see the paths drawn in other browsers, because they have invalid coordinates.

In order to make this app work with recent versions of `Paper.js`, you need to manually map points to old serialized object version, before sending them. I forked the project [here](https://github.com/sasensi/drawing) and included the needed changes in this [commit](https://github.com/sasensi/drawing/commit/80bf9cf8900a36ae47a4b31a1bd8bec9b001992d).
Here is the method used to map points:
```javascript
// Convert Point to simple object with x/y coordinates
// to allow backward compatibility with JSON serialization.
function formatPoint(point) {
    return {
        x: point.x,
        y: point.y
    };
}
```

I close this issue since there is nothing to fix in the library.
