### ISSUE TITLE
Where is tool.distanceThreshold

### ISSUE THREAD

**Issue by mmirold** [paperjs/paper.js#1332]
May be a stupid question, but I am missing the tool.distanceThreshold attribute mentioned in the tutorials and the Tool reference (did a "grep -r" on the code base). On the other hand, I am not even seeing a Tool in my scope, so the fault may be completely on my side. I am using the Javascript integration.

**Comment by sapics** [comment]
How about `paper.Tool`?

**Comment by lehni** [comment]
Ouch, that's a left-over in the docs from Scriptographer times... It's called `tool.minDistance` since ages, see http://paperjs.org/tutorials/interaction/creating-mouse-tools/#minimum-distance

And @sapics is right, when working with pure JavaScript, you need to create your own tool object from the `paper.Tool` class, see: http://paperjs.org/tutorials/getting-started/using-javascript-directly/#working-with-tools
