### ISSUE TITLE
How to Extend Subclasses (eg Path.Rectangle)

### ISSUE THREAD

**Issue by jacksonkr** [paperjs/paper.js#1335]
`Path.Rectangle.extend` doesn't work and I'm not sure how to make `Base.extend` work in this scenario. I've messed with `Rectangle.extend` and it's promising but doesn't cut it.

The es6 equivalent of what I'm wanting to accomplish would look something like

```
class RedSquare extends Path.Rectangle {
    constructor(obj) { // obj is the json object with initial settings eg {size:50}
        obj.fillColor = 'red';
        super(obj);
    }
}

new RedSquare({ size:50 });
```

**Comment by jacksonkr** [comment]
In the meantime I'm using a factory.

[sketch](http://sketch.paperjs.org/#S/dVE7T8MwEP4rlpekUmSlSCyumJA6IzoSBte9Jladu+AHCKr8d+ykJSDgBsu++x725zNH1QOXfHeCoDtecU2HfH5Vjvk4gNu9ROVgq3Qg987u2DGiDoawXLFzgyxVhlKaILyxBxU68Qg6KGwtlBdELm8+QN7W1dI5GmvvyZKThYND8W2iow/Ub5OT/MPvWqEzXnyJpAsUexuh+AnShJ4sCEtt2XBPPSQathcLRtjwalJabRbiOG/Ha29eHYTokFFqJkCDU0R+nYx/B1Vm6gy4+R+QhmIgb/L7RA53XdebLJ1kxRLChG0wfc7egToNZDB4Lp+ex08=)

```
var superSquareFactory = function() {
    var o = new Path.Rectangle({
        size:50,
        fillColor:'red',
        customFunc: function() {
            this.fillColor = 'blue'
            console.log("something custom on", this);
        }
    });
    
    return o;
}

var ss1 = superSquareFactory();
var ss2 = superSquareFactory();
ss2.position.y = 100;

ss1.customFunc();


```

**Comment by lehni** [comment]
`Path.Rectangle` and co aren't real constructors / sub-classes, they actually return plain `Path` items. This was probably a bit of a poor design decision, which we went for to reflect how things were done in Scriptographer... These constructors are there as a way to create path items with pre-populated / constructed `segments` arrays. They are actually factories internally, but you use them with `new` in front (but you don't have to with these, since they have an explicit `return` statement...)

As for sub-classing Paper.js classes, that's something that we don't officially support. It is possible, and people  are doing it, but we're not supporting it.
