### ISSUE TITLE
Divide operation is not working with open paths

### ISSUE THREAD

**Issue by ajoshi-cimpress** [paperjs/paper.js#1343]
Divide operation is not working for a dividing path into two pieces by a straight line. Here is the example use case http://sketch.paperjs.org/#S/dZFRS8MwFIX/SshTB92lXdbUTHzSV0HYo/UhSy+2NCYlSSso/neTjjllLg+XE87J+QL3kxr5hnRH9wMG1dGcKtum+ywdsVNAt+/kiOSOGHwnTzJ0WUMfyxp4zjYg5nUp4KbqthzYvMiPhq5uG3N+Cj44O+C91dbFmoY6bBsaI4mgpvBfP2NQVTnbglBFvq5BcM5rEmVZgWDxJL1hII6wU8sF6qClGhbYEedH3YcEie6vH7b93LeYnWpS5U8SgpPGaxkwK4siJ8Vf95I44QJU1nirEbR9zc7xMY4HGeTqWiIZcQkHh3IYbW+Cp7vnl69v. 

Also in many cases the divide operation will return a path even if both the path are way away from each other.

**Comment by kampong91** [comment]
In the case above, you are dividing a closed path with an open path. There is an option for divide which is `stroke: true`.

Refer to the sketch here: [LINK](http://sketch.paperjs.org/#S/dZFBa8QgEIX/injKgivJuklqSk/ttVDYY9ODa4YmxGpQk0KX/e/VhG1atutBZnhv3jfiCWvxAbjChx68bDHB0jSxn4RFZvRgD60YAD0gDZ/oRfg2qfFzVtKCsB3l0zbj9C5v9wVl01x+1XhzX+t1lDpvTQ+PRhkbYmpsoalxsESCHP1/+YzRPCdsT7lMybakvCiKEoUyyyln4cR6xyhfYJeUK9RRCdnPsAXnBtX5CAnqrw2bbuoaSC4xBJ3QklQhb0dAZxQpP8PUW6GdEh6SLE0JSv+q10uMMO+wWqQyDpqgxvj4AKOdUUCVeU9W1xCuJ+HF5pYjCuHHjhZEP5hOe4er17fzNw==)

**Comment by kdta91** [comment]
In the case above, you are dividing a closed path with an open path. There is an option for divide which is stroke: true.

Refer to the sketch here: LINK

**Comment by ajoshi-cimpress** [comment]
Having stroke option does work but then in some cases the division is not proper see the [LINK](http://sketch.paperjs.org/#S/dVPLbtswEPwVgicHkAhy+XaQU3sNUCDHqgdGJmrDqmhItAskyL93V4bj1GkvknZ3dmYWA73yMf3KfM2f9rn2W97wvmyoPqWJlWPN09M2HTJ7YGP+zb6lul11/DGI0CgrvLenFt8KtmCEsqfl++URpHBGhdgoKcDaXglrTFSNZCB89LpplZDeWP1egzC9pLYGazzDD7Cg4zJg7UdUK1HCGYdkLbHLaBsppPRAtfYQPdWg1IIFp4JeGjFqQlgFANSIMhpqoI+FQvlgHa3E4JeG9lIbsuJ80HivAOWUvTZAgJQabdOKUYbh1VEajciAapbdAgVo9EfawTtAuME1qpUJTrNbK3QoyAWvdCR6MM7C5Tp2c+1Lx+/uu/GamZjrVPb5SxnKhPl1fMqbjiOEou2P9V/BYnK2gSUGyiMKxyiWKIDegLmfVS7rnzSeh9TvF5WzznwYdpXYcfrB2mZ32m3y6kLTsFd2ZlqzOh0ze2Ok8r4s6pTGeUg1r5SUDZN/Tz+bOObFwxXSD2XOG5wSPR1QxrkMWQzl5+qKOuDja6rp7n8IGuA/8jzltD+U3Vhnvv7+4+0P). In this case the sketch shows some weird shape but actually it is a rectangle with a circle inside it. When I try to divide it with line the division should give me two half rectangles with a cut of half circle but actually it is connecting the half circles with the cutshape.

**Comment by sasensi** [comment]
@ajoshi-cimpress, about your last example, you were not supposed to get only 2 parts because your cut line is crossing here too:

![screenshot-sketch paperjs org-2018 11 09-15-15-33](https://user-images.githubusercontent.com/11247504/48267340-63489900-e432-11e8-944e-f4f4889c63a5.png)

and the connection you are talking about is due to your call to:
```javascript
splitPath.closed = true;
```
which is closing each generated paths.

Here is a modified [sketch](http://sketch.paperjs.org/#V/0.11.8/S/bVRNb9swDP0rhE8O4Kj6tK0O3WHDsMsKDNhhh2UHx1YaL45lyIqLtuh/H6XEaZY1F4nUI98jX5KXpK/2JrlNfuyMr7dJltS2CfFUObAHb9yPbTUYuIPePML3ym/TVXJfkjJjihSFmpZ4Mr7lkjA1xfvzPackl6zUGaOEK1UzoqTULKPASaELkS0ZoYVU4hxzImsa0oIrWQBeuOJCxwdYXqKWFClymWOzZehOtcooobTgIRYF10WIOWMRy3NWipjQWgSEYpzzkNBUy5BAHbEFK0qVhxJdFjEhCipkkJIXpcB5CWc5U28JTjilAmWHEskk4NSaSoHIEtkUXAMJF6gvcJdFzhEusSzETJa5gGspYVBOI54JHdpzmSs+TwdX0z6vksWHlVv1b66R0Tu7M59tZx06uEqcaVZJBAV764N/z1x0T2U8WhE80SSHYI0mPJwcvZ+Z5gb/8ay7qt6dmGa2cehaHzgQcSGxaae2MencKoMXOHa7Be8OBl6PVOdq4l3Vj13lTSpoBvT6eTSdqb1pkCXUX7/+I7Q/dN1Z480N1M5gX6jgwdnDAI8tiq3tfrCH/gGGIL3etl3jTA/eQjUM3ROCm3azMZjzpy5HDiwMJLYHU9VbPM157R0GyP6mKmbSxdmYI/3Rla/hnkYEmdlP2485Z/Z2motj4WnIn20Td80vXt7dXWAcnJkuF3KEz3xkY90XnCJNW2/2GbQLuPsILwEI+AnJq83GkyBbY/cnbScj5yXVVWfATMY9+W2L6x0tPOLSqh5GY2BtPH5DAnZw9g8aSqrat5P5Vj0ZRzat/4SeNGM6teaRrOOdxJYp/hjV4kiFf2ZrdHQ32Lb3Y3L76/frXw==) showing more clearly the generated paths.
It apply a different stroke color to each one so we can see them:

![screenshot-127 0 0 1-8080-2018 11 09-15-13-36](https://user-images.githubusercontent.com/11247504/48267471-bb7f9b00-e432-11e8-8cef-edc9691af363.png)

If you move the cut line to the right, you'll see that we get only 2 parts, as expected (see this [sketch](http://sketch.paperjs.org/#V/0.11.8/S/bVTLbtswEPyVhU4yIDN86pEiPbQoemmAAjn0EPcgS3SsWhYFipaRBPn3LinLcd34Qu5ydmd2x/Zr1JV7Hd1GDzvtqm2URJWpfTyWFszBafuwLXsNd9DpI/ws3TZeRfc5yROmSJapcYkn41suCVNjuL/cc0pSyfIiYZRwpSpGlJQFSyhwkhWZSJaM0EwqcY45kRX1acGVzAAvXHFRhAdYXqKWFClSmWKzpe9OC5VQQmnGfSwyXmQ+5owFLE9ZLkKiKIRHKMY594mCFtInUEdowbJcpb6kyLOQEBkV0ktJs1zgvISzlKn3BCecUoGyfYlkEnDqgkqByBzZFFwDCReoz3PnWcoRLrHMx0zmqYBrKX5QTgOeicK35zJVfJ4OrqZ9WUWLTyu76t5dI4OzZqe/mtZYdHAVWV2vogDy9lYH95G56J5KeLDCe1KQFLw1BeH+5Oj9zDQ3+I9n3ZbV7sR0BjlbdkNbOh3jN2FqMCsZ+rZxnh+rL+TXzdjUOp47JPAKE9MtOHvQ8DZ1OVdfUAiaAL1+HnSrK6drZPH116//DNEd2vas8eYGKquxL5TwZM2hh2ODYiuz782he4LeS6+2TVtb3YEzUPZ9+4zgutlsNObcqcvEgYWexHSgy2qLpz5b0mKA7O+qQiZenE2b6CfHvvt7HBBkZj85E3JW7804F4fC05C/mjrsml+8fLg7z9hbPV4uZILPfGRj7DecIo4bp/cJNAu4+wyvHgj48cmrzYaTIFtt9idtb4vLVQ9V2WrQo7bPbtvgegcDR1xa2cGgNay1w2+Ix/bW/EFDSVm5ZtQ/ymdtyaZxX9CTeojHRh/JOtxJaBnjD1UtJir8o1ujo7veNJ0botvH329/AQ==)):

![screenshot-sketch paperjs org-2018 11 09-15-19-20](https://user-images.githubusercontent.com/11247504/48267551-eff35700-e432-11e8-8663-743c80719f4e.png)

I close this issue since there is nothing to fix.
