### ISSUE TITLE
ps tool assigns wrong value to points if the view is resized.

### ISSUE THREAD

**Issue by dtracers** [paperjs/paper.js#1359]
So I have a canvas at a certain size that takes input for drawing.  It is then dynamically resized (not by a window move)
and I call 

```
ps.view.viewSize.setHeight(canvasElement.height);
ps.view.viewSize.setWidth(canvasElement.width);
```

Which resized the elements correctly.

But When I try drawing again the point values that the ps tool gives me no longer matches up with the points that are drawn to the screen.

This is really messing up my project and I do not think I can fix it externally because it also needs to scale negative values and with the zoom in and zoom out of the canvas using ps.view.zoom

Is there a way the to make it so that the points in the event always matches up with what is drawn to the canvas?

**Comment by sasensi** [comment]
You can resize the `<canvas>` element and the `view` at the same time by setting [view.viewSize](http://paperjs.org/reference/view/#viewsize) property.
Here is a [fiddle](https://jsfiddle.net/xidi2xidi/cn95jamd/4/) demonstrating the solution.
It draws a red rectangle for original canvas size, then resize canvas and draw a blue rectangle for new canvas size.

```javascript
paper.install(window);

// bind paper to the canvas
paper.setup('canvas');

// draw a rectangle matching original view size
new Path.Rectangle({
    rectangle: view.bounds,
    strokeColor: 'red',
    strokeWidth: 5
});

// resize canvas and view at the same time
view.viewSize = new Size(500, 500);

// draw a rectangle matching new view size
new Path.Rectangle({
    rectangle: view.bounds,
    strokeColor: 'blue',
    strokeWidth: 5
});
```

![screenshot-jsfiddle net-2018 11 09-10-54-19](https://user-images.githubusercontent.com/11247504/48255736-d55ab700-e40d-11e8-9ba5-db69315d179e.png)

I close this issue since there is nothing to fix.
