### ISSUE TITLE
exportSVG without embedImages set to `true`: image in wrong position

### ISSUE THREAD

**Issue by fdiazsmith** [paperjs/paper.js#1364]
I believe there is a bug in the exportSVG when done without embedImages.
here is minimal test setup I did. Contains `paper.js` `index.html` and `img`
[testpaper.zip](https://github.com/paperjs/paper.js/files/1184984/testpaper.zip)

I trying to export card of images with information about that image attached to it. 

When I do an exportSVG with embedded images. it works fine.
This test file is correct because it matches perfectly what I see on paper js canvas. 
The image and the test grid should meet in the corner 
![image](https://user-images.githubusercontent.com/5597587/28745284-c9b0053a-7475-11e7-8e01-c235e6ea3f52.png)

When I export without embedded images it comes out looking like this. The further it is from the canvas origin the further the separation is
![image](https://user-images.githubusercontent.com/5597587/28745306-1fb1e14c-7476-11e7-8e22-78aef6496019.png)

any information around this issue will be greatly appreciated.

**Comment by sasensi** [comment]
This issue seems to have been resolved by recent changes, look at this [fiddle](https://jsfiddle.net/xidi2xidi/usdqx349/).
Exporting with or without embedding image outputs:
![screenshot-jsfiddle net-2018 11 07-12-39-31](https://user-images.githubusercontent.com/11247504/48129587-41141700-e28a-11e8-8fdb-d1fc89fb7df0.png)

I close this issue since it seems to have been resolved.
