### ISSUE TITLE
Path.intersect() returns null while Path.intersects() and Path.getIntersections() return valid results

### ISSUE THREAD

**Issue by Sagar-19** [paperjs/paper.js#1370]
Hi, 

I am a newbie to paperjs. I am facing some issue while using path.intersects().
I am trying to find intersected path between two paths (whose boundaries are overlapping). I am using path.intersects() but not getting the expected result.

Here is the sketch - 

http://sketch.paperjs.org/#S/jZLNTsMwEIRfZeULbZU4bdLQP3GCSw9ICI6Yg5OukiiuXdlOKkC8O3bSAm0F4uasZr8Zj/NOJN8iWZKnGm1ekoDkauO/W64hq4pHzC2XhUC4AYl7eOC2HDByH8Z0ngbhJKZJnJbxmF63cUoXaRl253BK/ZjO2nAyp4kf09kbI8MVkz+p1FitarxVQmnncJUJntdXTsSkD2C2XIhfI0wSOk6DBU1m6dHG5Vm03fFgdko4s2NEaTdHRjrHXEmjnEioYnASskC7lha1cZPKiQan1CEVKAtbDlcQRTD9A1QdKReIftfqBv+zfhFg5zq545b3GNkI4S/EZDSCNfCtA79WsgCrwN0FbInwxcIN+G3I0O4R5emjc7k5e4QA9qVXKZeQS1A71NyXApWBxjgYk5WFomrRdDl6uOect3gQTWGnXBjTab4L8jyNttGyC+6KGUXu78w08rpfIMvnl49P

Am doing it right?
****

**Comment by sasensi** [comment]
Calling `path.intersect()` with `trace` option set to `false` will give you the result you are expecting.
Quoting from [documentation](http://paperjs.org/reference/path/#intersect-path):

> options.trace: Boolean — whether the tracing method is used, treating both paths as areas when determining which parts of the paths are to be kept in the result, or whether the first path is only to be split at intersections, keeping the parts of the curves that intersect with the area of the second path. — default: true

See this [sketch](http://sketch.paperjs.org/#V/0.11.8/S/fZI9T8MwEIb/yilLUim5tgmmX2KBFSQEAwNlcJJrYprale2mgqr/HTtVK1IJBkvn8/l5H1k+BJJvKJgHr2uyRR3EQaFKv2+5hlxUL1RYLquG4A4k7eGZ2zoKn5IUpyxOxilmKavTEd62KcMZq5OuTm7Qt3HSJuMpZr6Nk+9wsFjqpfxNRWO1WtODapR2CWHe7CjspvzyDmbDm+Yvi3GGIxbPMJuwc5JTmrVdec7rE64TK00k+5FCWtLGXRBK+iQ31nO+nEd9dAwHq3lBc1jxxtDxFH9NuxbQVIb/Db6JslNIL47DIZiCu8ewtZCVgd0WjII9QcElGCLIyTqUH91q9emIyB21pUf+RRpXwt6rnSxN1AraY97V2BGjEbLBYOF+Qa6Jr7fKOZlg/v5x/AE=).

![screenshot-sketch paperjs org-2018 11 06-17-12-59](https://user-images.githubusercontent.com/11247504/48077326-67cd4180-e1e7-11e8-9602-fd3a494d8e18.png)

I close this issue since there is nothing to fix.
