### ISSUE TITLE
item.onMouseDrag event always reaches view

### ISSUE THREAD

**Issue by Primi2000** [paperjs/paper.js#1397]
Hi guys!

I have this code snippet (just an example):

```javascript
var path = new Path.Circle({
    center: view.center,
    radius: 30,
    fillColor: 'black'
});

path.onMouseDrag = function(event) {
    path.position += event.delta;
	event.stopPropagation();
	return false;
}

view.onMouseUp = function(event) {
	console.log('view.onMouseUp');
}
```

According to the documentation, the onMouseUp event should not be triggered, but unfortunately it is:
"Note that such mouse events bubble up the scene graph hierarchy and will reach the view, unless they are stopped with event.stopPropagation() or by returning false from the handler."

Did I do something wrong or am I missing something?

Thanks!

**Comment by sasensi** [comment]
Hi,
I think you misunderstood what documentation says: when you stop `onMouseDrag` event propagation, `onMouseUp` event is not affected, only `onMouseDrag` is.
If you try to add a `view.onMouseDrag` callback instead of `view.onMouseUp`, you'll see that propagation is properly stopped.
Look at this [sketch](http://sketch.paperjs.org/#V/0.11.8/S/jZDBasMwDIZfRfiSlBUz2C2lp+46KOy47qA6amqiWcZ20kPJu89OSC67zGBs6f+lT+ipHP6QatRnT8nc1V4ZaUs8YgCP6Q5HcPSAc/7qkw2GqX5ewsVBPoZcotDAaOmhl2C/agFbO8QG3l631M0yn4QlV1RXRtNXRZl2h/KUW3ha3IcMkd4Ddpl9G5xJVlxNY+6/g409e71EW1R4OcJs0C1xwsNqWnIxiT8H8djh3GoBTht2Hv+fWCMuCpNm6erqT6FBZmqrFZC3eQ2EvRfrUlTN1/f0Cw==) (drag the circle and see that nothing is printed to the console).
```javascript
var path = new Path.Circle({
    center: view.center,
    radius: 30,
    fillColor: 'black'
});

path.onMouseDrag = function(event) {
    path.position += event.delta;
    event.stopPropagation();
};

view.onMouseDrag = function(event) {
    console.log('view.onMouseDrag called');
};
```

I close this issue because there is nothing to fix.
