### ISSUE TITLE
Attach Mouse event with paper js Hexagon not working 

### ISSUE THREAD

**Issue by Govi-p** [paperjs/paper.js#1418]
Hi,

I am drawing 6 hexagons(HoneyComb structure) In typescript onInit using the below mentioned method,
drawHexagon(positionX,positionY){
    console.log('draw Hexagon');
    console.log(this.angle);
    var tool1 = new Tool();
    this.hexagon = new Path();
    for(let i = 0; i <= this.noOfDimension; i++) {
      
        this.hexagon.add(new Point(
          this.radius * Math.cos(this.angle * i), 
          this.radius * Math.sin(this.angle * i)
        ));
      }  
      this.hexagon.position.x += positionX; //300;
      this.hexagon.position.y += positionY; //300;
  }
=> In mouse click i wants to fill any color in hexagons. the color should fill in all hexagons.
=> I used the below code to fill color. But it is not working as expected. It fills color in only one Hexagon, even this also sometimes not working on mouse click. 
       this.hexagon.onClick = function(event){
         this.fillColor = "pink";
       }

Please Help to resolve the issue.

**Comment by sasensi** [comment]
Hi, based on what you describe, here is a [sketch](http://sketch.paperjs.org/#S/XVTLbtswEPyVhS6WH5GVAjUKOT4UadEEaAsjSU+ODzRFWaxo0iCpOEbgf++SkmipvIhajnZnZ4f6iCQ5sCiLnitmaRnNIqpy9/5GNDx9/fb45xlW8DldvupX6WIleyd7JQ1GN9sQPSouLYbeODsllEnLtD+bz4ESQWtBLIOcH5g0XEkotDp0maCBg1VgeM66jD+///7x8oApfxFbJlSZ2G/WjzCHxRgmLTlfpa2Ua3IK/FysUBpil4xjntslPu5WsMDndDqGD4cAXA7Qclg1jSQkz2PJTrB2b3FAukXkXrAMU01gkc76J4LJvS2zjvkEPnWnl/F42e07fsmxNmVMNUNlHppY3LBowZd+Z9wcBTkDl8bqmlreNhg4vrD3Hk+qMI+0GYzuBacVoMhEnoPgqDQtsQ8GtmQIFiiTKoAIMQoNeR2y/jxhCpt0Bje3X9JtgP2tjeUFp8RRwnoNdOT5j8Nsilp6zjBs19foDUIzW2sJvik36ye2R+PotRJnBx+MoSmUNTwHY3AmMhksBkFNcl5jtDHN4KjgQtw7DZC+0k6W0TCf1apiHWInCK2GAJyPYdaJTL3aaHixQ1Qfo6SfRNYK77Nd3TGc91WtKzbuyYT19lgPqeZ4i2g/lbeyn+cK/HdJg4qv/sOvyfEo0EvWGYERWnbG6CCDa5P6a3O1bePy/+9Q39kbvk2CqJjBEwr1L6FX/Nfs0A+VH6GJss328g8=) demonstrating how it can be implemented.

I close this issue since there is no bug to fix.
Please post future questions in [Google group](https://groups.google.com/forum/#!forum/paperjs) instead of here.
