### ISSUE TITLE
Bug: Small or normalized (between 0 and 1) x and y values in Points array of Path.segments do not Simplify well

### ISSUE THREAD

**Issue by dylansnow** [paperjs/paper.js#1432]
# Description/Steps to reproduce

The following code produces different results if the points are multiplied by 1000 (npm used here):

```
import { paper, Path, Point } from 'paper';
var parser = require('html-attribute-parser');

export function getPathSegments(pointsArray) {
    var pointsArray = [[0.15742397137745975,0.5935201749155238],[0.1426654740608229,0.595905386603061],[0.13640429338103757,0.5974955277280859],[0.12477638640429338,0.6016696481812761],[0.11359570661896243,0.6074339097594912],[0.1050983899821109,0.6141920095408467],[0.10196779964221825,0.6199562711190618],[0.10196779964221825,0.6267143709004174],[0.1050983899821109,0.629695885509839],[0.10867620751341682,0.6312860266348639],[0.11225402504472272,0.6324786324786325],[0.11806797853309481,0.6340687736036573],[0.1283542039355993,0.6340687736036573],[0.13416815742397137,0.6330749354005168],[0.1449016100178891,0.6302921884317233],[0.15742397137745975,0.6253229974160207],[0.17128801431127014,0.6199562711190618],[0.18246869409660108,0.6161796859471278],[0.20125223613595708,0.6112104949314252],[0.21601073345259392,0.6086265156032598],[0.2334525939177102,0.607036374478235],[0.24686940966010734,0.6068376068376068],[0.2558139534883721,0.6088252832438878],[0.2620751341681574,0.6129994036970781],[0.2652057245080501,0.6205525740409461],[0.26654740608228983,0.6227390180878553],[0.2701252236135957,0.6289008149473265],[0.2759391771019678,0.635261379447426],[0.28846153846153844,0.6420194792287816],[0.2947227191413238,0.6438083879944345],[0.3009838998211091,0.6446034585569469],[0.3085867620751342,0.6440071556350626],[0.3152951699463327,0.6424170145100377],[0.33094812164579607,0.6372490558537071],[0.3430232558139535,0.6326774001192605],[0.35286225402504473,0.6294971178692109],[0.36359570661896246,0.6263168356191612],[0.3738819320214669,0.624130391572252],[0.3949016100178891,0.6219439475253429],[0.40429338103756707,0.622142715165971],[0.4083184257602862,0.6229377857284834],[0.4163685152057245,0.6255217650566488],[0.4257602862254025,0.6320810971973763],[0.4288908765652952,0.6344663088849135],[0.4432021466905188,0.6416219439475254],[0.454830053667263,0.6450009938382032],[0.462432915921288,0.6457960644007156],[0.4673524150268336,0.6459948320413437],[0.4789803220035778,0.6453985291194594],[0.4977638640429338,0.6430133174319221],[0.511180679785331,0.6412244086662692],[0.5214669051878354,0.6398330351818724],[0.5362254025044723,0.6372490558537071],[0.5518783542039356,0.6320810971973763],[0.5813953488372093,0.6205525740409461],[0.5957066189624329,0.616577221228384],[0.6104651162790697,0.6135957066189625],[0.6149373881932021,0.6118067978533095],[0.6162790697674418,0.6110117272907971]];
    var canvas = document.getElementById('theCanvas');
    paper.setup(canvas);

    var path = new Path({
        segments: []
    });
    for(var i = 0; i < pointsArray.length; i++) {
        path.add(new Point(pointsArray[i][0], pointsArray[i][1]));
    }
    path.simplify(10);
    console.log('Path after: ' + JSON.stringify(path));
    var svg = path.exportSVG({ asString: true});
    var d_target = parser(svg).attributes.d;
    console.log('d_target after: ' + d_target);
}
```
c.f
```
import { paper, Path, Point } from 'paper';
var parser = require('html-attribute-parser');

export function getPathSegments(pointsArray) {
    var pointsArray = [[0.15742397137745975,0.5935201749155238],[0.1426654740608229,0.595905386603061],[0.13640429338103757,0.5974955277280859],[0.12477638640429338,0.6016696481812761],[0.11359570661896243,0.6074339097594912],[0.1050983899821109,0.6141920095408467],[0.10196779964221825,0.6199562711190618],[0.10196779964221825,0.6267143709004174],[0.1050983899821109,0.629695885509839],[0.10867620751341682,0.6312860266348639],[0.11225402504472272,0.6324786324786325],[0.11806797853309481,0.6340687736036573],[0.1283542039355993,0.6340687736036573],[0.13416815742397137,0.6330749354005168],[0.1449016100178891,0.6302921884317233],[0.15742397137745975,0.6253229974160207],[0.17128801431127014,0.6199562711190618],[0.18246869409660108,0.6161796859471278],[0.20125223613595708,0.6112104949314252],[0.21601073345259392,0.6086265156032598],[0.2334525939177102,0.607036374478235],[0.24686940966010734,0.6068376068376068],[0.2558139534883721,0.6088252832438878],[0.2620751341681574,0.6129994036970781],[0.2652057245080501,0.6205525740409461],[0.26654740608228983,0.6227390180878553],[0.2701252236135957,0.6289008149473265],[0.2759391771019678,0.635261379447426],[0.28846153846153844,0.6420194792287816],[0.2947227191413238,0.6438083879944345],[0.3009838998211091,0.6446034585569469],[0.3085867620751342,0.6440071556350626],[0.3152951699463327,0.6424170145100377],[0.33094812164579607,0.6372490558537071],[0.3430232558139535,0.6326774001192605],[0.35286225402504473,0.6294971178692109],[0.36359570661896246,0.6263168356191612],[0.3738819320214669,0.624130391572252],[0.3949016100178891,0.6219439475253429],[0.40429338103756707,0.622142715165971],[0.4083184257602862,0.6229377857284834],[0.4163685152057245,0.6255217650566488],[0.4257602862254025,0.6320810971973763],[0.4288908765652952,0.6344663088849135],[0.4432021466905188,0.6416219439475254],[0.454830053667263,0.6450009938382032],[0.462432915921288,0.6457960644007156],[0.4673524150268336,0.6459948320413437],[0.4789803220035778,0.6453985291194594],[0.4977638640429338,0.6430133174319221],[0.511180679785331,0.6412244086662692],[0.5214669051878354,0.6398330351818724],[0.5362254025044723,0.6372490558537071],[0.5518783542039356,0.6320810971973763],[0.5813953488372093,0.6205525740409461],[0.5957066189624329,0.616577221228384],[0.6104651162790697,0.6135957066189625],[0.6149373881932021,0.6118067978533095],[0.6162790697674418,0.6110117272907971]];
    var canvas = document.getElementById('theCanvas');
    paper.setup(canvas);

    var path = new Path({
        segments: []
    });
    for(var i = 0; i < pointsArray.length; i++) {
        path.add(new Point(pointsArray[i][0]*1000, pointsArray[i][1]*1000));
    }
    path.simplify(10);
    console.log('Path after: ' + JSON.stringify(path));
    var svg = path.exportSVG({ asString: true});
    var d_target = parser(svg).attributes.d;
    console.log('d_target after: ' + d_target);
}
```
# Expected result

Expect that the d_target's would be the same, except with the start, and two control Points being scaled by 1000.

# Actual result

The d_target's differ substantially: in the one multiplied by 1000, there are many Curves within, however the normalized values (the top function shown) have only a single Curve. For example:

**Normalized =**  d_target after: M0.15742,0.59352c-0.09537,0.01541 0.34439,0.08532 0.45886,0.01749

**Normalized * 1000 =** d_target after: M157.42397,593.52017c-13.71862,2.21715 -62.86429,10.14671 -55.45617,33.1942c3.04411,9.47057 26.40107,7.68413 32.20036,6.36056c38.23599,-8.72653 71.63607,-29.52254 112.70125,-26.23733c22.12221,1.76978 23.09772,31.86249 47.85331,36.97078c26.47339,5.46276 69.58736,-19.86499 100.17889,-21.86444c23.10187,-1.50993 38.00103,18.29761 59.92844,23.05705c40.72008,8.83847 89.63292,-11.38391 126.5653,-24.44842c11.14054,-3.94087 24.68966,-3.49992 34.88372,-9.54085

Not sure if this is intended behaviour or not, but it took me about a day to find this out.

# Additional information

Found on:
  Chrome 63.0.3239.132
  Windows 10 Pro OS Build 14393.2007 Version 1607

**Comment by sasensi** [comment]
Hi, your seing this issue because you are passing the same tolerance value to `path.simplify()` in both cases.
This tolerance amount represent the maximal square distance allowed between the original path and the simplified one.
So in order to obtain the same result for a path 1000 times smaller, you have to use a 1000000 times smaller tolerance.
Here is a [sketch](http://sketch.paperjs.org/#S/jVfBbtw2EP0VwZfYqbHmzJAcMkEObYGeeiiQY+KDssvYataSoZVtGEX/vU9Lci0nazeHbJLdp+HMm/dmqH9O+vYmnbw7+fgtTevrk/OT9bCZ/3/fjs1u3W7TH+16GsbmQ0PGmPefx899/XNx0WzG9qGZrlMzjN1V17fb5radrpuHDh/3aXxstsNDs+luUr/rhn43PzUHvh26ftr9Oo7tIwJ/+mRW5NSyRCVRtS6qO2/MykVxbEhtJOdYwuV5M0Mte++sWuNNYI4Z6aJxErw3YjwVoHhrLEeRQEbUaUYiHKKpcjDBxQJlq+rxfH1ghnpD3kdvAwViPUQlwWlqvKcQPVvJULUi0SDxiGy5QI0zMUiIMTCR2WfqyVJkY6KzJlivFUnRq0acxkyBXYbG6DwrEUUUFV6DsleyoiYaY0HYK+dz9NGF4PY/1fJN8OrZqCOx5APvkUIcvAHZYoM/QIkZqbMz1iqzFij4C4dPV6HBeI0anIiJoDFD0begKuiUdyqV/yDOshF03MUoryD3CS7kkqGCBuBZa4zDz1UoNqKF0C1pCLEcbziCtmCFlKUGPaY+z04gL+iFwIKpnVLkGgzIBhOKv1/pVGDrg4/WROgSHGeoJ40eyrOIpAUKlbNjFl/EVaDEZCwEJdC8K6JimmOpiHUMg8TcADSQvSMHrvBtjXoAkSqZglTQKYruBZbSqed5quSiwL7o02eBOhdIooMm8D1TOR06RAvhhhAONS0ENROcSwKhOEh8VKOBKhI2d8rWmQDJ5pj4BrnD5UjL+gNy4fwAAWcoK7wHteFs50pP5+YsOc3IAIMEAqcqOLUiDxTN1srcY/LgQY3gCfOmACEbTxgz5TOXBNkS4kUkhIoqNO7dQRF2Fy7zBOwY2BHetRadyUgxzzyai7cWjbQO1aAtPlZkcAufckEaoxiPSNj4mqiQ4wgj4CBYg7XkickAwToYAjovyOxMiMo6yNIUO6EXmKc4HyNFC/di4R059N8V42MWIQUIn72pJUELfjEmSpcgZDgEEwIGNLUm/3ya+jLNBKIRB1/BLkX4ohAXRWHDZDGYMxL0YmpAX3xwiMQjvmf0CD8oNAXqyunP1oPXUj3GqkXrwB9GAVVkEApwIawwF1eAEUQGnB1skDJ0IXeBvalKuowSx6TeGeexT4pBnqJlqgqh0Cf2CEWF7aQiUQfU7Z2fG1tmLkSCcRYgykjVyRBW5QeTMBTd0bL8mqdDzhiX4r2C7wx02PEYv9AjZnGh085LjkEx2sY14l4sVXy+AhWdt+SwM4KIL0iIEJMBawkCKqrD7IkBB2APilOtMSUGlAcp4aGaZTyylyFEEsxvzGC4rnTI0XLfFBthWSFHXAsgqVjqcU/06Lx1MpnwIISE7/Atl8PBzXLZycvecDVYXmH+5VY+m56mbLqjs+75LYPL7QGbEFJHXehRSRNKt5j9aLJi+8Qs4ue3FFeR2CULG5Uts1zTB2SN5rEqqO4j+Fyx86PR2RmX7w8XuvnW96Hp00PzF/55urjgne1BM2C1S9u0ntIGyGm8S99fJtdjaqfUtM16uH1svqT57thNyyM+dje32+5rlzaEGPuY6+3Qp9OnQxaQ1e2w6ybcO5tfcMk05/mBL8Ndv9mtrlN3dT01bxtaucujT9dsfx+2+/vvm6sxpf7N+5LtLkMfkWK+77ZPN95p2Kax7dfpaNzy4Ck1F83p8o79dnnjPjt7iZ9+wI17/BmW+P9Z4p9jSY5xxD9yNKbNE0OoIjU1/NPdf1eyOpbE4dmZiJnau9uj584/L7k7e6Ut/TDe4M3klabwoilnP6SwGR76l5Ogi0Ua53N5PzQuR0qzPKbrrr9CUc1uwHtTixxTs277ZpfS/j1qTLu77bR/Ubodh79B7gqBu/v0Z/uYxtXXbvpt35nT+y491C7lRMwqFM3gLe4LtPItu/Dk3afLf/8D) comparing two approaches which give the same result:
- simplify using a small tolerance
- scale up the path, simplify it using a normal tolerance, then scale it down
