### ISSUE TITLE
layer.translate(point) does not move the layer by the given point

### ISSUE THREAD

**Issue by lexa274** [paperjs/paper.js#1478]
I'am trying to translate a layer, so its content would appear centered, but i've encountered strange behaviour of the translation method. It seems that the item was not translated by the given point and also pivot point was somehow changed. It is hard to describe the problem, so the [fiddle](https://jsfiddle.net/ytb1epLL/1/) with a test case might be more explanatory.

**Comment by sasensi** [comment]
Hi, thanks for the repport.

We can divide your case in 2 parts:
- first, you noticed that the pivot point (and position) of your layer is unexpectedly reseted to its bounds center after a translation. This is a bug which will be fixed with #1531.
- then, you are wondering why the value of `layer.localToGlobal(layer.bounds.center)` is different from what you expect.
If I'm not wrong, this is related to how `Paper.js` coordinates system actually works.
Item bounds are expressed in the closest parent with matrix not applied coordinates system.
In your case, `Layer` being a root level `Item`, its bounds are already expressed in global coordinates sytem. You can simply use `layer.bounds.center`.
@lehni, could you back me up about that ?
Actually, the only way I known to get the global position of any item in the project in all hierarchy / matrix application cases is `item.parent ? item.parent.localToGlobal(item.position) : item.position`.
Maybe we should have a simpler way to do this in the API ?

**Comment by lehni** [comment]
@sasensi yes that's correct, unless you set `applyMatrix = false`, see https://groups.google.com/forum/#!searchin/paperjs/applymatrix/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ

**Comment by sasensi** [comment]
Closed by #1531
