### ISSUE TITLE
project.exportJSON() export item event handlers

### ISSUE THREAD

**Issue by sadboyzvone** [paperjs/paper.js#1497]
I think it would be a good idea if exportJSON could export the item event handlers too.
It would make some work much easier.

**Comment by lehni** [comment]
Events are functions. How would they be included in the JSON? JSON can't store functions... And some functions are closures that access values outside of their scope, something that can't be serialized

**Comment by sasensi** [comment]
@sapics, I think it can be closed.

**Comment by sapics** [comment]
Thank you very much @sasensi for helping a tons of issues!

To add event handlers to json, we need to use `exec` or `new Function` at importing json.
If user import cracker's json data, it looks very dangerous.
Thus, I do not want to add this feature to paperjs, too.

But, this is just my two cent.
Because, I agree that it would be useful in some cases.
So, it would be better to make a decision by owner.

**Comment by lehni** [comment]
Let's close it. I really don't see a decent way to implement this...

**Comment by sadboyzvone** [comment]
@lehni, I found a workaround so it's fine :D
