### ISSUE TITLE
PLEASE UPDATE YOUR PAPER-CORE.MIN.JS!!

### ISSUE THREAD

**Issue by ValentinZhao** [paperjs/paper.js#1498]
# Description/Steps to reproduce
I am not familiar with your paperscript and also do not need acron.js in order to smaller package when my app bundled up. Therefore I use alias in webpack config and refers to your paper-core.min.js lib just like your README.md instructs. Here comes the issue, **paper-core.min.js behaves DIFFERENT WITH paper-full.js** and after I changing the path to paper-full.js everything just fine. And I am going to illustrate this with several pics.

![](https://static.dingtalk.com/media/lALPBbCc1sB7CbDM_M0BPQ_317_252.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%22334625571%3A334625571%22%2C%22msgId%22%3A%22303952586937%22%7D&open_id=334625571)

![](https://static.dingtalk.com/media/lALPBbCc1sB9OpNQzQJg_608_80.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%22334625571%3A334625571%22%2C%22msgId%22%3A%22303872892220%22%7D&open_id=334625571)

# Expected result
After I change the package

![](https://static.dingtalk.com/media/lALPBbCc1sB7xhzM-c0BPw_319_249.png_620x10000q90g.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%22334625571%3A334625571%22%2C%22msgId%22%3A%22303952872873%22%7D&open_id=334625571)

**Comment by lehni** [comment]
Can you describe what the actual problem is? Is it just the name missing in debugging?

**Comment by ValentinZhao** [comment]
Okay sorry for not offering details. As for me, I encountered with this `initialize` object all over the project, which means all children in `paper.project.layers` is `initialize` and you can not tell which is `Path`, `Raster`, etc.. What is more, some associated methods are missing, for example you can not call `remove()` on `initialize` to remove it from project anymore because this method is `undefined`.

**Comment by sasensi** [comment]
I tried to reproduce this bug. I can confirm the debugger name issue but not the missing of functions.

For the debugger name part, it is due to the fact that when minifying code, function names are [mangled](https://en.wikipedia.org/wiki/Name_mangling) to save space.
Taking the example of `Path` class, the debugger information is extracted from the name of this function https://github.com/paperjs/paper.js/blob/53897d749819b86bc47e935294e14971323a21e9/src/path/Path.js#L89

Preservation of this information in minified code is possible by disabling function names mangling in minify task, adding these

    mangle: {keep_fnames: true},
    compress: {keep_fnames: true}
to uglifyOptions object
https://github.com/paperjs/paper.js/blob/53897d749819b86bc47e935294e14971323a21e9/gulp/tasks/minify.js#L20-L25

The trade off is +6Ko in `paper-core.min.js` output.

For the missing function part of the issue, could you provide a more detailed way of reproducing the error, like a [fiddle](https://jsfiddle.net/) demonstrating it ?

**Comment by sasensi** [comment]
I close this issue for lack of feedback.
It will be reopened if more information is provided.
