### ISSUE TITLE
Defining a "paper" variable

### ISSUE THREAD

**Issue by photopea** [paperjs/paper.js#1544]
Hi, in exports.js, you have a line like this:

    paper = new (PaperScope.inject(Base.exports, { ...

The "paper" variable was not defined before, so you are setting it as a property of a "window"? Did you mean to write

    var paper = ....

?

**Comment by sasensi** [comment]
Hi @photopea, I think this is on purpose as you can see in the comment above.
https://github.com/paperjs/paper.js/blob/fd1a517e84fb17d96b30536cded823651a32caf5/src/export.js#L16-L19

**Comment by photopea** [comment]
@sasensi  I disagree. I don't think authors wanted to define a window.paper variable at that place.

Even if they did, I believe it should be possible to rewrite the code, such that defining window.paper can be avoided.

**Comment by sasensi** [comment]
@lehni, could you enlighten us about this one ?

**Comment by lehni** [comment]
We can't do that currently because of the way PaperScript is compiled on Chrome and Firefox, see here:

https://github.com/paperjs/paper.js/blob/develop/src/core/PaperScript.js#L484

Sadly this only works with a purely global `paper` object.

**Comment by lehni** [comment]
I guess we could work around that though:

```js
			script.appendChild(document.createTextNode(
				'window.__paperscript__ = function(' + params + ') {' + code + '\n}'
			));
			head.appendChild(script);
			func = window.__paperscript__;
			delete window.__paperscript__;
			head.removeChild(script);
```

I need to check if this would break some other environments, e.g. node

**Comment by photopea** [comment]
@lehni Can't you just write "var p = ....", if you don't want to write "var paper = ..." ? That variable is used only in exports.js, so it can have any name, right?

**Comment by sapics** [comment]
@photopea Thanks for suggestion!
Please look at [src/paper.js](https://github.com/paperjs/paper.js/blob/develop/src/paper.js#L124) which is `include('export.js');`.
It means that `export.js` is **directly inserted** to the paper.js source code, so `export.js` is not independent code.
Thus, `var p = ...` would not same as `var paper = ...`.
(I guess that it might be almost same, but it changes a scope of variable `paper` at least.)

When we apply `var paper = ...`, the minified code is 100+ bytes smaller than before and makes scope of `paper` locally, thus it looks better performance!

I think that your suggestion `var paper = ...` looks very good, but we need to do it carefully because there are some effects to the other codes.

P.S. I am not good at English. If I made misunderstood in this issue talk, I am sorry.

**Comment by lehni** [comment]
@photopea yes we should fix this, I agree. The problem I've outlined above is that `PaperScript` itself relies on a global `paper` to be present. And that's the only dependency I've found.
