### ISSUE TITLE
Constructing a Raster with explicit width/height, incorrectly reports loaded as true

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#1604]
# Description/Steps to reproduce

- Construct a `Raster` with `width`/`height` attributes.
- Immediately after check the `loaded` attribute of the Raster.

# Link to reproduction test-case

http://sketch.paperjs.org/#V/0.11.8/S/JcwxDoMwDIXhq1ieiIQqWCP1Eu1IO4TEIhFgV4klBsTdgXR73/C/HdmthBbfM6mP2KKXcNsLF4XsilKGJzBt8KpodthS0Gih77oWIqUpagUc5sN3Jws9Fpmaf31NFyiY63vM5OafJNaCdsAev8cJ

# Expected result

- `Raster.loaded` should be initially `false`, until `Raster.source` is set and actually loaded.

# Actual result

- `Raster.loaded` is `true`.

**Comment by sapics** [comment]
@nicholaswmin I guess that this is intended behavior and your expected behavior looks achieved as [sketch](http://sketch.paperjs.org/#V/0.11.8/S/bZDNboQwDIRfxcqFoCKgh15YVVV/nqDtrfTggjfJLjgoMUUV4t2bXe2lP76NNPN57FUxjqQa9XIk6awqVOf7k+48R4GAUSjALTAt8HwWeoXF9WIbuK7rAiw5Y+UsYMtbPuX8QOXgjc7us+KCSBp76pOh5U8MMIchUTMrMjVVhTGSxHLCicIhlj6Yyo1oKFYjBjd8cXmYzF0GV/CEQiX7Ree7li/o6OfQUcIl6O5Xg4c/DZIjLXt1I/lZtN7P3InzrPO1ZUjzI/74zwFbXsBNXdd5etZHIDxO3rFE1by9b98=).

When the size of rasterItem is set without image and source, the canvas object is created as raster.image. Thus the raster.loaded is true.

When the source of rasterItem is set, raster.loaded is false until raster.image is loaded.

**Comment by nicholaswmin** [comment]
@sapics I disagree on the basis that this doesn't reflect how the HTMLImage element works.

If you don't set a `src`, the `onload` handler never fires there. The image is not considered "loaded" if there's no actual image data asynchronously loaded.

In this [JSFiddle](https://jsfiddle.net/om3x149y/1/), the `onload` handler doesn't fire since the `img.source` line is commented out. If you uncomment it, it fires.

I think `Raster` should reflect the same behaviour.

**Comment by nicholaswmin** [comment]
I didn't know about `.complete`, now that I do what you're saying makes sense.

Closing and thanks a lot for clarifying.
