### ISSUE TITLE
SVG import bug when arc subpaths start and end at same point

### ISSUE THREAD

**Issue by jackytwh** [paperjs/paper.js#1635]
For SVG paths containing Arc subpaths, when the endpoint of an arc is the same as the starting point, that will result in: 
1. `0` valued [x & y](https://github.com/paperjs/paper.js/blob/ed8a904b74c5875b24fd8c083923f33552c5da2d/src/path/Path.js#L2535-L2537)
2. `Infinity` valued [factor](https://github.com/paperjs/paper.js/blob/ed8a904b74c5875b24fd8c083923f33552c5da2d/src/path/Path.js#L2553-L2554)
3. `null` [vector](https://github.com/paperjs/paper.js/blob/ed8a904b74c5875b24fd8c083923f33552c5da2d/src/path/Path.js#L2573)
4. crash took place when trying to read `getDirectedAngle` of a null vector with the error below
`Error: TypeError: Cannot read property 'getDirectedAngle' of null`

This issue should be similar to #930 & #931 which are no longer in open status. However, the bug is not yet resolved.

# Link to reproduction test-case

sample buggy SVG
http://sketch.paperjs.org/#V/0.11.8/S/xVVNjxs3DP0rwvTSAhUtUd+LNIf20Bw2pwC9ZAtkMjuNnR17jPHUDrbof++j5O02aO4LQxxSpCg+iqT/6g79fuxuuncP4zpsux+7Yb4X+dgfx4WOy/x5HFba7Y/zsr777dfvP7w6nT+pL/vpcPrprtuu6/Fms7lcLnRxNC+fNmyM2cDkrlPncTnt5gPMLBmRd+Pl5/kLZKOMsqauu+71q2O/btUfu2mC6jAfRtie1mV+GCF/Z8TmKutpdxiH/oj9Zf7zcP+14vO8O/xfs9+t4zLt8JFAxNc9mLcpkU1eeU/RpT5SYFWJefo97jU2EmtYMA9GWwo+aSomaaYshK12FAwrS84wHDklmxBLCI2terhKlLKVG3uHs1k1+nzZXbd5mTxEJhus8omyTVvEaQOwUomAywGgU2n4vAB25azJRdcHsqWoRutrVj7pujOQDxGblEskE72ct0XQazImgEQsZI+sTU9cSw3cNdqcOiq6ygNFKzuwgyNfwMUCt0XezpeoGm2nLJNPUXIPMGR8kFhMlqugss5VRglyUeESuEswE04WzH0U8xLw3lkT+yggOMANC4hMNloJPYiuMj0qQMlqQTAFwIBs3JuYyIUzagDhfmWFfLEBsAkuGcnPL1cIOVG4lsG/8QZj38j+AOxJUgVQKAnLoXJYZyHAFExWjdZ61le1sY9vXSTYJwOIdqp7qlApeQsesi9FV1lX/qqTw497nDP1CD8fqU48Su35UPrPIdy4x5tZzXje7CedKaYod/fsqaAlr5+Wf5soZiTesb+1MHMoC0OJS8WUVKMNE+rJVU+TtEXMqtJqWFSjTw0tpmFCzacYVPsMEZVXVKPWo6MkD0ECYiqZm7CVcP1TOcjseLnJIEWgQkDn+W9XLWYBl7itKfaDfDJ2NfKYvUO6HHqlgdMV3K0NMgaVw/9BRnrgUEYhGjqkX7ggJagTzFa0LmYNmhw1hxBSuL67lULC65UiG7cepCpbaYnWPquNvY21gtt5X/LAlII8fKwjh2UWqUQcI2a8D3lCg7qoESSzv/aAAGxPIH9qrz/8gH/Ij8vYPxyRyvXU3bz//e9/AA==

**Comment by sapics** [comment]
Hi @jackytwh, thank you for your bug report!
#1614 would fix this issue :)

**Comment by jackytwh** [comment]
Thanks @sapics ! 

I can see there is a conflict in CHANGELOG.md. Will it be resolved in coming days and release a new version?

**Comment by sapics** [comment]
@jackytwh  I resolve it now :)
Sorry, I cannot merge the PR because of authority, but I wish so too !

**Comment by sasensi** [comment]
I close this issue because it was resolved in https://github.com/paperjs/paper.js/commit/3177c7ac4666552260124d57659846c4f18f7d61.
Here is your [sketch](http://sketch.paperjs.org/#V/prebuilt/S/xVVNjxs3DP0rwvTSAhUtUd+LNIf20Bw2pwC9ZAtkMjuNnR17jPHUDrbof++j5O02aO4LQxxSpCg+iqT/6g79fuxuuncP4zpsux+7Yb4X+dgfx4WOy/x5HFba7Y/zsr777dfvP7w6nT+pL/vpcPrprtuu6/Fms7lcLnRxNC+fNmyM2cDkrlPncTnt5gPMLBmRd+Pl5/kLZKOMsqauu+71q2O/btUfu2mC6jAfRtie1mV+GCF/Z8TmKutpdxiH/oj9Zf7zcP+14vO8O/xfs9+t4zLt8JFAxNc9mLcpkU1eeU/RpT5SYFWJefo97jU2EmtYMA9GWwo+aSomaaYshK12FAwrS84wHDklmxBLCI2terhKlLKVG3uHs1k1+nzZXbd5mTxEJhus8omyTVvEaQOwUomAywGgU2n4vAB25azJRdcHsqWoRutrVj7pujOQDxGblEskE72ct0XQazImgEQsZI+sTU9cSw3cNdqcOiq6ygNFKzuwgyNfwMUCt0XezpeoGm2nLJNPUXIPMGR8kFhMlqugss5VRglyUeESuEswE04WzH0U8xLw3lkT+yggOMANC4hMNloJPYiuMj0qQMlqQTAFwIBs3JuYyIUzagDhfmWFfLEBsAkuGcnPL1cIOVG4lsG/8QZj38j+AOxJUgVQKAnLoXJYZyHAFExWjdZ61le1sY9vXSTYJwOIdqp7qlApeQsesi9FV1lX/qqTw497nDP1CD8fqU48Su35UPrPIdy4x5tZzXje7CedKaYod/fsqaAlr5+Wf5soZiTesb+1MHMoC0OJS8WUVKMNE+rJVU+TtEXMqtJqWFSjTw0tpmFCzacYVPsMEZVXVKPWo6MkD0ECYiqZm7CVcP1TOcjseLnJIEWgQkDn+W9XLWYBl7itKfaDfDJ2NfKYvUO6HHqlgdMV3K0NMgaVw/9BRnrgUEYhGjqkX7ggJagTzFa0LmYNmhw1hxBSuL67lULC65UiG7cepCpbaYnWPquNvY21gtt5X/LAlII8fKwjh2UWqUQcI2a8D3lCg7qoESSzv/aAAGxPIH9qrz/8gH/Ij8vYPxyRyvXU3bz//e9/AA==) working with the latest `prebuilt` version.
