### ISSUE TITLE
onFrame animation not working for version 0.12.2

### ISSUE THREAD

**Issue by runtimee** [paperjs/paper.js#1674]
# Description/Steps to reproduce
Tried both on Firefox and Chrome.
http://paperjs.org/tutorials/animation/creating-animations/
Directly copy-pasted from the tutorial but did not work for version 0.12.2. It works if downgrade to 0.11.8:
```
var path = new Path.Circle({
	center: view.center,
	radius: 70,
	fillColor: 'red'
});

function onFrame(event) {
	// Each frame, change the fill color of the path slightly by
	// adding 1 to its hue:
	path.fillColor.hue += 1;
}
```

**Comment by sapics** [comment]
@runtimee Thanks for report!
In sketch, prebuilt and v0.12.1, it looks work as http://sketch.paperjs.org/#V/prebuilt/S/PZDBbsIwEER/ZeQLoEahnCq54oTacyWOpAdjb2IL10bOJgih/HvtBHHwyjvPOzvyQwT1R0KK44VYW1EJHU3pR5VwVWyxR6AbfvK1PrikPa0fTWpCw5oCU5IYHd3qpakWkpRxQy/x8f4UWuf9IfqYX68SmVVRp83nDPNph6DZxYAYvlOOs6Yx223wXLTd4ktpi7awCtqq0BHYEoovdDFGbGdljtx711n2d5zvLwdljAsdduAIxz3sQHKBZaR+JawzwNseuzndVEr+lHMidblGF7gX8vQ7/QM= .
Thus, it would be fixed in next release!

**Comment by lehni** [comment]
This is identical to #1672, and already fixed. New version coming up shortly!

**Comment by lehni** [comment]
`v0.12.3` is out now
