### ISSUE TITLE
Setting position in Shape.Rectangle constructor causes incorrect bounds calculations

### ISSUE THREAD

**Issue by nikkwong** [paperjs/paper.js#1686]
```
var shape1 = new Shape.Rectangle({
        point: [20, 20],
        size: new paper.Size(100, 100),
        fillColor: 'blue'
});

const shape2 = new Shape.Rectangle({
        fillColor: 'red',
        position:  shape1.position,
        size: new paper.Size(50, 50)
})

console.log(shape1.bounds.area) // 10000
console.log(shape2.bounds.area) // 0
```

[Sketch](http://sketch.paperjs.org/#V/0.12.3/S/hZDBisIwEIZfZcilLZRQC16yePINtkfrIW1nNZidKUlUUHx309piFxbMYcI/+f/hy9wF6V8USlQnDO1R5KLlbtAX7cAfdY8r2ADhFapByG9sg6aDxfReE0ynZ0NBwa4sciiLff5+8eaGaoz3Me1kFXW6KqIvlmxh/DHWbtmyU5A09oxJTY/sq6aaWiYfXijlZ5TlHIddki8pvQmGScH0MTl3PgGvI++6yAakmYgtSsuHdJrU8Jk6L7VDnf1jKP8Y4pKbeJ/GtXmhdvvHEw==)

**Comment by nikkwong** [comment]
Somewhat unrelated but also wonder why you can't just copy bounds from one item to the other. 

```
var shape1 = new Shape.Rectangle({
        size: new paper.Size(100, 100),
        fillColor: 'blue'
});

const shape2 = new Shape.Rectangle({
        fillColor: 'red',
        bounds:  shape1.bounds
})

console.log(shape1.bounds.area) // 10000
console.log(shape2.bounds.area) // 0
```
If bounds is supposed to be readonly, it would be nice to note that somewhere.

**Comment by sasensi** [comment]
@nikkwong, thank you for the report.
The bug was actually linked to the fact that position was set before size, resulting in invalid bounds being cached. #1708 will fix it.

About your second statement, yes, I think that bounds are supposed to be readonly and we are working on improving the readonly states in the documentation along with the typescript documentation improvement.
@lehni, can you confirm that every variant of bounds (bounds, strokeBounds, ...) should be marked as readonly ? If yes, I can make a PR to fix the documentation.

**Comment by codemacabre** [comment]
Encountering an issue of my own which might be related: the linked sketch above (and any kind of transform I've experimented with) outputs massive numbers of `_transformBounds` errors in Chrome when zoomed (but works as expected in Firefox).

![image](https://user-images.githubusercontent.com/49149591/69651081-73481080-1067-11ea-9ddd-2a3208f9d16d.png)

@nikkwong @sasensi Is this the same / related issue or should I create a new one?
