### ISSUE TITLE
[Feature] Path get nearest segment.

### ISSUE THREAD

**Issue by Domvel** [paperjs/paper.js#1692]
Like `getNearestPoint(point)` but for the segments of a path. The new method `getNearestSegment(point)` should return the nearest segment.

http://paperjs.org/reference/path/#getnearestpoint-point

Workaround: Iterate through all segments in path and compute the min distance to a point. Hold the segment of the current min value and return it.

paper `0.12.3`

**Comment by sasensi** [comment]
I am not sure that this is needed since [path.getNearestLocation(point)](http://paperjs.org/reference/path/#getnearestlocation-point) already provide this information.
It returns a `CurveLocation` instance which has a `segment` property corresponding to the nearest segment.
So all you have to do is `path.getNearestLocation(point).segment`.
Here is a [sketch](http://sketch.paperjs.org/#V/0.12.3/S/dVJBboMwEPyK5QtEQiiJ1AtVTrk2bSWOTQ+OsyEIWEdrQw4Rf6+xSwxURULYM97dmcEPjqIBnvG8AiOvPOFSnYe9VKgNuwlzZTuGcGefdpnmRlD8ONIRmX0koAHKWFfCPfWbZORuqkSjM7bZPiES57LVm4y9rBfY1p5bB1AbUhXsVa1s8+hUC1lFA9evXofP8F5alKZUyBQeVKvhoDqIobMaVizocx4QBIE2ORSNpa2bAsz7DIsHmwlz5akT7geFHo2gCmiaxL4kWUPIYprHfKLvmEwPetc2iBl6Ket6NK1IYAHRSPdBkJeSEjTW8gc6457t/4Tzn1PvcRlUraRwZTv339NQ/fbLxItwCExL+CxMtZ8S1Nj7dCIQlb8NPPv67n8A) demonstrating the solution.

    const path = new Path.Star({
        center: view.center,
        points: 12,
        radius1: 50,
        radius2: 100,
        strokeColor: 'black'
    });
    
    function onMouseMove(event) {
        const nearestSegment = getNearestSegment(path, event.point);
        const marker = new Path.Circle({
            center: nearestSegment.point,
            radius: 5,
            fillColor: 'orange'
        });
        marker.removeOnMove();
    }
    
    function getNearestSegment(path, point) {
        const location = path.getNearestLocation(point);
        return location.segment;
    }

**Comment by Domvel** [comment]
@sasensi Thank you! :) I somehow missed it.
