### ISSUE TITLE
Fuzzy Lines in Rectangle

### ISSUE THREAD

**Issue by peterjslater** [paperjs/paper.js#1735]
I am new to paper.js and don't understand why the lines have two pixel width with some alpha even though the stroke width is 1.

e.g. using the paper.js website rectangle example to isolate the issue.

[http://paperjs.org/reference/path/#path-rectangle-from-to](http://paperjs.org/reference/path/#path-rectangle-from-to)

With the rectangle example defaults the line looks fuzzy with 2 pixel width

`var from = new Point(20, 20);`
`var to = new Point(80, 80);`
`var path = new Path.Rectangle(from, to);`
`path.strokeColor = 'black';`
`path.strokeWidth=1`

However if I change the code to add 0.5 to all the points, it looks sharp with 1 pixel width

`var from = new Point(20.5, 20.5);`
`var to = new Point(80.5, 80.5);`
`var path = new Path.Rectangle(from, to);`
`path.strokeColor = 'black';`
`path.strokeWidth=1`

Also noticed that if i change the strokeWidth to 2 in the first example it also fixes the fuzzy and looks sharp.

var from = new Point(20, 20);
var to = new Point(80, 80);
var path = new Path.Rectangle(from, to);
path.strokeColor = 'black';
path.strokeWidth=2

Why does the default lines with stroke width of 1 draw a 2 pixel width but when i change to add 0.5 it changes to a single pixel width ?

Is there a way to get a single pixel line without adding 0.5 to everything ?

Regards
Peter

# Additional information
I am running this on a windows 10 laptop using chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by arnoson** [comment]
This happens because the stroke isn't applied on the outside of the rectangle but in the middle. So if you have a strokeWidth of 1 px, half a pixel is drawn outside the rectangle and the other half inside the rectangle. You can see how the stroke is applied if you set it to a high value ([sketch](http://sketch.paperjs.org/#V/0.12.3/S/VY7BCoJAFEV/5TEbCyQGIZDZ9gORixbqYnJeOajvyfiihfjvTRZFd3fPhcOdFdkBlVFFh9K0KlUNu1cnfMDRSrs7YSOWbj1u5oog5hp4MFBmOoVM1+kbCkeUR5R/0SSBOzx7J62Bvf6jB+45GEgCuuQzjDx58UyrenX/TNjHE+gMSLhjRcs2/rwEtN3InmRSpqyXJw==)). Therefor you get the fuzzy line, for this is the only way to render half pixels. If you add 0.5px to the rectangle coordinates you avoid these half pixels, because if you add 0.5px for half the stroke you get an integer value again.
Also, if your strokeWidth is an even number (like the 2px in your example) there are also no half pxiels.
Unfortunately, as for as I know, there is now way of specifying an inner or outer stroke alignment. Which would solve the problem without the 0.5px workaround.

**Comment by arnoson** [comment]
As I see, the stroke alignment has already been discussed here #494, so I'm closing this issue.
