### ISSUE TITLE
how now work with paper on nodejs? and paper with typescript?

### ISSUE THREAD

**Issue by sevaTechoPark** [paperjs/paper.js#1783]

**Comment by sasensi** [comment]
Hi, this is an issue tracker so you better address this kind of question to the [support forum](https://groups.google.com/forum/#!forum/paperjs).  
Anyway, you can find examples of working with nodejs in the `/examples/Node.js/` directory of this repository.  
About TypeScript, I recently answered a similar question [here](https://groups.google.com/forum/#!topic/paperjs/k35OzEXvm_Q).  
I close this issue since there is nothing to solve.
