### ISSUE TITLE
How to disable auto calculate path center

### ISSUE THREAD

**Issue by lgl017** [paperjs/paper.js#1789]
I want draw a polygon with complex control, but auto calculate path center make it confusion, have any way to close it?
[sketch](http://sketch.paperjs.org/#V/0.12.4/S/jZLBaoQwEIZfJXgxAZt1F7zssr30BQo9uh5iHDSoiSRZpZS+exPT2nVtSw8h5Bv/f/4ZfIsk6yE6Ri8tWN5EScRV5d8j02hQQlqDziiXMKFn/8JpglKSoBU4rMnhZ7SRpaQ4XfRF+jMXmG3w6ouHfbpReUSosVq18KQ6pV2+uNbwGp9+MfIu9+0/0R9G/owCJspBWvDF3EuKhRvOOiFrV9ini8BvzXV3cAlCZjtP75tpqOLvIqsqTCkNS78RDcoIK5T0CbIkK1aCmynDjskSfrcrrxYJNDFpkVWoBnc1wnzp/5ex7K4QQvrZejVC5XAISU0nOGBCuZKcWZxv0hSE9mzAAzo/omEOnBGyGXl2Ddj9gKUG1oYG0TEv3j8A)

**Comment by sasensi** [comment]
Hi, this is an issue tracker, so for this kind of question, please use the [support forum](https://groups.google.com/forum/#!forum/paperjs) next time.  
Anyway, you have to disable matrix application on your path in order to be able to do what you want (see [path.applyMatrix](http://paperjs.org/reference/path/#applymatrix)).  
Here is a [sketch](http://sketch.paperjs.org/#V/0.12.4/S/fVKxbsIwEP2VUxYSKQ0BiQXE0s6VKnUMDEd8gJXERvaVNKr677VjCgRKBw9+7967Z999RQobiubRe0Vc7qM0KrXw9yMaOGip2MISCkUtvPlbnKeQJykMgOkQmf4N3cnyZL1YmZXypyeQ9/Gg4mmS36k8lGSWja7oRdfauHyjnaFutHhg5F1u25+gf4z8OUpqs5IUkycLLwmRe8KWWEu1c8wkv0j8v7n+Dj1HSXrWo7ftDInQbTyG5w6EtLjpPRtkIz8BD4dalshSK2jJoRWB/TAEvEf+LWKDym61afo6Cye/VqsRw4aCCQlgHZKdxlpqbYRUyGSzcz5f270G3yVssbZ0CY9CxFmWBf3Vo/oAtTOKZynMkqHgag5hCwLvNm1jCKtgFs2L9fcP) demonstrating the solution.

**Comment by lgl017** [comment]
Thx, I'm sorry about this, but I can't access Google for some reason

**Comment by lehni** [comment]
You can use [item.pivot](http://paperjs.org/reference/item/#pivot) to specify your own registration point for the position.
