### ISSUE TITLE
the method hitTest will return some non-existent Path

### ISSUE THREAD

**Issue by Terness** [paperjs/paper.js#1878]
I have a CompoundPath in a Layer, and then i use hitTest  to get the CompoundPath 

But actually, i will get a non-existent Path instead of the CompoundPath by hitResult.item

Actually, in my project, i will use Path and CompoundPath at the same time, so did i use wrong?

[Here is the demo](http://sketch.paperjs.org/#V/0.12.7/S/dVLLTsMwEPyVKBzqSJHlFkWtWnHqlUMFSBzSHIy9EBPHjmy3gBD/jh8kKRIcoozHO7OT3XzmivaQb/P7Dhxr8zJnmocz08q6TNIPMNlNpuAtG+gABt8GBhVHlY6D0a/AHKacp5uoKHZHFQGmzIkzdYAClTwH6trlj+fB42TmuWCCMMZ1XZGyIk2Z1UuSUAT+CVyVUDPJrDO6g0fBXettr3cj/yyk3Gupxw+IGC2uCCGLYqpiUlvgvsSZExzVZcrVHylXc8o1Kdcx0SaB8N5EYh1BM0n+6WGAyuDtL1IWeGfyxAFFVYg4jtFAr8+wb4XkBhS6mC/nE1uPfk2SpiZMCtYdtFDu1x4jg/wss4rMu2mFuwN7kqHWtcJO+/UXD2Admt3mHloClvoFTWIsHPSF/5eefKJuCNU239bN1zc=)

**Comment by arnoson** [comment]
You get one of the CompoundPath 's children as a result. So the resulting path exists (its not the non-existent path you used to create the CompoundPath ). In order to get the whole CompoundPath (the parent of the path you get) you have to change your `hitOptions` to only test for CompoundPaths:

```js
project.hitTest(clickPoint, {
    // Using the default options (http://paperjs.org/reference/project/#hittest-point)
    fill: true,
    stroke: true,
    segments: true,
    tolerance: settings.hitTolerance,
    // But only test for compound paths ;)
    class: CompoundPath
});
```

Here is a [demo](http://sketch.paperjs.org/#V/0.12.7/S/dVNNb5wwEP0rFjmElQiQVKuNWPXSvfYQ9UM9sBxce3Zx1tjIHtJGUf57x/ZCslKDhBjezLx5fgMvmeEDZE32/QQo+qzIhJXhXVjjkWn+DI59Zgb+sJGP4MqvAclXe5NeR2cfQWDJpUyZ2LHa7k0MSi5QPXGEPEB7k1hHjv3tmfWB4kRHWKDJy7Js23VdrOuuYO1tnaIY0B2wdYq6pc2jsyf4pST2RPtpO+MHpfXOajsfIcb59VVd19erpUpo60FSCboJLlXe/Ufl3ZvKTV1soqL7FITnfQQ2MeiWlg9mOOA6cFMiaYG/Qk8S8tiVPEtGOhjsE+x6paUDk79zWMoFbWe+7r3dQitxerDK4MUmI5KTl2xdp/K5oVf4DfykQz32yi9bpsQP8Ji/MRbsZW8YXVXFfnpljtQATMKBh3Y7oiJGlveIY1NVcfCjL607Vg4OQJoFVGf26orokehvxsC8SrxhhU10rUhA2vUlBMcBDPoLEK0Gx4m/oTwiSfNR/wwXi+4vEyk1+pmF4exAX4uww2gnI+NSPNuetQjNPQ3ZnbPB6L15Td4tnpUKYSg9aDrSsnH6r37Tbk7xZD5r2u71Hw==)

**Comment by Terness** [comment]
But in my project, i will addPath and CompoundPath at the same time in a Layer, so when i click the item , i don't kown it belong Path or CompoundPath, i can't use the `class` to only test for CompoundPaths, beasuce  it will lose the Path item.
Do we have any options which only test for the item(not the item which paperJs automatically added ,like CompoundPath 's children) that are added to the layer?

**Comment by arnoson** [comment]
Ah I see, in this case you can use the `match` function and check if the items you are testing in `hitTest` aren't CompoundPaths or children of CompoundPaths:

```js
match: ({ item }) =>
  item.className !== "CompoundPath" &&
  item.parent.className !== "CompoundPath",
```
or without the use of arrow functions and destructuring:
```js
match(result) {
  const item = result.item
  return (
    item.className !== "CompoundPath" &&
    item.parent.className !== "CompoundPath"
  )
}
```

[demo](http://sketch.paperjs.org/#V/0.12.7/S/lZNNb5wwEIb/ypRKWVaikI3UCxK55NRLU/XjtOzBgQGcNR5kD0rb1f73jmFJdqNKbXxAeD5eP54ZHyKreozy6NseueqiJKqoDvuKrGcYFHcbKMDiE3yR//QrVqxsazA+lBZkhfQcVvdOt9oqM0XBZpXM3oG8Zk02h+3m+joB+exOLq9/S2KwzvtGG3NHhpyoPZgRV6U9rktb2heSm7eT3Pw3yce/gTisX3FU1A802npSL+YCpfizMmON8QR5FuzQj4ZDmKNH4U07zd/Rc7yV0+TEXQIn+CyDH17bFrhDqLFRIY+GQOwh7piHPMsGNaB79Cm5NnPYoENbYXbSzt6LOIv4h4G05fXLZXJgN+JyWXa0x0sTtj1a9hdGJoNOiX4ufmZB8xP9Yk6eue+t+QWGaA8NuakgXm6hGJTwrRjuzirmQdl6cVSdNrX8PitRcxmczp5eyWTmEB9AM/ZwXENxO3vCCra0Msr7zzIA8K4ooIzOZcoIrq5exQ8Bgf+Rliydn9uYTpkejRQba2lqqFZphfuTrVEsTwgt8tRBWoZwfkBK7n0ahnk0pIqpoTY+Vw7zu5YH+OBQ7ace+ijf7o5/AA==)

**Comment by Terness** [comment]
thanks for your help!!

**Comment by arnoson** [comment]
You're welcome (:
