### ISSUE TITLE
When setting width or height property equal to 0 on path's bounds, we just can't reset the property to an non-zero value

### ISSUE THREAD

**Issue by wiskewu** [paperjs/paper.js#1938]
Is it indent to act like that?
```
const item = new Path.Rectangle({ x: 0, y: 0, width: 100, height: 100 });
item.strokeColor = 'red';
item.bounds.width = 0;
console.log(item.bounds.width); // 0

item.bounds.width = 100;
console.log(item.bounds.width); // 0
```
# Description/Steps to reproduce
[Here is a little preview of what I am doing.](http://sketch.paperjs.org/#V/0.12.15/S/fY/BCsIwDIZfJfSyCaPM68STLyB6VA9dG9ayrpE1MmXs3W0HggfxEvIn+b+fzCKoAUUjzj2ytqISmkzWmkJkcIwD7CHgBEfFVp5Qswqdx3KGZwN1Ba+1Ts6wbWBbp96i6yyvApbN7hoyREYeqccDeRoTsBjRFJ9VS49golwZaVeneU4nj9JTV37dZNpvUwr7Z0t/tSOq/k4ucBTN5ba8AQ==)

# Expected result
The new value of bounds'width was expected be set successfully.

**Comment by wiskewu** [comment]
Addtionally, on the demo above, the bounds'x property was calculated to 50 from 0 while the width was still 0.

**Comment by r00sn** [comment]
<img width="259" alt="Screen Shot 2021-07-28 at 9 33 40 am" src="https://user-images.githubusercontent.com/53328329/127240823-641696ad-32ef-4c97-bf87-a31418653ebb.png">

Hi @wiskewu, I think x=50 is showing your path's location while the size of the rectangle is still 0 which is why it's coming up like a line. 

if you remove:
```
//item.bounds.width = 0;
//console.log(item.bounds);

```
http://sketch.paperjs.org/#V/0.12.15/S/dY/BCsIwDIZfJfSyCaOb14onX0D0qB62Nqxjs5EuMmXs3W2rBxG8hIQ///cns3D1FYUSxx5ZW1EITSbOmtzI0DFeYQsOJ9jXbOUBNdeuHTCf4aGgKuCZ6tQZtgrWVegtdq3lNMCy2pxdhMiRPfW4o4F8AGYeTRakskwRsqG7M6NMmCBXbyneQAPKgdr8ay0yP9QfX4gM2l9b+K7xWPc36hyPQp0uyws=

it comes like this with x=0 and rectangle but if you remove item.bounds.width = 100; it will create a line with 0 width and x in position 0.

**Comment by wiskewu** [comment]
Hi @r00sn, thanks to your reply. My question is, when I set `rectangle.bounds.width = 0`, and then set `rectangle.bounds.width = 100`, I wish to get result with 100 when I log `rectangle.bounds.width` on the console.

By the way, I think it'll be better if the `bounds.x` still be 0 when I get a result of line along with an area of 0. Visually it's a line but  not a valid rectangle.

**Comment by sapics** [comment]
When `rectangle.bounds.width` set to `0`, all of the information about `x-axis` are removed except `center.x`.
Thus, `The new value of bounds'width was expected be set successfully` is impossible when `width=0`.

**Comment by sapics** [comment]
Sorry, I closed this by mistake. Is it OK as answer?

**Comment by wiskewu** [comment]
@sapics Thanks of the answer. That will be ok to me.
