### ISSUE TITLE
very weird interaction with Object.prototype

### ISSUE THREAD

**Issue by bomelino** [paperjs/paper.js#2010]
# Description/Steps to reproduce

There seems to be a weird interaction when extending Object via Object.prototype and the error is very cryptic.

`Object.prototype.test = ()=>{}` - this will screw up setting positions `item.position = new Point(100,100)`

Also groups are torn apart (the children change their relative position).

The error:

>paper-full.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
 >   at t._transformCorners (paper-full.min.js:1:36192)
  >  at t._transformBounds (paper-full.min.js:1:36335)
>    at initialize.transform (paper-full.min.js:1:63262)
>    at initialize._transformContent (paper-full.min.js:1:63588)
>    at initialize.transform (paper-full.min.js:1:62920)
>    at initialize.translate (paper-full.min.js:1:62514)
>    at initialize.setPosition (paper-full.min.js:1:46884)
>    at initialize._set (paper-full.min.js:1:23158)
>    at initialize (paper-full.min.js:1:18981)
>    at HTMLDocument.<anonymous> (?editor_console=true:139:25)

# Link to reproduction test-case

https://jsfiddle.net/9o6bfpn8/6/

# Expected result

Extending Object should not have an interaction (?) or at least there should be a better error.

# Additional information

Chrome Version 107.0.5304.107

**Comment by lehni** [comment]
That's strange. I wanted to load a non-minified paper.js to debug more easily, so I changed your sketch to using this instead: 

`<script src="https://unpkg.com/paper@0.12.17/dist/paper-full.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>`

The problem then goes way… Very odd?

**Comment by lehni** [comment]
Ah I only now understand it only happens upon interaction, sorry.

**Comment by lehni** [comment]
Ok this happens because we have a few `for (var key in … )` loops that don't check for own properties, for reasons of performance, e.g. https://github.com/paperjs/paper.js/blob/77188ce229a7f275a34ec656d03a3e52058fc683/src/item/Item.js#L3643

Extending `Object.prototype` is a really bad idea and strongly discouraged. There is a reason why this bug is only now surfacing: Almost nobody does this:
http://blog.dreasgrech.com/2009/11/no-one-should-extend-objectprototype-in.html etc.

If you really need to do extend it for some obscure reason, then you can simply mark the added properties as non-enumerable. Something like this should work:

```js
Object.defineProperty(Object.prototype, test, {
  enumerable: false,
  value: ()=>{}
})
```

**Comment by bomelino** [comment]
ah, I now understand the consequences of extending object. this was a bad idea :)
no i don't really need to do this, just thought it was practical in a different project, then i included it and this weird behaviour appeared. just thought i'd let you know. maybe put i warning somewhere...
