### ISSUE TITLE
Shape union produces wrong results if points of overlapping shapes touch on horizontal lines.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#450]
I'm sorry @hkrish to report more bugs with the boolean code! Check this example, derived from #449:

```js
var path1 = new Path.Rectangle({
    point: [60, 50],
    size: [50, 50],
    fillColor: 'red',
    selected: true
});

var path2 = new Path.Rectangle({
    point: [100, 50],
    size: [50, 50],
    fillColor: 'blue',
    selected: true
});

// project.activeLayer.rotate(15);

var path3 = path1.unite(path2);
path3.fillColor = 'yellow';
path3.selected = true;
path3.position += [0, 100];
```

Resulting in:

![screen shot 2014-04-07 at 12 31 08](https://cloud.githubusercontent.com/assets/213275/2629948/d47a7d14-be3f-11e3-900f-bf6f49cd63e8.png)

Now if you uncomment that `rotate(15)`command, you get:

![screen shot 2014-04-07 at 12 31 20](https://cloud.githubusercontent.com/assets/213275/2629949/d9977b62-be3f-11e3-9417-6cf3af514148.png)

Note that there are still extra points that we could get rid off, but that I guess is fine?

http://sketch.paperjs.org/#S/lZAxT8MwEIX/yslLiojcBBSGoE5dGRCMTQeTXKnBvYvcS6tS9b9zCUqkToAn+31Pfu/ubMjt0JTm9ROl3prU1Nz074OL0DrZ5rAAwiM8692+YC2O3gPOzhWBnpY9SQmrhyyFIlunP+ref6GKxZW48SEsOXAsIYnYJKMXg36KTQkSO6zocvNYUUVj/N2f4vPsf/lvocNfCszn0Eb+UGRdLf6AT+6E0UYWJzjLi+ua91pz2JbtyCsfqveWAdopW23JCUPgYzLBsYCyvsGkt7z34pngdgErHUWHXCs0l28=

**Comment by lehni** [comment]
@hkrish isn't it strange though that the rotated paths produce the correct result? Isn't this perhaps simply an issue of horizontal paths not handled correctly?

**Comment by hkrish** [comment]
I did look at it in detail. The issue is with overlapping paths. The transformation may nudge the points just enough that the paths may not be  precisely on top of one another anymore. 

Try changing the ```rotate(15)``` to ```rotate(90)```. Now the intersecting parts are not horizontal, but the issue will reappear, since the lines are aligned again. 180 and 270 degrees does not seem to show the issue, but again we can't debug like this, the IEEE floating points have a major say in this. If you step through the code in the debugger, the boolean code makes no attempts to resolve when it reaches an overlapping section, and because of that it occationaly takes the wrong path. 

It might seem arbitrary, but a subtle difference in the slope of these curves determine which path is being taken, when we sort and choose a path to traverse at an intersection.

What we need is a conscious design choice of how the algorithm should behave. Also might need some code to identify the parts that are overlapping. This may not be the only issue when we deal with overlapping paths. So may be it is a good idea to keep this issue open for now?

**Comment by lehni** [comment]
Yes that makes a lot of sense. Do you think this is something we can address in the current implementation, as opposed to the new approach that you once mentioned?

**Comment by lehni** [comment]
Who would have thought! I managed to address these issues in the current code base, and the work in the `boolean-fix` branch has landed on `develop`! Time to test thoroughly, but I'm closing these bugs. Feel free to reopen if similar problems arise.
