### ISSUE TITLE
Curve.getIntersections() fails if curves intersect tangentially

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#565]
This is sub issue 1 of 4 for #547, only addressing problems with tangential intersections.

Curve.getIntersections() often fails to find intersections if curves intersect tangentially Here is a sample code that illustrates the issue:

<pre>
var crv1 =  new Curve(new Point(421.75945, 416.40481), new Point(-181.49299, -224.94946), new Point(44.52004, -194.13319), new Point(397.47615, 331.34712));
var crv2 =  new Curve(new Point(360.09446, 350.97254), new Point(-58.58867, -218.45806), new Point(-109.55091, -220.99561), new Point(527.83582, 416.79948));
var pth1 = new Path([crv1.segment1, crv1.segment2]);
pth1.strokeColor = "green";
var pth2 = new Path([crv2.segment1, crv2.segment2]);
pth2.strokeColor = "blue";
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = "red";
}
</pre>

Click below to open the code as a Paper.js Sketch:

http://sketch.paperjs.org/#S/nVRNU9swEP0rGp+SIRW70q60gvbQ4dQbMz0SDiaIxEOwGdvQA8N/7yqBEqf00lzij/dW72OTl6qtH3J1Vv28z+NqUy2qVXdb7p/r3qz6ZzTfjGnzL3Px1D/nWbm67Jp2nJFDGzkRLwxhsAQkOF+YD8AXFLSUXEoL88U5sokShQmEyLIDIAVgIoveY5oAfIqWYkA9RN9ZTxHdfH6+7Jftmz73L30+gIVEFJTKYFN0TFN9LJZFQizyUCyxQDhyAMkyQ8KdAx2SOExNsotWPIvbpxBTInkTeHpqvm/H3Lf12Dxn81g3venuzKroHMy4qUezqctFNoNWYJpheMp74kH2n0YvGia44Hz0gsGVw0HjQwBMIUaPEvzUiQus74UlIofIcWdaOQCRUok1uhDlyH1UQ0rSjDiKOFkYRLQpAHIC5t2LaZ9erGDCkIA8B+9VmEsWXIriI6nSGP6kc1Dgp/2JWMdOgIiLR1DJlLQDBu+8CxJVWzxSrEsEXOSqt6gwdandayIBAnhwEei4Ys0yInhdVFUsPkhJRneHPYUgwYHGNQ2Gki4LEiCmJAh7Zcy6KcLaCCY9iItPUyw+jpv3Hi/rcTO7KsXaIa8fcjvqYh3euut9OO/7/T/cwrHD2Hf3+aLbdr3yl9W6z7ldVucHg93xYDcd7D4Z7P4afLPVnf2Yq/EM+nyna53HH63u/5BXY9O1w6wM3Y+6U/Zsh1cwnOvX1x3VbnO7Hjf64ORkbl4K1OinIG+78UCwvWj61TbPCumqubaPpRj9oe/HF47i7V2z3X5I7fPtm9JX/Ze76XN9v6MN1dnV9etv

Found intersections are marked with a red dot. As you can see below, one of the two intersections is not found.

![crvs](https://cloud.githubusercontent.com/assets/2122773/5086706/166ce216-6f20-11e4-9642-184a83195c16.png)

**Comment by iconexperience** [comment]
Thanks for implementing the fix. If I can help with any of the other issues, please let me know. I will make time for that.

**Comment by lehni** [comment]
You're welcome! It'd be great to have you on board with this, since it's all a bit above my head and @hkrish has been too busy to look into it all lately... One really helpful resource to test against is his separate suite of boolean tests that I just pushed to a new repository here: https://github.com/paperjs/boolean-test

You need a symlink from paperjs -> your paper.js repository, and then you can run unit tests that compare the outcome of paper.js' boolean operations with the ones in Java through Java2D, by comparing rendered pixels. Give it a go and don't hesitate to ask if it doesn't work for you. I have a couple of more changes to push in the coming hour or so.

**Comment by hkrish** [comment]
Hello guys,

Regarding many of the discussions happened around the intersection code in paper.js, I did not feel right about replying to without explaining *in detail*, what the algorithm does, how it works, and how to measure it's performance.

So I cooked up this http://nbviewer.ipython.org/gist/hkrish/0a128f21a5b9e5a7a914, all in spirit of encouraging more hacking and more pull-requests. :)


You can view this online, however, I **highly** recommend downloading the .ipynb file (the notebookviewer has a dowload link on the menubar) and the associated source code, and running it locally, since the online version will disable all of the interactive features of the notebook.

Please proof read it and let me know any corrections, what can be improved,and if anything needs to be explained further. 

Thank you.

/hari

PS. Once it is in a good shape, we can link it somewhere more appropriate.

**Comment by iconexperience** [comment]
What a great report! I will take a look at it and try to help if I can with my limited knowledge.

**Comment by hkrish** [comment]
Thank you @iconexperience. We would definitely like your help. (and all our knowledge is limited in many ways, I wouldn't worry too much about it! :))
I am only trying to explain parts of the code that I wrote, especially regarding something like boolean operations; it's full of edge cases.

Thanks again.

**Comment by iconexperience** [comment]
Alright, here is my first remark:
Maybe you should add two sentences to help your readers understand where dmin and dmax come from.
When I tried to understand fatline clipping from the Sederberg / Nishita paper, understanding how  dmin and dmax are calculated also helped me understand bezier curves a little better. Also, the information that using the factors 3/4 or 4/9 are a good tradeoff between tight fit and inexpensive calculation made it much earier to understand that part of the algorithm.

**Comment by hkrish** [comment]
Yup. I forgot to include the details on dmin and dmax.
Thanks.
