### ISSUE TITLE
incoherent fill-rule used when building CompoundPath

### ISSUE THREAD

**Issue by louisremi** [paperjs/paper.js#590]
The default fill-rule of SVG, 'nonzero', is respected when building a CompoundPath from a single SVG path:
```javascript
var p = new CompoundPath('m 51.428571,89.50504 94.285719,-20 20,91.42857 -102.857147,17.14286 z M 200,130.43865 l 22.85715,82.85714 -97.14286,28.57143 -17.14286,-114.28571 z');
        p.fillColor = 'black';
        p.windingRule = 'nonzero';
```
[See demo](http://sketch.paperjs.org/#S/VY89T8MwEIb/yslLiuRYtmM3dqtOnZEQjJTBTQyN4pyjkFIpiP+OA2bgtnveR/fxSdANnuzIU+/n5kIoaWK79if8cBOMcAD0NzjGYYxXbB/cfNkUA2jBlDS6FtRYprnmCqxiP8TSUnKQnNrsQCm4ZGukaipqJhLdwgL3SeJUVJypymw1BJC/mqYm+1Da7FNp2EqqNO0PlULknbAUd/sTQq6RvXYhHGOIU7q/OAfX9MW//NZh2+Hb4zX41cCIi59isU//nyfv+jF2OL+T3fPL1zc=).

But when trying to build it from the two sub-path, the result is totally different:
```javascript
var p = new CompoundPath({
    fillColor: 'black',
    children: [
        new Path('m 20,35.219325 94.28572,-19.999999 20,91.428574 -102.857148,17.14285 z'),
        new Path('M 168.57143,46.647895 85.714289,43.790753 54.285715,146.64789 137.14286,158.07646 z')
    ]
});
```
[See demo](http://sketch.paperjs.org/#S/bVBNa4NAEP0rw15sYDM4+72WnnIuFHpMcjBqUNRdsbaFhvz3upHe+k4zb94HzI2FcmxYwd77ZqlaxlkV67R/lTNM8AKh+YZDHKf4Geq3cmmfbqcAK67dMBziEOcCsstQVn3Gt0PVdkM9N6GA40YkpJSHOxtB5FxqFOSl0OAVCqet4Hvy6B9IAk+oEq9gT7nAdSLlOFmkRMNPtuP/hb8CGYdJLLkyaJR1XoPTaJPPcyXR+txqCXrrJc3pTwgkt3zDSTvMrVEmNW1F51O4757X/1zmpuyn2IXlgxXH8/0X) (the shape of the path isn't the problem here, only the way it's filled)

If the first CompoundPath is exported to JSON and then re-imported in a CompoundPath, the way it is filled will also be different. Before finding a fix for this problem, I'm pretty sure that there is a workaround to achieve the same fill result as CompoundPath built from a single svg path, without actually using an svg path.

**Comment by lehni** [comment]
Yeah this has come to bite us in other places as well... We were emulating the way Illustrator handles it, but it's causing issues in multiple places. Will have to look into this properly soon.

**Comment by lehni** [comment]
@hkrish this is the problem I mentioned to you the other day... Would be great to find a solution to this that doesn't break old code...

**Comment by lehni** [comment]
@iconexperience I still would like to develop a good strategy here, since what we're currently doing is simply wrong. Would love to hear your thoughts on this, since you've been working on the new version of `reorient()`

**Comment by iconexperience** [comment]
@lehni Alright, I will look into that. A really great piece of code is IMHO the part of `resolveCrossings()` that reorients the children of the `CompoundPath`. I think as part of the solution we will have to extract that part into a separate function.

But first I will try to define what the correct behaviour of a `CompoundPath` should look like.

**Comment by lehni** [comment]
@iconexperience I've posted about this in #973, but I think it belongs here instead:

I've now split off the reorientation code from `#resolveCrossing()` back into `#reorient()`, but I have one concern:

The way `#reorient()` is currently implemented, it removes unnecessary children. This is great, and required when it's used for boolean operations in conjunction with `#resolveCrossings()`, but if we're going to remove the automatic orientation of sub-paths of a compound-path on insertion as suggested in this issue here, and recommend `#reorient()` as the new way to fix orientation (which we will), I think we can't have it remove these children by default...

I am now wondering, can we hide this behind an optional argument, and have it keep the children by default? since you wrote the method, do you think this easy to implement?

The part that would have to change if there is no sorting [is this](https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L1051):

```js
// We run through the paths from largest to smallest, meaning that for any
// current path, all potentially containing paths have already been processed
// and their orientation has been fixed. Since we want to achieve alternating
// orientation of contained paths, all we have to do is to find one include path
// that contains the current path, and then set the orientation to the opposite
// of the containing path.
```

Can the algorithm be changed to support non-sorted paths?

**Comment by iconexperience** [comment]
@lehni I was thinking about this already but this makes my head spin. I do not think it works without reordering, but as you know me, I need a visual example. What we can do of course is to keep the paths instead of deleting them. This should not change the paths appearance.

I need to think more about this, but I have to finish for today.

**Comment by lehni** [comment]
@iconexperience no rush with this, I just wanted to launch the discussion... Thanks for getting back!

**Comment by lehni** [comment]
@iconexperience just realized that I posted a comment about this in a wrong issue yesterday. Here it is, for reference: 

Or maybe I'm thinking about this all wrong... What we maybe want is this:

The current `reorient()` is quite destructive, it removes children when the `nonzero` fill-rule applies, and it sorts the children according to their area. Perhaps we wan to keep it as part of `resolveCrossings()` like we had it, but behind a switch. 

And then we could offer a new `reorient()`, which keeps the order of children intact (after all, the user inserted them in this way), but figures out what to do with their orientation, perhaps based on the same algorithm that the current `reorient()` uses. Underneath it could be same code, even.

For example, what happens if we keep the code but don't sort by area first? Can you help me figure a good approach out here?

**Comment by lehni** [comment]
@iconexperience I believe I have a fairly simple solution:

- We keep sorting the paths according to their area, and we don't modify your algorithm
- If the caller doesn't wish for the resulting sub-paths to be sorted from largest to smallest in the end, we store their original index first, and sort the result to preserve that sequence at the end.

We could also decide to always do that, as I think it's good practice to keep that order of the processed data and only do what the function actually says: `reorient()` (and optionally discard of unnecessary paths). The compound-paths don't mind about the sequence when they're drawn, nor do the boolean operations, and the sorting is then only an internal detail of the algorithm.

Do you agree?

I tested with your code below, and it still looks right.

```js
var cp = new CompoundPath();
cp.windingRule = "nonzero";  // change to "evenodd" for comparison
cp.fillColor = "palegoldenrod";
cp.strokeColor = "white";

for (var i = 0; i < 20; i++) {
    var radius = 180 - 8 * i;
    var c = new Path.Circle(0, 0, radius);
    cp.addChild(c);
    c.setClockwise(Math.random() > 0.5);

    var c = new Path.Circle(0, 400, radius);
    cp.addChild(c);
    c.setClockwise(Math.random() > 0.5);
}

var cp2 = cp.clone().reorient(false);
cp2.fillColor = "paleturquoise";
cp2.translate(400, 0);

view.center = cp.bounds.center.add(cp2.bounds.center).divide(2)
```

**Comment by lehni** [comment]
Uh oh, I was a little too fast: The boolean ops do seem to mind in some edge cases from @hkrish's test suite with the typography glyphs. I'm not sure why, and wether that's a boolean op bug? I will investigate.

**Comment by lehni** [comment]
@iconexperience should I investigate this propsoal further or do you already have a better idea for the algorithm anyway? : )

**Comment by iconexperience** [comment]
Keeping the order may work, but I am a bit worried about the orientation of the compound path. What should `isClockwise()` return, if the paths are not sorted in any way. IMHO the orientation of a compound path only makes sense if the bottom paths have the same orientation, otherwise it is just an arbitrary value and we could as well use a random value :) Maybe we should investigate if a `CompoundPath` should really have an orientation, or if that only makes sense for simple `Path` objects.

**Comment by lehni** [comment]
@iconexperiencey yes, that's exactly what my investigation of said case just turned out!

Currently, `CompoundPath#isClockwise()` returns the orientation of the first child. And as you say, this only works when we keep sorting. so what if `reorient()` gets an `options` parameter:

- `options.sort`: Sorts the resulting sub-paths according to their area, default: `false`
- `options.reduce`: Removes sub-paths that don't change the visual appearance, default: `false`

And in boolean operations, we pass `true` for both. I like it.

**Comment by lehni** [comment]
Forgot to say: If somebody builds a compound path by hand, and calls `reorient()` on it without any of these options to just fix the orientation of the constructed sub-paths, it's that person's responsibility to build the path int he right sequence. I think that's only fair, and what I would expect from such a function to perform.

**Comment by lehni** [comment]
Here the code of the mentioned case, for reference:
```js
var g = PathItem.create('M316.6,266.4Q332.6,266.4,343.8,272.8Q355,279.2,362,289.8Q369,300.4,372.2,313.6Q375.4,326.8,375.4,340.4Q375.4,354.8,372,369.2Q368.6,383.6,361.4,395Q354.2,406.4,342.4,413.4Q330.6,420.4,313.8,420.4Q297,420.4,285.8,413.4Q274.6,406.4,267.8,395Q261,383.6,258.2,369.6Q255.4,355.6,255.4,341.6Q255.4,326.8,258.8,313.2Q262.2,299.6,269.6,289.2Q277,278.8,288.6,272.6Q300.2,266.4,316.6,266.4Z M315,236.4Q288.2,236.4,269.8,246.6Q251.4,256.8,240.2,272.6Q229,288.4,224.2,307.8Q219.4,327.2,219.4,345.6Q219.4,366.8,225.2,385.8Q231,404.8,242.6,419Q254.2,433.2,271.4,441.6Q288.6,450,311.8,450Q331.8,450,349.6,441Q367.4,432,376.2,412.8L377,412.8L377,426.4Q377,443.6,373.6,458Q370.2,472.4,362.6,482.6Q355,492.8,343.4,498.6Q331.8,504.4,315,504.4Q306.6,504.4,297.4,502.6Q288.2,500.8,280.4,496.8Q272.6,492.8,267.2,486.4Q261.8,480,261.4,470.8L227.4,470.8Q228.2,487.6,236.2,499.2Q244.2,510.8,256.4,518Q268.6,525.2,283.6,528.4Q298.6,531.6,313,531.6Q362.6,531.6,385.8,506.4Q409,481.2,409,430.4L409,241.2L377,241.2L377,270.8L376.6,270.8Q367.4,253.6,351,245Q334.6,236.4,315,236.4Z');
var u = PathItem.create('M253,316.74Q242.25,316.74,232.77,318.39Q218.77,320.83,208.21,328.52Q197.65,336.21,191.32,349.4Q185,362.6,183.59,382.95Q182.01,405.69,189.83,423.08Q197.64,440.46,216.05,452.56L215.99,453.36L183.27,451.09L181.06,483.01L387.37,497.31L389.72,463.39L273.2,455.32Q259.23,454.35,247.72,449.74Q236.21,445.14,227.96,436.95Q219.7,428.76,215.7,417.05Q211.7,405.35,212.78,389.78Q214.14,370.23,226.09,359.83Q236.68,350.61,252.94,350.61Q255.02,350.61,257.19,350.76L396.85,360.44L399.2,326.52L263.53,317.12Q258.12,316.74,253,316.74Z');
g.fillColor = 'red';
console.log(g.children[0].area, g.children[1].area);
g.reorient();
console.log(g.children[0].area, g.children[1].area);
u.fillColor = 'blue';
var res = g.unite(u); 
res.fillColor = 'yellow';
```

**Comment by lehni** [comment]
Hmm, I'm starting to understand this excluding thing better: It only is performed when processing a compound-path with 'nonzero' fill rule. The issue is a compound-path with this fill rule is processed and reduction is not to occur, than nothing can actually be done. so maybe it's save to say that this reduction always happens when called on a nonzero path? And on an even-odd path, it figures out orientation according to what you'd expect based on nesting?

**Comment by lehni** [comment]
@iconexperience note also that if a compound-path has the `'nonzero'` fill rule and intersecting sub-paths, than this exclusion will lead to a destructive change, that is wrong. I am still not sure how to handle this best, if `reorient()` is to be a utility function exposed in the API. What are your thoughts on this? Example:

```js

var circle1 = new Path.Circle({
    center: [100, 100],
    radius: 50
});

var circle2 = new Path.Circle({
    center: [120, 100],
    radius: 50
});

var circles = new CompoundPath({
    children: [circle1, circle2],
    fillRule: 'nonzero',
    fillColor: 'red'
});

// circles.reorient();
```
Due to the intersections, this wrongly gets reduced from:

<img width="149" alt="screen shot 2016-07-21 at 13 40 37" src="https://cloud.githubusercontent.com/assets/213275/17021522/c1e38514-4f48-11e6-8717-e6088c13bfc6.png">

to:

<img width="116" alt="screen shot 2016-07-21 at 13 40 42" src="https://cloud.githubusercontent.com/assets/213275/17021524/c44c98ae-4f48-11e6-813e-086303413b49.png">

**Comment by iconexperience** [comment]
I think reorient was never meant to work with crossing sub paths and I have strong doubts that it will ever work. One reason is that we currently take an interior point of a path and check if this point is inside the another path. With crossing paths, the result can be either way, depending on where the point is located. So having non-crossing paths should probably be a prerequisite for using `reorient()`

**Comment by lehni** [comment]
Yes I agree. Maybe what I meant to ask is this: For `nonzero` fill-rule (the default), can there be an implementation that does 'something' but doesn't remove paths? I guess not?

On other news: I'm working on removing the annoying handling of auto-clockwise, have moved `isClockwise()` to `PathItem`, and have changed `reorient()` to always preserve sequence, and I'm seeing a whole lot of simplification without much new issues anywhere, so definitely a good sign.

So the `sort` parameter for `reorient()` will disappear again, but now I'm thinking it could be nice to ask reorient() to apply the `evenodd` fill-rule even if the path is actually drawn with `nonzero`.  This could be useful, I think. So we could have that as an optional parameter, with default to the path's own fill-rule.

**Comment by lehni** [comment]
Ok, now I think I have figured out the API version of `reorient()`:

I think what people will mostly when they call it, is the `evenodd` behavior. So we default to that, and have an optional `nonZero` parameter that can be set to true, if they want nonZero. The boolean code then always passes `path.fillRule == 'nonzero'`.

Sounds good?

**Comment by iconexperience** [comment]
Yep, that sounds reasonable.

**Comment by lehni** [comment]
@iconexperience I didn't think the day would come so quickly for a0417040f8d2b8518a3c44915ca1aa1c99c8d784 to land. But it made more and more sense to do it now for me too. I think this means the next version is going to be `v1.0.0`! After all these years!
: )

**Comment by iconexperience** [comment]
You have written all that today? That's pretty amazing. Please give me time until tomorror to take a look at that. I need to solve some non-paper issues at the moment.

**Comment by lehni** [comment]
@iconexperience yes that just tumbled out in the last hour : )
