### ISSUE TITLE
Shape "guide" property is not suppressing mouse events

### ISSUE THREAD

**Issue by piotrwitek** [paperjs/paper.js#608]
Hi,
I noticed that shape "guide" property is not working as expected when set to true.
Mouse Events are triggered as they shouldn't.
I have tested with Shape.Circle on mouse events (enter/drag).
But I can assume that all of them will have the same issue and the problem is related with guide property check somewhere.

**Comment by lehni** [comment]
Hmm I can't really replicate this anymore. It might have been fixed in the meantime?

http://sketch.paperjs.org/#S/jVBNi8JADP0rYS6tUKR7nWVPZW+7J4/qYXYadTAmMh8Vkf53Z9rC4s0cQvLe472Qh2JzQaXV5ozRnlSjrPRlH4yHcDJXhC9gvMGmzOvOeUtYP3YMuSxyRK9h+9G2DeS2b2bCm96loAu0IAdH1AlJVld3JJJbtTDH5HrUEH3CBRH+lRTwezY/JLbRCdc45LgVLNlTvnAQwjXJsa6mW6rV50yPr14/aAZ834uK/N9rx2OZ83P+PJrzVRzHoPR2Pz4B

**Comment by lehni** [comment]
But there is one problem though. Hit-testing that only guide results in the layer being selected, and that triggers an error that I fixed in d9c9b3d1a271496ee79bc398cdcbd4f0a6c1bbc7. But the layer shouldn't be selected to begin with.

**Comment by piotrwitek** [comment]
@lehni  it was v0.9.21, so might be fixed already, I will try to do simple test with older version later today and I'll put the results here
