### ISSUE TITLE
hitTest options are incorrectly defaulted when an options argument is passed

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#619]
If an options object is passed to hitTest then any options that normally default to true but are not specified in the options object are defaulted to false.

I'm documenting the bug that pull request #616 fixes.

**Comment by lehni** [comment]
That's not a bug actually, but by design. The idea was that if you provide an option object, you want to fine tune these values. If you don't, it uses the defaults.

We can discuss changing this, but it will affect existing code, so I am very reluctant.
Also, the fix isn't really the best way to do what you'd like to achieve, since `new Base(obj1, obj2)` produces the result of first mixing `obj1`into the resulting object, then `obj2`, you could simply do:

```js
return new Base({
    type: null,
    tolerance: paper.settings.hitTolerance,
    fill: true,
    stroke: true,
    segments: true,
    handles: false,
    ends: false,
    center: false,
    bounds: false,
    guides: false,
    selected: false
}, options);
```

**Comment by bmacnaughton** [comment]
Generally with options those that are not specified retain their default values. It puts a burden on the caller to know what all the default values are otherwise, e.g., what is `options.tolerance` and what are the boolean defaults for all the boolean values? The only way to find them is to look at the code.

I'm generally against changes that break things. And I can fix this in my own code but the code then becomes dependent on finding your default values at runtime so I'm version-independent. That's the only way for me to leave the ones I don't want to change at their default values.

Thanks for pointing out the better way to fix it. That makes a lot of sense.

**Comment by lehni** [comment]
`tolerance` is inherited from the default value, so you don't have to do anything there. The only place where inheritance doesn't happen in such a way is with `fill`, `stroke` and `segments`. These are on by default, but as soon as you provide your own options object, they are all off, so you can pick your own combo. This still make sense to me, as otherwise you'd have to turn explicitly turn off the ones that are on by default, which is also annoying. Tastes differ.

**Comment by bmacnaughton** [comment]
Documenting how it works would be a good thing. It's different than many.
