### ISSUE TITLE
Converting Shape to Path loses opacity

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#622]
[Example](http://sketch.paperjs.org/#S/TY9NC4MwDIb/SulJmYgTeunwNHYfeLQeOpdhWZcUWzaY+N9XPwaGEJInb5tk5KhfwCWvnxC6nme8o/tcv/XALtYa54FVDOHD6l47yDeWjApZtIex9kyWBrloljQphchYsXou0myVevMFyZpjEXEM7YYdGQx7rnBKTwoV7lYo4w5bmneWEJJZ8ieOvAmGkB2q+I+Yx7a7dqCrDn18Ea+7DaCfy0jPZdNOPw==), When you convert a Shape to a Path using `Shape#toPath()` The `fillColor` loses it's alpha channel.

**Comment by georeith** [comment]
Ignore... further testing made me realise it was creating a copy of the object and placing it on top of it, it appears that the first boolean argument to `Shape#toPath()` determines whether to insert the copy or not.

**Comment by georeith** [comment]
Ok... I'm not going mad. It's not the `fillColor` that it loses... it doesn't copy `opacity` across. [See example](http://sketch.paperjs.org/#S/VY/BCsIwDIZfJfS04SjdoJfKTuJd2HHdoc7KirUta1F07N1ttwkacki+/CR/JmTEXSKGmpsM/YAK1NtL6h9iBKm1cl5CDUY+oRmEk/i4smziBmJcldYHq+3IFs1SZhWlBZCYebGqvHpLBm1JIywJ6TbsrDIhcfLPrRO9Ci8GBFNu5nzPDTc/hqroaCtxsCcRhixpvlPsrFdBWQO7GtoqLSddnMfnzqMUt+WsR6zt5g8=)

**Comment by lehni** [comment]
Good catch! That's because right now, only the style gets copied over, while many more attribute should be... And opacity is not yet part of style, for this to happen, we need to first implement the style refactoring as outlined [here](https://groups.google.com/forum/#!searchin/paperjs/style$20change/paperjs/pJzsEYv2W7M/_njgiP2kpy8J)
