### ISSUE TITLE
ES6 Inheritance

### ISSUE THREAD

**Issue by nvartolomei** [paperjs/paper.js#640]
Hello,

can anyone help me extending Paper.Tool using ES6 syntax?

instead of
```
var tool = new Paper.Tool();
tool.onMouseDown = function() {}
tool.activate();
```

I want to do the following:
```
class PenTool extends Paper.Tool {
  onMouseDown() {}
}
```
and then
```
var tool = new PenTool();
tool.activate();
```

But this doesn't work :/

**Comment by lehni** [comment]
Could you provide some information about the context of this? In which environment are you using ES6 features?

**Comment by nvartolomei** [comment]
In a browser using Babel transpiler.

**Comment by lehni** [comment]
Could you share the resulting code of the transpilation, or a test-case for me to replicate? I've never worked this way. Thanks.

**Comment by lehni** [comment]
OK, this wouldn't even work the normal JS way. The problem is that onMouseDown is not a member function in a ES6 class sense, it's a property that you set. You also don't have to create a subclass of Tool, you simply create an instance of it:

    var tool = new  Tool();
    tool.onMouseDown = function() {
    };

This is internally redirecting to:

    var tool = new  Tool();
    tool.on('mousedown', function() {
    });

You can also use the object literal constructor, which gets the closest do your desired syntax:

    var tool = new  Tool({
        onMouseDown: function() {
        }   
    });
