### ISSUE TITLE
Why is there a third parameter in Curve.divide() and why doesn't Curve.subdivide() handle linear curves correctly?

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#652]
This is not really a bug report, but rather a request for information why `Curve.divide()` was implemented in this specific way.

The function `Curve.divide()` has a third parameter called `ignoreLinear`. The only place where this is used seems to be in `splitPath()`, which again is used by the boolean operations.

Setting this parameter to true makes the function return subcurves of a linear curve that may have handles of a non-zero length. In other words, the returned subcurves of a linear curve may be non-linear. I find this behaviour strange, because I would expect that subdivisions of a linear curve to be linear, too, without exceptions.

Also, currently the function `Curve.subdivide()`, which is called by `Curve.divide()` may return non-linear subdivisions for a linear curve, as this sketch shows:

http://sketch.paperjs.org/#S/nZK9TsUwDIVfxcrUiqqKufxIRYiBlQ2JJemQ20SX6JYEJW0ZEO+OU4RwBQywxMdxbJ1PzqsI5smJTtwf3TQ8ikYM0ZZ8MQmGtCBcQ3AvcDunxVUKpWyAjr4BRWoTd2sNZV9f6TDEkOPo2jEeKi3WQT6DFnACVclan+98cCZVNdzQPVU6CiFOdNb0SotxrVNG43QofqxfMvlZvbR53lPurfuYd3DTgxlnl6v6q4EqVm4Iyggle1Ucf2pk+pTpHdNnTJ8zfcH05c/k5ICjW/kv9tKJ31GQoSBDQYaCDAUZCjIUZCj4O8p2i/bva6QPtk/OHJ+jD1MWnerf3gE=

To me it seems like this behaviour has been implemented intentionally. But why? Simply making sure that `Curve.subdivide()` returns linear subdivisions for linear curves would make life much easier is many cases, but does it breaks anything in other cases?

Or in other words, why can't we simply change the implementation of `Curve.subdivide()` to return linear subdivisions of linear curves, and get rid of the third parameter in `Curve.divide()`?

**Comment by lehni** [comment]
We need to ask @hkrish again for why we introduced `ignoreLinear` as an internal parameter for boolean operations. I remember it was crucial for the operations to work correctly.  I shall rename the parameter to `_ignoreLinear` to reflect the fact it's meant for internal use only.

As for why splitting linear curves sometimes produce non-linear subdivisions, that sure sounds like a bug to me.

**Comment by lehni** [comment]
Oh wait... You're calling Curve.subdivide() on a values array. That's never returning linear curves, simply because of the way Casteljau's algorithm works. It has something to do with bezier curve tension, which is not linear along curve time, even for linear curves. If you look at Curve#divide(), you'll see that the handling of linear curves happens there. Is this a problem?

**Comment by iconexperience** [comment]
The reason I found this issue is that I am currently working on the `Curve.getOverlap()` function for #648 and the API should look like this:

`getOverlap(v1, v2)`, return type can be a curve, a curve's value set, or two CurveLocation objects

This function splits the curve's values using `Curve.subdivide()`, otherwise I would have to convert to `Curve`objects and then use `divide()`. The problem is that if I have two overlapping linear curves, I will get a non-linear curve as the overlapping part, which is not correct.

I can certainly sort this out, but I was wondering if it wouldn't be better for the internal structure if `subdivide()` checked for linear cases and returned linear subdivisions for these cases. But then I found the third parameter and thought that there must be some intention behind this behaviour.

Anyway, I am currently in touch with @hkrish on the overlapping issue. Therefore I will ask him directly about this.

**Comment by iconexperience** [comment]
@lehni After closely looking at the subdivision function again I had a moment of enlightenment. 

I was always convinced that the subdivisions of a linear curve not being linear was just the result of a rounding error. Wow, I was absolutely wrong the whole time.

Thanks!

**Comment by hkrish** [comment]
@iconexperience  Great that you have cleared this out.

The thing is, linear cubic bezier curves are curves with **control points equally spaced along its length**   
i.e. for a horizontal curve, the control points has to be at [0, 1/3, 2/3, 1]. Only then, the curve is linear in the ***true*** sense of the word (that is, not just on the screen after rendering, but parametrically linear as well). 

[sketch.paperjs/demo](http://sketch.paperjs.org/#S/nVdtb9pIEP4rIz4UOwGHl/RLaKTr5So1Uq6JlEhXCfJhsRd7i9k1u+sEi+a/38waYxvo9VpLLMvMeN525tlh25FsxTtXncclt2HS6XVCFdHvmXxhGqzO+Z2QnOkblSoN19BVmsmYd3szCfhkLOP6QMKqFbOqkpBKHvDnKQuX3clMljZC/TJEsuSvcJPrF+5Nh4NBD3AJ3j/3YIr7QfN7XHP9vZKM2YS0hKPMI4Vtzgg5TiIIUyW5R1xHDyxGY1JmuefUDvyZXLElf9rH7ZVyIXlmpoOdyUizV6/czuTFBbB8E7jNdrsl0iKXoRVKlv74sC1zobnNtXShPqBaLwwMj1dc2mEP9vsR6X1raSnNVVpcVIZC0uobD23AUOqF37GC6yBMRBppLnfZpyclUROkXMY2mZT0cl0o7ZE2gRKDCX59gHQC5+dib6uyFzodU/FcZ6JhgR5j6XBnnS/KQupSN+tMahHMzb1MCwgTHi4N2ITDQmhjwenrAWdh4s4IhAGTZ5kyPAKrIGEvHBS9iidXStdaxQI8YRqnFfr+9rRfJHTKMVfFLjJji5TjqtWSV8V60ACN996Ap4Y7D8JAmJ39H5p3jRJ8w9jIyq87cthox55s/6+qdkc2FdXbenes5x8R4TFdw/vJodQiT9PikadYlHh4ZfYmp5Q6bNk1/YMS0j7xjW20Q5AREc6hHRM9tdRoJ9WHwxd9uIAR0gkzRmXPVq/b4FturFiIkLnWQjwK8UWuuy2hUCFNkosY88kQqCe/vpgnL0TYIDODyszbrn0vzmbyHmtWLVy5rxRWu8xXXKNtzBNoNUdX4JUVVOeuMaicXAQGmMZqV2lZKNQUVs1kqFZZbrnThwKs0m21QFTGusKOXmHq5wWRV4FzyCKgSVhotQK4SViGwfbHY/gD/uQsx1TkKdwg6F/BHWeRkDE8aBVrtkJPDXzaZCkTEj6rV3hKeIGLkEunF6mpMNmV++FFHOHKOdWv3fayDWQFrDewxng3oAu/kULvGrwz8PqAUnrj047ECt/f0dd7elbSfcTns4sGMgpzUxnzsh6se6BbOPnp4fH27v4LnuOQ94ejSQuHPc/Lgg3WiQ7QClpcB4X7RR70kb1ucbOa6yNS7lQfg7Uw9nHtvGm5Em3Qi1IjWm2gZ1Q4RuEYRdtFfOmMlnOSwl0xaRTXRwOFyiFkEgxHDH0VNlG5BQaLlMXgYbeHCKt4pH5ZXnS4WGHMwQ/V1ExSi2It1mVGTGuxlObCIvjqiOsesJQ0x0kPbmEl4sTCHAvQifANi2OusZtkHJBnH1OjsPpQFTmGciqzYiUQzntkXHKqTx4cHWQLxVt3nbvYD1q8kb9s1OYnTEYpv88JP7JhU/CyKTg6VjRu80tFt5L0XDbkThdVDQ9VebWKE6/4bISfSx/evYMj1rhi1cr+xtswYHPjVRXlVFBlVgTSN24W4/HocDDN/GJmf5YwyryHUli5QwLd8WE2+9lxehoGDbefq9PCcCoEbZjcS9xKD2M9ORpVMBxt8FPsI3R9hcv374TOk0bY7vraT2F+0+mfZASHKLqMh0HM7V94CkyG/OhGqsKohyxRzlcfroe4nl8PgsH71oiVOauo012GH60neu7ybN5cGVVDFHlTBwcEIRTcOU5tZ+TWs7+/fSrpU5d/PX3XHrbzEVCpeFOM0cGOM0Nz956AC9pz5Mq/H1qLNS+6k98yswvPhfYrZupzPp4wWkG4vxkRwe6wnhF+Oh80Z4Pu1z31v0yRgV00aPM3TdnuHvov4O0Nd/hnbY7X7bIcGDpX0+e3fwE=)

So if we have such a true linear curve, and we want to divide it at t=0.5, we can just linearly interpolate and find the point as you would normally expect.

So the real issue is with the way paperjs always handled linear curves, since, we think of control vertices as handles for respective segments, it seems natural (also what a artist/designer would do in Adobe Illustrator) to keep the length of handles **0**, if it is a linear segment. It works, but only when we draw it on screen, for parametric purposes (for pretty much all the relevant algorithms) this curve is far from linear. There is only one parametric cubic linear curve as you can see in the sketch.

This usually haven't made much of an issue because, for most purposes the ***zero handles*** approach works --even when you want to divide the curve **once**. Besides, *isLinear* works very well if we need to compare the location of handles to 0.

But when you want to slice a linear curve at **multiple** locations, like we have to in Boolean code, we need **true linear** curves. One very important property is that if we subdivide **true linear** curves, the resulting straight line curves also will be true linear (ie, the control points spaced at t = {0, 1/3, 2/3, 1} ).

That is why we introduced the ignore linear parameter. If you look at [Curve.js#L349](https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L349), all it is doing is *negating the isLinear check* that Subdivide function used to have so that, it would actually record the handles. Subdivide used to skip this step if the curve is linear, here [Curve.js#L354](https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L354).

The reason we want to have the handles set back to the results of subdivision is that, we might want to divide it again (as it is a common case in boolean ops [PathItem.Boolean.js#L222](https://github.com/paperjs/paper.js/blob/master/src/path/PathItem.Boolean.js#L222)), and the previous division has returned a true linear curve instead of resetting their handles to 0, so we can divide the new curves again. Finally, since it's been the convention, the boolean code will reset all handles to 0 once we are done with multiple subdivision (https://github.com/paperjs/paper.js/blob/master/src/path/PathItem.Boolean.js#L241)).

Just elaborating because, this can catch you by surprise. I took a while, first time I came across this.

**Comment by iconexperience** [comment]
@hkrish Thanks, the demo is great, it made things even clearer.

If I understand correctly, the reason why you cannot set the handles to zero when slicing at multiple locations is that this would cause slicing at the wrong points, because functions like `getPointAt(t)` would return a wrong point from the second slicing on.

This probably means that I should not set the handles to zero for linear cases on the return value in my solution proposed in #648 ?

**Comment by lehni** [comment]
Where's the like button on GitHub? Super nice, @hkrish & @iconexperience : ) :+1:

**Comment by lehni** [comment]
@hkrish this has me wondering... Curve#isLinear() is a bit of a misnomer then. Should we find a term that actually describes having 0-length handles in both anchors?
Or should it also detect the case where the handles are at 1/3 and 2/3, and return true then too?

**Comment by iconexperience** [comment]
:+1: to@hkrish from me, too.

I have understood this concept thanks to the great example, but I am still wondering if it wouldn't be easier if curves with zero handles were treated as lines (and maybe rename isLinear() to isLine()). Of course you cannot apply the algorithms for cubic curves anymore (as I learned above), but the algorithms for lines are much simpler usually. For example when subdividing a line the split point is simply `P1 + t * (P2 - P1)` and the control points are the end points of the subdivisions.

I am a little afraid that I may burn my fingers with playing the devil's advocat, but I still think that a clear distinction between curves and lines (previously known as linear curves) would make sense and improve performance in many cases. Or maybe I haven't fully understood...

**Comment by hkrish** [comment]
Thanks guys.

@iconexperience you are right, when we slide a curve handle away from its true linear position (to 0 for example as in paperjs), we cannot treat that curve as linear for other algorithms; all at the same time, it is *okay* for drawing on the screen (splitting, dividing, ).

@lehniI think the current version of isLinear is okay, as long as we specify in the documentation that, this method is to called to check if the control points represent a straight line. Also we have to check if the points are collinear (not just 1/3 and 2/3, it could be anywhere on the line). I have a function to check collinearity in the sketch, it is very robust, geometrically. May be we can add that as well to the Point class? It is quite useful to be able to check it.
Then, can we add another more specific method, may be called **isLinearParametric**, that checks if the handles are at 1/3 and 2/3. This can be used internally for algorithms when we need parametric linearity, also something like **Curve.setLinearParametric** (similar to Segment.setLinear but this affects the whole curve?). 

Does this sound like a good idea?

**Comment by lehni** [comment]
@hkrish this sounds like a great idea. I'd love to see the collinearity code and add it to Point, also!

**Comment by lehni** [comment]
I am reopening this as we still need these changes to `isLinear` / `setLinear`, and a clear API around what the different versions mean.

@hkrish the current implementation of it only checks for the handles to be 0-length. I am relying on this in `path.isPolygon()` (which is also a misnomer, as it's also matching open paths).  `path.isPolygon()` is used internally to decide if a path can be exported as an SVG polygon / polyline... And I wouldn't want to export it as such if it had handles defined, even if the resulting curve appears as a line. In this situation, I'd only want to treat a curve as a line if the only given information is the coordinates of the points it passes through, as the conversion to a polygon then would mean that no information is lost.

So I think we need at least two versions:

- The current `isLinear()`, as required by `path.isPolygon()` could be replaced by `hasHandles()`, reverting its meaning (true if handles are defined, false if not). Likewise `path.isPolygon()` could then be replaced by `path.hasHandles()` or more specifically `path.hasCurveHandles()`, for internal use mostly.

- The new `isLinear()` should check for collinearity, as stated by you.

- We could introduce a new `isParametriclyLinear()`, or we could define an optional argument to `isLinear()`, called `parametric`, defaulting to `false`.

- Do we need `setParametriclyLinear()` at all?

**Comment by lehni** [comment]
@hkrish I am confused by this check in your code:

    Math.abs(distSq(p1, p2) - distSq(p2, p3)) < EPSILON

p1 and p4 are the anchor points, p2 and p3 are the (absolute) handles. Why would an equal distance between p1 -> p2 and p2 -> p3 mean it's a true (parametric) curve? that makes no sense to me?

**Comment by lehni** [comment]
@hkrish PS: We already use this approach for collinearity checks, see here:

**Comment by lehni** [comment]
I have been rethinking the naming for these methods, and propose these now:

- `isStraight()`: True for all curve that appear as a line, even if they have collinear handles defined.
- `hasHandles()`: Wether or not the curve defines handles, regardless of their collinearity.
- `isLinear()`: Returns true only if the curve is straight and has its handles at 1/3 and 2/3.

I think this is very clear and concise. The only downside is that the previous meaning of `isLinear()` shifts to `isStraight()`, but I think we can live with that in terms of API breakage.
