### ISSUE TITLE
blurred image in simples Raster

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#655]
The original image URL:
http://upload.wikimedia.org/wikipedia/en/9/95/WP1_0_Icon_small.png

With Raster it is blurred:
http://sketch.paperjs.org/#S/TY6xDoIwGIRfpemCJqbVwQGMD8BmdHAQQ2r5Aw3w/01bYDC+uy0uDjd8d5fLvTmqEXjBbz0E3fEd19QknpVjTvkAjp0ZwsKuK2y2p8pV+EuEp8lpiIWsC8EWUk52INWIxfRmhMYoQa6ViWwiCShzmR/l/XKo93WpCWs/qmEQFtvsf9iSN8EQxunZwCI0YLTXRlK8+XKgeksGg+fF4/n5Ag==

Surprisingly the same code paste into paper reference demo it is not blurred:
http://paperjs.org/reference/raster/#source

It was tested with win7+chrome. In firefox the reference demo also blurred.

**Comment by iconexperience** [comment]
The image looks blurred because the top left corner of the image is offset by half a pixel horizontally, vertically, or both.

Here are the numbers for my browser:

<pre>
image size:          63x60
view size:           959x813
view center:         x=479.5, y=406.5
top left of raster:  x=448 y=376<b>.5</b>
</pre>

Here you can test yourself:
http://sketch.paperjs.org/#S/fZDBTsMwEER/ZeVLW4FsOHBoEB+AxAG1Bw4ERa6zTa04u5btNBKIf8dJqBSkisMeZvx2PNovQbpDUYh9i8mcxK0wXI/6rAMEHRMGeALCAXaTWG8ey1DS/CIj98FgBlanlHyhVO8d61oOtrUd1lZLDo0alR+VQlJbtX1Qb6/31V31bJiq2GnnpKdmtQz2HG2yTDn6bHGQBinbE5GXIjuUjpt1KWynG4RoP7GAUsANXJplZ3OFH9OW+JT+Lzx/vcRn59pCYg8Ojwn4+Fvkb6sD91RHmbGXTM0Jl8mnPwTUrWdLKYri/eP7Bw==

Just make sure that the coordinates of the top left corner of your image are integers and the blur should disappear.

**Comment by Skalkaz** [comment]
Very true. Thank you.
