### ISSUE TITLE
Non consistent mouse event handling

### ISSUE THREAD

**Issue by eugene-rozov** [paperjs/paper.js#663]
I've encountered a bit weird issue when events attached to _Path_ items, sometimes are not triggered.
I tried both PaperScript and direct JavaScript, tested in 2 browsers: Chrome (incognito mode without plugins) and Firefox (mac os). I used the latest PaperJS release 0.9.22.

**Steps to reproduce:**
Load page. Then slowly move mouse inside the shape. If everything is ok, shape background should get green color. Reload page and try again several (5-10) times. I've noticed if bug appears, move mouse for some time around the shape and then likely shape is "fixed" and it is possible to select it again.

**The code is**
```javascript
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.9.22/paper-full.min.js"></script>
</head>
<body>
<canvas width="600" height="400" id="test-canvas">Update browser</canvas>
<script>

    function createBrokenSegment(center, distance, fillColor){
        var point = distance / (3.1415) * 2.2;
        var start = new paper.Point(center.x + distance, center.y);
        var through = new paper.Point(center.x + point, center.y - point);
        var to = new paper.Point(center.x, center.y-distance);
        var item = paper.Path.Arc(start, through, to);

        item.add(new paper.Point(center.x, center.y));
        item.closed = true;
        item.strokeColor = 'black';

        item.onMouseEnter = function() {
            this.fillColor = fillColor;
        };

        item.onClick = function() {
            this.fillColor = 'orange';
        };

        item.onMouseLeave = function() {
            this.fillColor = 'white';
        };
        return item;
    }

    window.onload = function() {
        var canvas = document.getElementById("test-canvas");
        paper.setup(canvas);
        var tool = new paper.Tool();
        createBrokenSegment(new paper.Point(200, 170), 50, 'green');
        paper.view.draw();
    }

</script>
</body>
</html>

**Comment by lehni** [comment]
A lot of work has been done on mouse-event recently. Could you check again with https://www.dropbox.com/s/nvklyibrpemsmqv/paperjs.zip?dl=0 and let me know if this is still an issue?

**Comment by eugene-rozov** [comment]
Problem still exists for me. I've used code sample from this issue, paper-full.min.js from your dropbox, checked in latest chrome for OS X. 

A bit more details on the issue: when move mouse slowly into the shape, I cannot reproduce issue. When move mouse with normal or quick speed, then bug appears very often. If bug appears (shape is not green and cursor is inside the shape), then start slowly move mouse outside the shape and when cursor be located over the border, shape becomes green. 

If I put cursor inside the shape and then refresh page (cursor is still inside the shape after refresh) — shape will not be selected even if I move cursor inside the shape. It will be selected only when I slowly move it to the shape border.

**Comment by lehni** [comment]
Yes I am seeing this now too. Also happens [on sketch](http://sketch.paperjs.org/#S/lVNbT8IwFP4rJ3vZpqPClJhgfFDimyYm+KY+lO6wNSst6TqmIfx3211gEEXtw9adfpezfu3Gk3SJ3sSb5WhY5kUeU4n7XpSSGa4kMI3U4L1WOcoZpkuUJmD2gTqChBeGSoYRLLgQUyWUDjdvEuxYUw0rxaWB2x0MLiC4JKOr0TiEM4hJfLPHWoR2WIkVrOgKNXl27NaKfMB5z60tfoY9AZNpVabZaYm6oz0fBk3lQEedkNhTB103fS43uLTslklNRu40C+pfi7oG7UQ5TsNyDEKTJPjdMeycag4TqsDEmhldYn+hMC6qOgu76s8FZbl/AGBUYBAf9aDkkyoLfHBeltfFH4TQBuqGyXhBdlE7WDdvDbbHolPBWf53PV9pKlP0f5Kre3xEusZ/aFaZZfcl3VujKbWsdW1l63ya9JU4yP/FFgK3V9/dg+PQ4uEwgtH1MIxgbGd+qhGl79gNas2xIommVdDsvr1ucyub14ew8Cav79sv)

**Comment by lehni** [comment]
Oh haha! That's s simple one:

Your path has initially no fill, so the enter / leave events only fire if you actually hit the stroke. Once you're inside, it won't trigger, because there is nothing there, except for when you already hit the stroke, then it's green and the call to `hitTest()` will hit it.

The only problem that does exist here is that when you reload and the mouse is already in the shape, there is no 'enter' event. This is easily fixed.

To fix your example, just give your shape an [initial white fill](http://sketch.paperjs.org/#S/lVPdT4MwEP9XLrxQlOE2XUxmfNDFN01M5pv60JUbNLB2KWVoFv53W74G00ztA5S7+33Qu+4dQTfozJ1lgprFju8wGdrvdS6Y5lIAU0g13iuZoFhitEGhCTMPVD6EPNNUMPRhzdN0IVOpvP2bALN2VMFWcqHhtiuDCyCXweRqMvPgDKbB9OZQayqUrRVYwJZuUQXPFt1IBR9w3lNrgp9ej0DHSuZRfJqicnTAw6iODHjkCYoDdNS66WO5xo1BN0iq4+BOMVL9mt8aNBtpMTXKIgIahuR3Ra9VqjAslRmGRkyrHPuJTNtWVb0wWXeVUpa4/YKuVTZdxCY2SGeMpkimRxaleJJ5hg/WisG100E8aPptl455NqDv9o1AeUy6SDlL/s7nSkVF1Pn9Rld5fES6w39wDo6gbN4Kda5ExWsipdWph0Omg/F4MQFiz+qna3Lc0+l47MPkeuz5MDM7N1KIwrXoumrHsQhCRQtSn765jStDm1Qzmjnz1/fyCw==).

**Comment by eugene-rozov** [comment]
Indeed :)

**Comment by lehni** [comment]
Actually, there is no fix for the initial `mouseenter` before moving, because there is no way in browsers to know where the mouse is until we get the first mouse event. Closing this!
