### ISSUE TITLE
circle.split fails when splitting across segment points

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#679]
I am splitting a circle into a set of arcs. To do so I use circle.getPointAt with the appropriate length to split the circle into evenly sized arcs. I then use circle.getLocationOf with each of the values returned by getPointAt to get the location to split the circle. Whenever the arcs crosses one of the segment points of the circle split makes circle zero length instead of the arc.

This worked in 9.20 and stopped working in 9.21.

It's confusing to describe but here's a sketch that illustrates the problem (I updated the link as I made a few edits after I originally pasted it):

http://sketch.paperjs.org/#S/bVTBbqMwEP2VEZfABpFEK+2hLIeo15VaqceSg+MMYIWMkXEaVVX+fT3YsLCNL2D7zZs3bwa+IhIXjJ6itzNa2URpJPWJ9yVJZWSLUADhDV6FbbLn4ST+UHjLJJJFk8Juu03yEZz11ugzPutWGxe4OrZCnlfuuqTqStIqTdA3+vaqFdk+7oZHCpLxCXyVBG5VLjb+EAaUo9jm7vEbPDJrkWrbuKP1eoLzYrR8oNSHvatDCj9Z5YiXWaXadpQ5pA+395LuLJcZe6w7vg6lYX1BFnERXTxWE+Okw6C9GgLMhqSO7p4w0axc5kthZfC0SgZPNhug6+WIBnQFwsgerIa+a5UNScHF6ZJoz3cF/Fo6WaN9a5XEQE8pdK72SRCX4A0IzuyNEZ8xrXejFY+cpu/uTi46FGfIXOIh597Gw9635YfaUDK5OAukIdC/bw/5wi5/HEzv2e7/q+La0+AHC58bynbWBpGCoXNrOI49YVCIHotyvusOKRz7s7HL7H4cNo7lj5aCGV8ql82pTx56txu8Kx6Z53L5jqKQDTfZ9RS49OX0tlr+G7VvedVhPr2MN3gRihTVswEdpDuiOVZVMFbjuwRF4Xq9kMjLNkbfoIwCaAvCgirKCNag8iV0s5Gaes2Muo4fh8wl3Gff3fhLmeTni4FZEp80IdyU42ba1LMOgzK11w/HrMW5+4MdDYqzH6zo6f1w/ws=

if nArcs is set to 4 or any mulltiple of 4 (the number of segments in the circle) then it completes. But if nArcs is set to anything else then it fails when the arc crosses a segment point.

**Comment by iconexperience** [comment]
You can simplify your sketch by simply running through all split points and trying to find the location of each point.:
http://sketch.paperjs.org/#S/bVC7bsMwDPwVQpNdG34sHZx6CLoWaICMVQdFpW0hCmXISjIE/vdSQlJkKBeC4t3pjjdB6oSiE/sjBj2JUmj3E2dtvLYIPRBeYafCVL2nl+xi8FpppIC+hLZp8o2kugY6nw7owQ2gvF4gOFhmawLcdQwFJ4m2cdfDK3MkDWfSwTgCw1oq4N4ajTvH0CWjEmb+NIebJOAanIfsojwYpjcbbm9A3IriDxJr5m3kVSOGpLQNWZot0himF1NT9PuAW6efCB9Oq+jnc8jmZ5R2tDiLlXVjJoXppYCCDRQgRQdpYJ0HYZW0xnD/ZYrpy/tF8nQCSXzxg0d1nBNGdF+ibcX3+gs=

As you can see in the output, `path.getLocationOf()` does not return a `CurveLocation` object starting at index 2. 

If you look at the code of `path.getLocationOf()` it relies on `curve.getLocationOf()` to return `false`, `null` or `undefined` if the point is not on the curve. But as described in issue #660  `curve.getLocationOf()` returns an object (but not a `CurveLocation`) in this case.

Believe it or not, your issue is actually a duplicate (although on a higher level) of #660, which should already be fixed on the develop-branch.

**Comment by bmacnaughton** [comment]
Thanks for simplifying it. The code started out duplicating what I was doing in the particular application. In that I need the slice points to apply to  multiple cloned circles, so the structure is a bit leftover. I was also stepping through the code and found that when Curve.getParameterOf is called from getLocationOf in this situation it returns null. But getLocationAt just checks offset for being >= 0 and <= 1 and then creates a CurveLocation with a null offset. But it's a bit more complicated to fix - just returning a null from getLocationAt creates other problems.

Any knowledge of the stability of the develop branch?

**Comment by bmacnaughton** [comment]
Thanks. I've taken the changes from Curve.js in the develop branch into my local copy of v0.9.22 and things are back to working again.

**Comment by bmacnaughton** [comment]
This is fixed in develop-branch. Same problem as #660.
