### ISSUE TITLE
Slow performance when adding more than 100 elements

### ISSUE THREAD

**Issue by franverona** [paperjs/paper.js#693]
Hello team,

I'm currently developing a personal project using Paper.js, and I noticed that adding more than 100 elements creates a huge lag.

I created a simple example to prove this behaviour. This example automatically creates 200 elements (one every 10 ms) with 5 random segments each one.

You can give it a try here: http://sketch.paperjs.org/#S/7ZMxa8MwEIX/yuEOlmsj3AwdbDJ1KrRQ6NAhyaDKl1iNLBlJsSnB/71SYseBQjt1q6bT07t7cHw6Roo1GBXR6x4dr6Ms4roK944ZcKJBC0vIy7VZq6AI5dB0THqxF6rSPbXoHkeRbA+KO6EVkASOoQX8CW0tc7VvUdjDiy/J5RHA4q5B5WwBq1mEs1X7OPLsG+hWam3OpWE+t/EJt3CX53kCKeQZ/OC6H01JBn+e8B/wW8DmKsE6o/f4oKU2BcQ3flD87fVNVK4uYDHpQ1JO5QnPNL3cxRbIiOwSFiHwirMRVy6RmQuwE87zzGEqWqM/kDvaCezpoa2YQzLbuFZWS6RS78jkZJ79Dp/YJxrKayErg4pKVDvPfgoxoMQT6XESpgyZ31xS+g/3bpDt27BmGxWrzfAF

Take a look to console. At the beginning all works great, but at 100th element (more or less) things start to get laggy.

I hope someone can provide info about this issue.

Best regards,

Fran

**Comment by franverona** [comment]
Ok, problem seems to be project.view.update() function. If I execute it after each addition, it takes more and more with each new element added.

Big problem for drawing application that needs to constantly update when user is drawing elements.

**Comment by franverona** [comment]
Can someone provide any help to improve canvas refreshing when canvas has more than 100 elements and need to execute 'project.view.update()'?

**Comment by pyblendnet-js** [comment]
hi - have you fixed it already?  I tried your jsfiddle and it got to a 1000 elements in a couple of seconds. 
I was looking at the jsfiddle on firefox using windows 8.0 on a Intel i7.
The following is probably not relevant, but in my application I used script to create a backdrop with a couple of thousand circles that really slowed things down.  To speed things up again, I rasterize this backdrop and then delete the circles and showed the backdrop as an image.  Full speed ahead.

**Comment by franverona** [comment]
Hi pyblendnet-js,

Thanks for you answer. PC specifications are involved on Paper.js performance as you pointed, and I did a few days ago some test with different hardware configurations and this thesis was proved.

The problem is not this specific test where all elements are added one after each one. The real problem is that my users are going to draw in real time like many of the examples on Paper.js web. With this lag issue, they won't be able to see their draw in real time because of continous project.view.update() executions. Well, they are going to see some draw, but with huge lag.

Your solution is good if you have some "Loading, please wait" process and then PUF, all is displayed. It isn't applicable in my case, and lag issues still remains. I hope Paper.js main developers could drop us a message.

Regards,

Fran

**Comment by franverona** [comment]
Hi pyblendnet-js,

Thanks for you answer. PC specifications are involved on Paper.js performance as you pointed, and I did a few days ago some test with different hardware configurations and this thesis was proved.

The problem is not this specific test where all elements are added one after each one. The real problem is that my users are going to draw in real time like many of the examples on Paper.js web. With this lag issue, they won't be able to see their draw in real time because of continous project.view.update() executions. Well, they are going to see some draw, but with huge lag.

Your solution is good if you have some "Loading, please wait" process and then PUF, all is displayed. It isn't applicable in my case, and lag issues still remains. I hope Paper.js main developers could drop us a message.

Regards,

Fran

**Comment by bartosik-desy** [comment]
I believe this issue is first of all related to the nature of Canvas, which is used as backend in Paper.js. Redrawing all the elements every time is difficult and will always be. I see two options to improve this situation:
 **Difficult:** Make Paper.js intelligently determine the area of the canvas that has changed since last `project.view.update()` and redraw only this area. *It is not really clear to me how exactly this can be implemented efficiently.*
 **Easier:** In case users are not going to erase any parts of the canvas, but only draw on top of it, you can create a second **background canvas** under the one used by **Paper.js**, and copy the state of the original canvas to the background one after every e.g. 100 or 1000 view updates. Then you can reset the original canvas and draw only what was added to it since the last copying. This would improve performance by factor 100 or 1000 respectively.

**Comment by bartonaz** [comment]
I believe this issue is first of all related to the nature of Canvas, which is used as backend in Paper.js. Redrawing all the elements every time is difficult and will always be. I see two options to improve this situation:
Difficult: Make Paper.js intelligently determine the area of the canvas that has changed since last project.view.update() and redraw only this area. It is not really clear to me how exactly this can be implemented efficiently.
Easier: In case users are not going to erase any parts of the canvas, but only draw on top of it, you can create a second background canvas under the one used by Paper.js, and copy the state of the original canvas to the background one after every e.g. 100 or 1000 view updates. Then you can reset the original canvas and draw only what was added to it since the last copying. This would improve performance by factor 100 or 1000 respectively.

**Comment by lehni** [comment]
Related: Related: #377, #820, #484
