### ISSUE TITLE
Curve.getParameterOf doesn't properly return null for some shapes

### ISSUE THREAD

**Issue by Aciho** [paperjs/paper.js#708]
Demo here:

http://goo.gl/jpfGLf

I would expect all these to behave identically, but for some reason the two rectangular paths always return a non-null value from curves[0].getParameterOf(point).

**Comment by lehni** [comment]
@hkrish, this appears to happen because of a bug in your new cubic / quadratic solver code:

For example, the cubic equation with the parameters `a = 0 b = 0 c = 0 d = -100` returns infinite solutions, while it should return zero:

```js
var roots = [];
console.log(Numerical.solveCubic(0, 0, 0, -100, roots));
```
The old solver correctly returns 0. Could you please look into this?

**Comment by lehni** [comment]
@hkrish I looked a bit into what's going on, and I have a feeling this is happening:

- `solveQuadratic(a, b, c, roots)` is called with `a = 0 b = 0 c = -100`
- The discriminant `D` ends up being `0`
- Your code tries to pre-condition the coefficients, but since `D` is `0`, it ends up multiplying them all with `0` (https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L199)
- Since both `B` and `c` are now `0`, the code that checks for infinite solutions will always returns -1 (https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L209)

Proposed solution: 

Check that D isn't exactly `0` here: https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L184

**Comment by lehni** [comment]
@Aciho thanks for spotting this! And I shall still implement unit tests for this not to creep back.
