### ISSUE TITLE
Boolean unite() fails on shapes where multiple intersections occur in the same point

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#787]
In the current boolean-fix branch, `path.unite()` still fails on the test case below. I was able to simplify it and by using a horizontal line I made sure that this has nothing to do with tolerances. 

In this case, the first two paths touch at one point, and one curve of the third path goes through this point.

```javascript
var path1 = new Path({segments:[
  [260, 250, 0, 0, 0, 0],  // point shared with path2
  [270, 230, 0, 0, 0, 0], 
  [290, 260, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
  [260, 250, 0, 0, 0, 0], // point shared with path1
  [250, 230, 0, 0, 0, 0],
  [250, 260, 0, 0, 0, 0]
], closed:true});
var path3 = new Path({segments:[
  [300, 250, 0, 0, 0, 0], 
  [250, 200, 0, 0, 0, 0], 
  [230, 250, 0, 0, 0, 0]
], closed:true});
 
var result1 = path1.unite(path2);  // result1 is a compound path
var result2 = result1.unite(path3);  // this fails

```

**Comment by lehni** [comment]
So I think this special case requires some refactoring, since any intersection (CurveLocation) object cannot simply have just one other intersection, but an array of them... Most of the time, there will just be zero or one, but when there are more, we need to loop through them and find one that contributes to the resulting boolean shape. It shouldn't be too hard...

**Comment by lehni** [comment]
But first I need to figure out why the intersections array contains one of the solutions twice although I am filtering them all.

**Comment by lehni** [comment]
Today I realized that our way of sorting and merging locations didn't eliminate all double solutions, causing issues in many edge cases. I developed a new approach that performs as well, but really seems to filter all the doubles out: 2750c34090ad56908ad1e5c4e576491c968a5f0b

@iconexperience please let me know if this seems to improve things at your end. i have a feeling it will.

**Comment by iconexperience** [comment]
@lehni IUnfortunately I do not see any improvements, maybe even a few more glitches than before. The example of this issue and my example in #784, and as far as I can see those were the only types of issues that were remaining. I will check if a third one has surfaced since the latest change.

A new thing of course is that I get "Unable to switch to intersecting segment" messages for each glitch.

**Comment by iconexperience** [comment]
For the tiny loop cases I now get a "Segment already has an intersection" message before they fail.

**Comment by lehni** [comment]
Yeah #784 is not solved by this, neither is #787. But the solutions that sorted and merged in a more robust manner, reducing the amount of intersections to process in quite a few cases. It could well be that given the miss-handling of these two issues and the fact that too many intersections are found sometimes has the opposite effect that randomly the right segment to continue with gets chosen... So I'm not worried by a slight increase of failing cases until these two issues are tackled.

**Comment by lehni** [comment]
I made great progress on the code handling multiple intersections today, and many edge cases seem to now be handled reliably, e.g. everything described in #784. But with this particular case here it's a bit more complicated: Since we're now resolving self intersections before the boolean operation pass, the intersection point between the  two separate shapes that get united in a compound path (the only point in which they touch) isn't listed in the intersections array that's used for the boolean op. I now need to find a way to preserve such intersections across the code that handles the resolving of self intersections and associates it with the right segments in the resulting shape, so it can be used as potential intersections in the boolean pass as well. Complicated stuff, and not sure if it's explained well, but the good news is: I know what to do... Implementing this will also solve some remaining minor woes with exclude() operations.

**Comment by lehni** [comment]
PS: I am aware of some remaining edge cases where the new code now fails while it previously didn't. I will investigate these further soon, before tackling the issue outlined above.

**Comment by lehni** [comment]
This one now works as it should, along with all the test-cases in #784! My assumption above was wrong, and the solution was much simpler. Unfortunately this broke a couple of simpler cases that I need to look into now. But we're definitely on a good track here.
