### ISSUE TITLE
Issues with interoperability and scoping

### ISSUE THREAD

**Issue by jsmits21** [paperjs/paper.js#824]
The way you're scoping paper is nice when you want to run a singular canvas at any one time, but a lot of modern web developers use libraries like Backbonejs and Angularjs to organize their html in views. Views then have subviews or objects that the view interacts with.

It would be nice to have the ability to scope Paper to a specific canvas element that is rendered on the page. As far as I can tell, there is no way to do this because Paper is a psuedo global object like 'window'. A nice syntax would be something like:

{
  this.canvas = Paper.canvas('object_id');
}

That way, the view object can now use this.canvas to do all it's animation code.

**Comment by lehni** [comment]
Hmmm. We are already scoping things properly through separate `PaperScope` objects. E.g. this page is running many examples on the same page, without interferences or overlaps: http://paperjs.org/features/

It might just not be so clear as to where the magic happens when working with PaperScript code, in which case it feels like it's all global, while it's actually scoped. If you work with JavaScript directly, you have to set up the scopes, as you can read here: http://paperjs.org/tutorials/getting-started/using-javascript-directly/
