### ISSUE TITLE
Possible Mouse Event Bugs?

### ISSUE THREAD

**Issue by jth41** [paperjs/paper.js#842]
I was attempting to do something on mouseup on a raster. However the event does not seem to fire when I use the global tool space.

Note this [sketch](http://sketch.paperjs.org/#S/nZI9T8MwEIb/yslLG6mN9yAmGEFCRUyYwaTXxE1zZ9mXZKj637GTwgQd8Pbex3Ovzz4rsj2qSr12KHWrNqrmfdZaw0NAKwgWgo2CAZxgD0N01IC0CG+7J0OjDd/peyCcYDeLtVGtiK+09tZjOMaSQ6NlEA7OnqJ2vW0w6olDl3DbyUm7XTBR90y2PPrGqOLOkKHk5JlHnGdeRwnPqkbKig+zGh1OhpaK0nN04piSqxwvl9KZly1HsUEeg21e2JHM4Wsj03rV8xBxzxOtNnAYqM6gNY4JUcDZEKRTM0U+YXniJt31auunL1sHQ5fid3Ka+y9y6rtNHvzf3JvowS/bTtz0BT7Tw3c+byaq6v3j8gU=), where clicking and dragging yields a log something like this:

> raster mousedown

> raster mousedrag

> ... [more "raster mousedrags"] ... 

> raster mousedrag

> raster mouseup

indicating the `raster.on('mouseup' function() {...});` was hit properly, as expected.

However, in this [sketch](http://sketch.paperjs.org/#S/nVM9b9tADP0rhBbLgCOhq4pOydiggY2iQ9XhItHSxRIp3FHWEPi/l3eyk1hNMvQ2fj0+ku+eEzI9JkWyO6BUbbJJKq6Dnedw69AIggFnvKADK9jD6C01IC3Cz+33ko7GXcLfgHCCbTTSMmlFhiLPBzOge/IZuyaXUdhZ0/nc9qZBn0/sDgp3M1lpb2YYn/dMJnsamjJZfy2pJGVyz0eMPc+thKNVIQWL99E6WpxKmjOygb0Vy6Ssgj+bUyNeoOzFOLlzpnlgSxLd+5GqWMF0z6PHO54oxaPWreG5JNB3XaXQMay9ZozT+ziav8AJL7Joedphh9WZadjfg5E226rLUNNh+qYivL3jvljw2FynCBdveS2iXhwf8JY7dgWsHNardxN+2VraAr68xk7zMS6mHmUnPMQRLoLwcRSswahwdHyolSKkYSomBOuhioqq12CohnGAR6yMrggmVCpQa9Zrh6vlZA571cAPWi4ktChA3IiLOcZhdi8mmG/0IhOmdNWHK9V67dUGLsdbHKxi8txh1nGjyj6L8KUuCBUUet7QP8jK8L+Qte5z5HH4GPdT6HGY/5bi6od/1KMcolZ8Uvz+c/oL), which contains functionality for displaying the dragged area, the `raster.on('mouseup' function() {...});` is not hit properly. Note that the log does not contain "raster mouseup", only "raster mousedown" and "raster mousedrag".

Why in the second instance does mouseup not fire on the raster?

**Comment by bmacnaughton** [comment]
I'm not sure how to classify this. The problem is that both the raster and the red rectangle are children of the layer and the red rectangle is the top-most item. The code finds the hit on the red rectangle and bubbles up to the layer for which there is no handler. It never checks the item underneath the red rectangle (the raster image). There are various workarounds but it's not clear that this is a bug. It depends on how the mouse interactions are defined.

**Comment by lehni** [comment]
Yeah I do consider the lack of events bubbling up a bug, and I plan to fix this since quite a while...

For now, there is a simple work-around: If you mark your red rectangle as a guide, it will not be considered in the hit-test. [Updated sketch](http://sketch.paperjs.org/#S/nVQ9b9tADP0rhBbbgCOhq4pOydiggY0gQ9XhItHSxRIp3FHWEPi/l3eyk1h1MvQ2fj0+kk96Tch0mOTJdo9SNsk6KbkKdpbBrUMjCAac8YIOrGAHg7dUgzQIj5ufBR2MO4d/AOEIm2gsi6QR6fMs602P7sWn7OpMBmFnTesz25kafTay2yvczWiluZlgfNYxmfSlr4tk9b2ggpTJPR8w9jy1Eo5WiRQs3kXrYHEsaMpIe/ZWLJOyCv50So14gbIX4+TOmfqBLUl07wYqYwXTPQ8e73ikJR60bgWvBYG+yyqFjmHtNWEcr+No/gwnvMii4XGLLZYnpmF/D0aadKMuQ3WLyw8V4e0cd/mMx/oyRTj/yGsW9eJ4j7fcssth4bBaXE14spU0OXybBevBVpiDuAHfA8fpTGdTz7UV7uNwZ6n4OCRWYFRSuhiolDwsw7xMCNZDGbVWrcBQBUMPz1gaXR6MqCSh0qz3DhdrSx12qo5fNF9VaDFRnQ0x9FcnmK73JiCm5aIL96tUB4s1nM86O2XJ5LnFtOVaNX+S51tdkDAo9LShf5CV4X8ha93XyEP/Oe6X0EM/fXWKq7+CZz3KPqrIJ/nvP8e/)

**Comment by lehni** [comment]
Related: #339

**Comment by lehni** [comment]
I've been looking more into this now, and compared it with how HTML work also, and I've realized that you get the same behavior there. So I don't think this is a bug... The event actually bubbles up correctly now, but the rectangle is not a child of the Raster, so it doesn't reach it (rasters can't have children). 

My workaround above is the correct way to handle this, another way would be to install the mouse handling event on the parent items (e.g. group, layer), or directly on the view.
