### ISSUE TITLE
Strange behavior in intersection

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#847]
Please look at following sketch.
http://sketch.paperjs.org/#S/fZDLCsIwEEV/JWRjC6W0dRdx5Q+IXbYuYp0+MM2UJOii+O9OxFQRdCCPezOZM8nMtRyBC15ewDU9T3iDZ6+v0jDbywkO0Di2ZRpurPQ69YbUnYJork2tGUVrcBSsKrKEFdkxCbZDMvOMXJredjsotUOFRrCVGkZY+YN7vPGLHx49Sdd/kPck/4DzJ+ILvCZz/QNr4PyiBmiD2qKCVGEXLe9OB+3AWNrZKHQUh3ohkqXZz/SlRvy8QB97MiAvE1KO5aI63h8=

`shapeRect.intersects(pathRect)` is `true`, but `pathRect.intersects(shapeRect)` is `false`.
It looks strange.

**Comment by iconexperience** [comment]
Yep, that is strange. Especially since the correct result is calculated if you change the Shape to Path, <a href="http://sketch.paperjs.org/#S/jZDBCsIwDIZfpfSyDcaY81bx5AuIHt0OtUY31jWjLXoQ39102CmCYKBt8jfJl/bOjRyAC77vwauW51zhKcRXaZlr5Qg7UJ6tmYEb20rfFiGW5qIhvde2NozsbHEQ7FCVOavKJo+yRxIXJam0veVzp/UGNVrBEt0NkISLR7YKR1iBPBLpf/BiQnyBlyQuf2AtnF7UCFVoHGooNF7S+dlFZzxYR55L40RZ7Bctn4f9TJ97ZFMB/evRguxHpBzHxaF5PAE=">as you can see here</a>. The good news is that it's obviously not a but in the boolean code.

**Comment by sapics** [comment]
Thank you for response!

I guess that it would be fixed as follow. 
https://github.com/paperjs/paper.js/blob/1e72447a7d0a90b960daff8694e1bb44e55457cd/src/item/Item.js#L1646
```diff
-  _matrix || item._matrix, true).length > 0;
+ _matrix, true).length > 0;
```

Because, item._asPathItem() have already applied item._matrix as  https://github.com/paperjs/paper.js/blob/1e72447a7d0a90b960daff8694e1bb44e55457cd/src/item/Item.js#L1625.

**Comment by lehni** [comment]
You are right @sapics that is indeed the fix. Thanks for spotting!
