### ISSUE TITLE
Curve time parameter not linear?

### ISSUE THREAD

**Issue by yscik** [paperjs/paper.js#851]
Hello!

I'm trying to walk through "curves" (straight lines) of a path, using `curve.getLocationAt`. 
When using the curve-time parameter form of the method, passing in values from 0 to 1, the distances between two consecutive points are larger at the middle of the scale. 
Here is a table showing the x,y coordinate and pythagorean distance (r) related to the previous point: 

 x | y | r  | parameter
 --- | --- | --- | ------
-0.94 | 0.36 | 1.01 | 0.2
-2.55 | 0.99 | 2.74 | 0.3
-3.76 | 1.46 | 4.03 | 0.4
-4.57 | 1.77 | 4.9 | 0.5
-4.97 | 1.92 | 5.33 | 0.6
-4.97 | 1.92 | 5.33 | 0.7
-4.57 | 1.77 | 4.9 | 0.8
-3.76 | 1.46 | 4.03 | 0.9
-2.55 | 0.99 | 2.74 | 1
-0.94 | 0.36 | 1.01 | 1.1

And here is the result using getLocationAt with the corresponding percentage of `curve.length` as the offset:

 x | y | r  | offset
 --- | --- | --- | ------
-3.09 | 1.8 | 3.58 | 7.14
-3.09 | 1.8 | 3.58 | 10.72
-3.09 | 1.8 | 3.58 | 14.29
-3.09 | 1.8 | 3.58 | 17.86
-3.09 | 1.8 | 3.58 | 21.43
-3.09 | 1.8 | 3.58 | 25.01
-3.09 | 1.8 | 3.58 | 28.58
-3.09 | 1.8 | 3.58 | 32.15
-3.09 | 1.8 | 3.58 | 35.72

Results as expected. Am I missing something with the time parameter or would this be a bug with non-beizer curves?

**Comment by lehni** [comment]
That's a known quality of bezier curves, and Paper.js offers many ways to simplify working around their nature. Curve-time parameters of bezier curves are only linear when the handles are positioned at 1/3 and 2/3 of the line (turning the curve into a line, of course).

In order to step linearly along an aribtrary path / curve, use the version that receives an offset, and loop up the path / curve's total length.

Also, please note that this is an issue tracker for bugs, not a forum for support. There's the mailing list for that.
