### ISSUE TITLE
Reported key value does not match character

### ISSUE THREAD

**Issue by tjunnone** [paperjs/paper.js#881]
There's still something a bit funny with the recent keyboard changes:

In git (8f4e0f16a0985):
Pressing + - and / keys respectively (US keyboard, no modifiers required) gives the following values:
KeyEvent {event: KeyboardEvent, type: "keydown", key: "k", character: "+"}
KeyEvent {event: KeyboardEvent, type: "keydown", key: "m", character: "-"}
KeyEvent {event: KeyboardEvent, type: "keydown", key: "o", character: "/"}

While in 0.9.25 it gives the expected values:
KeyEvent {event: KeyboardEvent, type: "keydown", key: "+", character: "+"}
KeyEvent {event: KeyboardEvent, type: "keydown", key: "-", character: "-"}
KeyEvent {event: KeyboardEvent, type: "keydown", key: "/", character: "/"}

**Comment by lehni** [comment]
Which browser and system are you on again?

**Comment by lehni** [comment]
This is insanity... Hitting the '.' key on my keyboard produces the native keyIdentifier value of 'U+007F' (accessible through `event.event.keyIdentifier` in a paper.js event handler). Converting that to a string turns it into '¾'. And it gets better: Hitting Shift + 1 produces a `Execute`.

I shall investigate a bit more and file a bug report with the Chrome folks. But since `event.key` / `event.keyIdentifier` is suppose to be the way forward and solves issues on other systems, I'd like to stick with it and get the Chrome folks to fix this bug instead.

**Comment by lehni** [comment]
And since when is `console.log(String.fromCharCode(127));` supposed to be `'¾'`? This gets weirder and weirder! Can you confirm you're seeing the same on your system [through this sketch](http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfGT8/OK83NS9XLy0zWCS4oy89L10oryc50zEoucgSo0DI3MNTWtY/KAOpKKUhOzC/Iz80qKlayiY2sB)?

**Comment by lehni** [comment]
It gets better: Chrome on Ubuntu appears to provide different `keyIdentifier` values for these keys in the `keydown` and `keypress` events, unlike any other browser I have encountered.

For the example above (the simple '.' key on the Swiss German keyboard), I get `'U+007F'` in the `'keydown'` event and `'U+00BE'` in the `'keypress'`event. Needless to say, either of these are wrong!

**Comment by lehni** [comment]
Sometimes a bizarre bug like this has a simple solution. : )

**Comment by tjunnone** [comment]
Nice detective work :) Confirmed that fix is good.
