### ISSUE TITLE
Small proposals for code improvements

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#891]
I have found two parts in the code that I think could be improved slightly. But I am not sure if I am correct, so I decided to propose them here:

1) https://github.com/paperjs/paper.js/blob/develop/src/path/CurveLocation.js#L452

Currently
```javascript
                var l = c.getLine(),
                    l1 = t1Inside ? c3 : c1,
                    l2 = t1Inside ? c4 : c2,
                    straight1 = l1.isStraight(),
                    straight2 = l2.isStraight();
                if (straight1 || straight2) {
                    return straight1 && l.intersect(l1.getLine()) ||
                           straight2 && l.intersect(l2.getLine());
                }
```

Proposal:
```javascript
                var l = c.getLine(),
                    l1 = t1Inside ? c3 : c1,
                    l2 = t1Inside ? c4 : c2;
                 return l1.isStraight() && l.intersect(l1.getLine()) ||
                         l2.isStraight() && l.intersect(l2.getLine());                
```

2) https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1896

Currently:
```javascript
            } else if (straightBoth) {
                // If both curves are straight and not very close to each other,
                // there can't be a solution.
                return null;
            }
            if (straight1 ^ straight2) {
                // If one curve is straight, the other curve must be straight,
                // too, otherwise they cannot overlap.
                return null;
            }
```

Proposal:
```javascript
            } else if (straight1 || straight2) {
                // If one curve is straight, the other curve must be straight,
                // too, otherwise they cannot overlap. But if both curves are 
                // straight, the overlap must have been found above.
                return null;
            }            
```

**Comment by lehni** [comment]
I think both proposals change the behavior. here's an explanation:

1. My code only returns if one or both curves are straight, but carries on if they are both not straight. Yours returns always.

2. The separate `if ()` statement in my code returns if one of the two is straight and the other isn't, regardless of what has happened beforehand. Your proposal connects it to the previous statements through a else. Now this would work if the only previous one would be `if (straightBoth)`, because that would cover the case were both are straight, hence not requiring the xor check anymore. But since that previous check itself is connected through a `else` to what comes before, it doesn't behave that way.

Does this make sense? Does the code need better explanations in comments?

**Comment by iconexperience** [comment]
Yes, both make sense. And no, I the comments are fine, I just thought I had found two simple improvements, but I was wrong.
