### ISSUE TITLE
onLoad not called when loading paper.Raster from canvas

### ISSUE THREAD

**Issue by sebastian-nowak** [paperjs/paper.js#924]
According to the docs `source: HTMLImageElement⟋HTMLCanvasElement⟋String — the source of the raster` so `paper.Raster(source, ...)` constructor should work correctly when given a canvas.

Let's try this:
```
var raster = new paper.Raster(someCanvas, new paper.Point(0, 0));
raster.onLoad = function ()
{
  alert('This function is not called');
};
```

If we replace someCanvas with url or data url, the `onLoad` callback is called. When given a canvas, it loads successfully but callback isn't invoked. Tested on paper 0.9.25.

// Edit: after looking into the source, it appears that onLoad won't be called when passed an image too.

**Comment by lehni** [comment]
I don't think an onLoad even makes sense for a passed canvas object, as that's a buffer in memory, not something you load form an external source. But it would make sense for it to be called if you pass an image object which hasn't been loaded yet. So that would be a bug.

**Comment by sebastian-nowak** [comment]
I have to disagree and here's a simple example why such behavior is quite weird. 

Just imagine you're writing a library which accepts a picture in the configuration options, loads it to `paper.Raster` and do some processing. It should be possible to just forward the picture to the `paper.Raster` constructor and everything else should work without additional code.

If you don't call `onLoad` for some types, the library would have to check what type the passed picture is and run a different code for each of them, and that's pointless as all of these types are directly supported by Paper.

So please, keep the api consistent and invoke the `onLoad` callback when `paper.Raster` finishes loading the passed picture, no matter the type. It's the most intuitive and friendly way.

**Comment by lehni** [comment]
Well, there are different ways of defining consistency. Currently, only the setter for `Raster#source` handles the `onLoad()` calls, just like setting image.src would trigger a `load` event on an native image, once the content is loaded (or was retrieved from the cache).

The setter for `Raster#image` doesn't trigger `load`, which I think is expected behavior, since you're passing an image and are responsible for its contents yourself. There is nothing to load for Paper.js, as it's assuming the image or canvas is in memory alread. Paper.js is not checking if the image is loaded already, and it is not waiting for it to be available. It copies its contents right away, and hence it would be misleading if it was emitting the `load` event, because that would suggest otherwise.

The constructor looks at the passed object and decides if it should use the `source` setter or the `image` setter. In a typed language, this would not be one constructor, it would be two, and only one of them would trigger the `load`events, the one receiving the string argument.

From where I stand, I think the current behavior is pretty consistent, and adding what you'd like to add would make it unclear as to what is actually happening internally.

**Comment by lehni** [comment]
Thinking a bit more about this, I guess I could move the whole `load` event handling to the `Raster#image` setter, and then use that from `Raster#source`. I think that would probably be the more elegant solution anyway : )

**Comment by lehni** [comment]
This turned into a rather big undertaking that made me add functionality to jsdom (https://github.com/tmpvar/jsdom/issues/1365) and prioritize #739. Things are now in place for this to be addressed next.
