### ISSUE TITLE
Paper.js mouse events not translating with canvas transforms

### ISSUE THREAD

**Issue by davidrhoderick** [paperjs/paper.js#945]
For performance and aesthetic reasons, I am transforming a canvas with a Paper.js "drawing" in it with a CSS transform (rotation). Basically, on scroll, the canvas rotates, with a transition-duration to smooth it out.

On top of that, my Paper.js paths have mouse events on them so that on hover they change color. However, when the CSS transform is applied to the canvas, the mouse events "disappear," for lack of a better word, and they don't work. I guess somewhere along the line, the CSS transform is working on the canvas drawn elements but is skipping over or applied differently on the mouse events created by Paper.js tied to my paths. Is there any solution?

**Comment by lehni** [comment]
Yes this is because there is no wide-spread API yet to factor in these transformations when dealing with mouse coordinates. Some browsers had a method for it but have deprecated it, e.g. [webkitConvertPointFromPageToNode](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/KS5GAM7JXtg/3jx_wEo5_LoJ). There is the new [GeometryUtils](https://drafts.csswg.org/cssom-view/#the-geometryutils-interface) proposal but that's not implemented anywhere yet, as far as I can tell.

The work-arounds involve so much code that I think it's better for now to have people who need this write their own mouse handlers. See here for some potential starting points:

https://gist.github.com/Yaffle/1145197
https://groups.google.com/d/msg/paperjs/owbBzmTFBnk/VUYEHWCmAQAJ
