### ISSUE TITLE
Nighly builds not created anymore

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#950]
After failing to build paper from the latest source I decided to simply use the nightly build for testing, but alas, they don't build them like they used to anymore.

The latest nightly build is from January 17. Is this intentional or is there something broken with the automatic build process?

**Comment by lehni** [comment]
I'm aware of this. It's happening because we're in the middle of a transition. But luckily, Travis CI is already building the new nightlies for us on each commit:

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

You can for examply specify specific versions from prebuilt/module in bower.json or package.json, e.g.:

```json
  "dependencies": {
    "paper": "https://github.com/paperjs/paper.js.git#548efe658c0e6a87f2ac34856ab4a2fa0faaf736",
  }
```

**Comment by iconexperience** [comment]
Thanks, this helps a lot.
