### ISSUE TITLE
New fairly simple boolean edge case

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#951]
This came out of your test suite @iconexperience, by using the slightly different code now for calculating the curve points: [Sketch](http://sketch.paperjs.org/#S/XZPLbtNQEIZfxcomRXKO5n5pxYo1ElKXlEVI3TaqcaokUAHi3Rm3pEA3vsycmf+fb+yfi2n9ZVicLy7vh+PmbtEvNrvr+f3bet89rI932L3tpuGx+1DPZ8v3HN7MISjYQCOoF8gWGslBiK7uvBFuLJmYiGngpn1FhCwpWTNIRDpvQMpq6JIiGdmvvDGkhamFV4qlWxE2Cqi2AZJKbtRXiLWackiaJ5CNQs2i9AAgEiytrwgakloCKDrlZkXRGIFVXaolc/QVMVNmqasjuXYrL1sqEPXKRLMplsbkAF4TQjUvU8YtnL1mpQxhFelno3NJYIqLlAv6sXxzcTWdMNIrjGaNq5sSA1YLnhHVrJAOxFhcBW1TRKgYa9mTRBGm3mey4cIWdRjVu1U0jWJsxXp2WqZRW2oVhifVHYXmUyVGlJoydyiOUNOXXImBOWbKqNnqxo6I4E6aPbTaakgUk9ol2gwSWlFQZyEyF6S07KU5cgmVpEltkIpl7SmZnbXAMAAq91gfBmZwCfKsw3kyVmxrgVij5oszTaulIzM/s7yanj7Idjjud/fDu9242xfV5X64Xl485+h17nY/DNMpe6q83KzH7XRb+X9r/kZv1uNheNKbt7cfDn9OYvs6bY/D2VPVs6FKtpvtOL4Ifh/Gcfc4K/6Xauvx4W5dB6A2Wsn6zz7vh/X9w247HQ+L84+ffv0G)

```js
var path1 = new Path('M387.6708283605882,409.85893821175773c43.34991911960765,43.42692935982444 7.025356174944989,-7.309686568753534 -21.280175804952762,21.350763849679026l42.68991000890696,42.16125690051729c-28.31035574280338,28.66533466571275 -77.0540871232289,-34.32700789309064 -63.873775729843544,-21.123281947448902z');
var path2 = new Path('M366.39065230143535,431.20970231882416c-7.258856574914432,7.349874368209157 -8.587656196327089,15.955888792558142 -8.65222959434982,20.669701880671994l59.99437111077259,0.8218485401191629c-0.06457342267412969,4.7138148876486525 -1.3933735123300153,13.319830673437139 -8.652230999115659,20.669705964951333z');

path1.strokeColor = 'red';
path2.strokeColor = 'green';
path1.strokeScaling = path2.strokeScaling = false;

var res = path1.unite(path2);

res.fillColor = 'yellow';
res.fillColor.alpha = 0.25;
```

**Comment by lehni** [comment]
It looks like not all intersections are found: [Sketch](http://sketch.paperjs.org/#S/bVRNb9tGEP0rhC6WA2qz87WzI6OnoIceAhTIMc6BpdcSYYY0KDluG/i/dyhKsZuWELTaeTPzZt4M9X01NF/Larv69FCO7X5Vr9rxbr5/a6bqsTnuofqlGspz9bv/Xl99pKwhacyYKUXJGWuOFrJko4wAKqrUMgViMzAAS1GT1G5hTIZGYhmZudIQUUgSKBuzZas3GihayklSVoeIqw1CwBw9bY5sgpqwdhOJJ6XMltQipp4xpOx8McZsMVmq3QIJUJLFKKBo7QZzIIgkouwpiXLtlpSEiP1bAVWqjXpZwjH7lRDnoogDocao3mH05F5UopCV1HtFy0zCXM+FziEZjJXZq8C/r65vboeLjPiTjCkF8myCFMFT0CyR9xpNIxK4rgypdUXQNRYvjw2YCWudlc3KlLI7g2i1yUGya5xc67lSLxokmHhgVkM/gXH2cjJEE+M5g+sYvXunc7KYFMy4Fwt+kAJAVEWxOgafaubsmvgsIc1CxuAqiBIjJmVAS1ZzUCAncsrEPkF0LX1ORqQkLgzFCEI1+GKAZXJCmnnILoW5tj5A8FbtR2ViyYcORLRoeTucFjIcjtP4UD6M/Ti5qldTubu6WTD8GdtNpQwX9BL5qW36btg5/jbm1Xrf9IfiMe/fLfObyuHsC+Fp6I5lfYpbSnIw3Hd9/4Pyr9L34/PM+S8oNP3jvnGH6DN18N37OXpO3w3HMr0y7Mrxt5OltMduHA6vZK3fxr6Eftytl6DQl2F33M/g2XA/Tr827X59/zScwhfH6+r77VD5c1nB8KGb2r6sz+b5acvsuV3KCY+jn/UrOjV33dNhW8Eb2xutt8sY/gOeRd0umi7oy/Xt8LKI960rz+Frc5y6P8/vx8fTZf3ZfFH8DfTFTyCsWeoqnj7/A2x8BSH4O4MpRZ7t5EZKwgGABTkz+H7Jl+sb/3/7YyrNw6m9w2r7+cvLPw==)

**Comment by iconexperience** [comment]
I am not sure. Two intersections in the center (both are crossings) could actually be correct.

**Comment by lehni** [comment]
Yeah you're right...

![screen shot 2016-02-09 at 15 53 41](https://cloud.githubusercontent.com/assets/213275/12919636/63b56080-cf45-11e5-9085-d143b27e8578.png)
![screen shot 2016-02-09 at 15 54 03](https://cloud.githubusercontent.com/assets/213275/12919639/6511acc2-cf45-11e5-9978-3265196aa9fb.png)

**Comment by lehni** [comment]
But something with these two found intersections is strange... It's very hard to see though. I can only zoom close enough on Firefox, but even there the glitches make an interpretation pretty much impossible: [Sketch](http://sketch.paperjs.org/#S/bVRNb9tGEP0rhC6WA2qz87EfI6OnoIceAhTIMc6BpdcSYYY0KDluG/i/91GUYjctIWi58+bj7ZtZfl8Nzdey2q4+PZRju1/Vq3a8m/ffmql6bI57qn6phvJc/Y739dVHycnF5DNniT7kzLV6czlkk8xEKaQkrYoTNSMjsuhTDDUsytHYJFhmVa2S8xwkREpqqpat3iQn3mKOIeYESLTaMDnOHmmzVwucItcwSUBSyWoxmefYK7uYUc97n81HizUsFIlDNO8DJbZ2w9kJeQkhKVKK5BqWGIOI4j8Rp1BtEmgF9RlbYZ5JiTrh5H3CCT2Sg1QUl5MknJUtqwTVeiY6h2QyTapgwX9fXd/cDhcZ+ScZY3SCbIHFE1LILBHO6i15FoKuSrGFIgyNA+ipkapwnWZlc1KJGc4UUrXJLmRoHKH1zBSkKTgLCMzJGCspz14oxmzBdM4AHT1Oj3Io5mMiM+2DOSySiMinxMFq79DVrBmaoJcUZyG9gwohiTLHpMQWrVaXSFAIJaOigwwt0ScTSRIgjHhPQWrCYJBlQUGZ64hdiEFbNJBwVPvBLFhE00lEFi1vh9NAusNxGh/Kh7EfJ6h6NZW7q5sF45+x3VTKcEEvkZ/apu+GHfC3Ma/W+6Y/FMS8f7f0byqHsy+5p6E7lvUpbqEE0N13ff+j5F+l78fnuea/INf0j/sGDh49Bfju/Rw9p++GY5leK+zK8beTpbTHbhwOr8Va7Ma+uH7crZcg15dhd9zP4NlwP06/Nu1+ff80nMIXx+vq++1Q4bmMoPvQTW1f1mfz/LRl9twudNzjiLV+Rafmrns6bMHezw+9gd5Ivl268R/wrO12kXZBX65vh5dFw29deXZfm+PU/Xm+Jh9Pm/XniihHUwwm5h0ziqmsK3/6/R+y0egZn6HoMWgWcI9hC7grqvP9dkl8DtWX6xt85/6YSvNwOuZhtf385eUf)

**Comment by iconexperience** [comment]
The problem is that path 2 has a self intersection, which is first resolved when calling `unite()`. Then one of the two new sub-paths has only one crossing with path1, which cannot be correct. <a href="http://sketch.paperjs.org/#S/bVRLT+NIEP4rVi44I6en69GPymgOK7SHPYy00hyBgzENsfDYyA6wuyP++1bbCQwToigd11ePr75y9c9VX/9Iq+3q+33aN7tVtWqGm/z8VI/FQ73fQfG16NNz8bf+L8++UQzGBxsxkrcuRqzYiokuCkUECC4EapgMsQgIgHgbvKvUwugFhZxEZOYiGIuOnIfAwixRqk0wZMVH73wMChEXGwSD0WraaFkcBo+VmshpUoosPohF3zEaH7WetTaK9eIrtYAHdF6sdRBQmg1GQ2DJucCakihWavHeEbH+BsDgik1QWo5t1EdCzKSIDWGwNmiHVpMrKU8mBgraK0pkcsxVJppDIggHZmWB/52tv1z2RxnxNxm9N6TZHJIFTUFZIu3VSrBIoLoy+EYVQdXYKT0WYCasQlY2BiYf1RlcKDbRuKgae9U6M1XS4Iw4DYxBUE9gzF5aDFGccM6gOlrtXstpMesDiHDnxOhBAQBsCOikskanGjmqJjpL8FlIa1QFF4gRfWBA8VKxCUBaSEt61gmiaqlzEqJAToUha8FRBfpigETSgpTrkByJqbY6QNBW5ZWZE69DByI61XI+zWPf7lP5DrOvYLNru5sx9Rf2yjTd0Kfytu6m9M4bTr3hxPuyX3xN209p3P9xPTylct6NjC5VP8YWFMy0H4f7dD50w6gFz8Z0c/YW+Rt4N6bUv8InsdfdYzqiR/B7U3dtf3fsxX5sPvWeO9Rcnz8tkoxpOjjDQdo5cOlEQXPbdt0rk39T1w3Pmcs7yNTdw65WB6svr4KfPufonL7t92l8q3CX9n/NltTs26GflmIH3Qr9XPZLhLkdxj/rZlfePvazaznb18XPxa/R4KFLphvuygWa8szb6XwcpklbLdfrnDX7HnfQnLdj06XykGJOk3LodqFpHgY9qzd0rG/ax2lbwC+2X0azXaZ6Ah7E3i5aL+jL+rJ/Wdp8atOz+VHvx/afwwXxbX4oL0Q3Ra8g3XwPjkN0VWHn7wfARncQjF4a6L3lbCc1kndsANghRwZdMHe1/qIX/PWY6vu5vWm1vbh6+R8=">Here is the sketch</a>

BTW, there is something very strange going on in the sketch. Why does the console show the point instead of a true/false value?

**Comment by iconexperience** [comment]
Not quite right, the problem is the other sub-path that actually has two intersections with path 1. Here is the simplified example with only two triangles:

```javascript
var path1 = new Path({segments:[
    [366.3906525556354, 431.20970206143676], 
    [409.0805625645424, 473.37095896195405], 
    [345.20678683469885, 452.24767701450514]
    ], closed:true})
var path2 = new Path({segments:[
    [387.73560545337955, 452.2903284310746],
    [417.7327938178581, 452.7012527396153],
    [409.08056281874246, 473.37095870456665]
    ], closed:true});
path1.strokeColor = 'red';
path2.strokeColor = 'green';

var res = path1.unite(path2);
res.fillColor = 'yellow';
```

<a href="http://sketch.paperjs.org/#S/hVNNj9owEP0rUS4EiVr+mrGdVU+rHnqoVGmPwMEbDEQEBzlhaYX473U+WNJtq1qREs97M+M3frmm3h5dmqcvB9cW+3SRFvWm27/ZkJxsu2fJ58S7S/I9fmfXxu2OzrdNvlz5JK6lQCTCUAQOAChALhIpGOHUKMopMilQ4XqRjHRJDaGaAnJACZJ3dCWIUNSANsgMSAoPupAQS6HSqIVEozVEPnDCpUKlKJNAgcn1wI5pRVU3bpO34exu85W/a+D/0aAVUQKQggQhlIF7F0MF11EOVTJquEtgHZsrIzRTGjQbyPE0HLgSUQSIB/ldr2ZaRb04FayoBESEfwh4Wvn+BkjThvrgnuuqDlHJLLjNbMT4R2wXnPOzD5kvha1Kv4v4NOcR3dqqcTFnmFhwzchk5OzL1mV91rwnRJBsy6p6b/jTVVV96Tr+BhFbnfY2Eijh0GcOxUvfuvCov3Pt1z7iirasfTNtNVDJtg5fbLHPtmffc7I+Pk+uw9Du90qey1BULhvD3Spcx8yHnuRUx/figQa7Kc9NnrBJbDLMfJjzH+A4tXwY2oB2XrsNh34r3YUcbRvKH6PpvvWbbGmIYIJziF5iIFVnZdo/fwE+8WgjojXniFR2cRGDAkESFk3PpZZMRAet50/xj30Nzh56eU2aL9e3Xw==">And here is the sketch</a>

**Comment by iconexperience** [comment]
Am I doing something wrong or does this example actually work on the current develop path?

**Comment by lehni** [comment]
you mean branch? It doesn't work for me...

**Comment by iconexperience** [comment]
Yes, on the branch. I am a bit confused today.

**Comment by iconexperience** [comment]
You are correct, it fails on the current develop branch. I better finish for today.

**Comment by iconexperience** [comment]
As suspected in #959 removing the new edge case handling in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/CurveLocation.js#L448">CurveLocation.js lines 448ff</a> fixes this issue. But the edge case handling is certainly there for reason.

@lehni Can you give an example of an edge case that <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/CurveLocation.js#L448">CurveLocation.js lines 448ff</a> was introduced for? I am having a difficult time trying to understand what this is actually trying to do.

**Comment by lehni** [comment]
I developed this code for #865. But many things have since changed, and I am not sure that we still need it. I am a bit surprised that the line intersection code produces a solution for perfectly parallel lines though, it shouldn't really. I'll look into this all a bit more now.

**Comment by lehni** [comment]
I can find only one failing boolean test, and this is actually not a failure, juts a rendering imprecision that results from a slightly different path topology that is actually more correct. So I think we can safely delete this code and adjust that one test.

**Comment by lehni** [comment]
Here the [sketch](http://sketch.paperjs.org/#S/ZVLLTtxAEPyVlS8GyRp5usfzAOXEdSKx4pbHwSxDWNnYkW2Coij/nurxKnjhMlNT/aou+08xtM+puCruurQcnoqqOIwP8v7VTrtl92k3pNfdbbs8XZSfybPylbaNorhiIifYeGXPcePecjaYvVd+v2JTs6KKvEW+0QQ2KFMZqqUmYAZwo+yea10ZrhFjLadhUrRnHaQHg2WWO3IT3u4at2HJrs2euVkRcnMHTAZLK0uii0hU1Jh96szBy6nzKWrAu4w1Mk/YQ19c8bqlzN6g7MgpvsHZwS/l5fW3QVzuzl0WRRbGQEywUQd4pbMEH0m7bJC1kZxRWJytU9qf+rKrFSPLg8NmUiIjYbCuGsw3GrJIuYBMeB+isawcYQ+tgnn/gs2oY/mekaFJy0MraqJ8Fw+F+YpnetetFjUv09ilm7EfJ2xXTumhBN+95+/7l1RuCu4ObX8cfiD02PZz2pR8jKzmTWkGt6jjsKRpToflorvMQQTU47Hv/8/6nfp+fC2v8YvfT6ntfo6omYurr9///gM=) for that one case.

**Comment by lehni** [comment]
I can imagine that the need for this workaround has disappeared with the recent improvements of precision in `Curve evaluate()`!
