### ISSUE TITLE
event.stopPropagation on mousedown prevents mousedrag event from firing

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#952]
When calling `event.stopPropagation()` in a mousedown handler no mousedrag events fire.

[example](http://sketch.paperjs.org/#S/dVCxrsIwDPwVK0tbqYoQY9CbntiRGClDSE2JmtpRkrYD4t9pgEpveHg73/nu5LsgPaBQ4thjMjdRC8NtxpMOYBMO8AOEMxxv2qPcO2d9xPLeECwTdGvHqGC72dTvTUyBe/xlx0FBcXHa9MWHulrnViJgu649R5ssk4LJ4iwNUsLQ0KPaNdRQbiCZymLgMWLLMxU1XEcy+aTEaVFX8G7zAjIm9ofAXnf6Jck2C2mYIjuUjru/XtUOvkUF3X2N+scty1e35YmXgLr3bClFoU7nxxM=)

**Comment by lehni** [comment]
First of all, please note that the mouse handler behavior has been overhauled completely since the last release (v0.9.25). So just to make sure: are you using a fresh build already? And it is to be discussed if this is a bug or not... A mousedrag is a "fake" event, initiated by a mousedown. If you tell a mousedown to prevent the default, one could argue that handling the following mousemove events as drags is the default that is to be prevented... To understand this better: What's the use case of this, why are you calling `preventDefault()`?

**Comment by georeith** [comment]
@lehni It is `stopPropagation()` not `preventDefault()`. `stopPropagation()` should just prevent the event from bubbling not prevent side effects. Whilst I agree that `preventDefault()` on `mousedown` should prevent `mousedown` just like it prevents `dragstart` in HTML.

The use case is that I have a `mouseDown` on the view and a `mouseDown` on an Item. When one is triggered I don't want it to bubble to the other but I still want my drag handlers to occur on that element.

**Comment by lehni** [comment]
Yes, apologies for misreading. That makes more sense. It's well possible that the behavior changed, so please test with a recent build, see here: https://github.com/paperjs/paper.js/issues/950#issuecomment-181827285

**Comment by georeith** [comment]
@lehni just tested with latest `prebuilt/module` and this appears to have been fixed.

**Comment by georeith** [comment]
Woops... I just realised I tested with `event.event.stopPropagation()` not `event.stopPropagation()` this still exists.
